### ISSUE TITLE
Backend database migration feature

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1002]
Requirements: 

* Stop erasing MySQL data on upgrading/re-installation
* Store database structure version in the database
* Detect version and run required migration scripts
* Add `statistics` migration script

**Comment by wiz** [comment]
> Stop erasing MySQL data on upgrading/re-installation

IIRC that's outside the scope of this project, and only done by the installation scripts in third party integrations like RaspiBlitz et al, so I think it's up to those projects to handle that part

**Comment by wiz** [comment]
> Add statistics migration script

IMO this shouldn't be a script but simply a feature in the backend. For example on startup if it doesn't see the SQL tables it should create them (like most applications do, most apps don't require you to manually create the SQL structure these days) and if it sees the old database it can migrate it and set the new version number in the version table
