### ISSUE TITLE
CPFP tag overlaps with the fee rate on smaller screens

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#1006]
![Screenshot from 2021-12-12 22-36-24](https://user-images.githubusercontent.com/100320/145764128-0f2d9ef6-97b4-44ea-b60a-eee89cd2e446.png)

v2.3.0-dev [271726bf]

**Comment by wiz** [comment]
Obviously this is why the button is transparent, so you don't miss out on seeing that important data 😂
