### ISSUE TITLE
[Liquid] Unconfidential address page looks broken on smaller screens

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#1013]
https://liquid.network/address/ex1qqmmjdwrlg59c8q4l75sj6wedjx57tj5grt8pat

![0CB55EAF-DB47-48F9-805F-470507AC5054](https://user-images.githubusercontent.com/100320/146115796-ec362d08-7859-462b-bba7-8c2b0c529827.png)

**Comment by wiz** [comment]
Verified fix in #1018
