### ISSUE TITLE
Can't see any info about next block

### ISSUE THREAD

**Issue by nrazavi70** [mempool/mempool#1028]
Hey
I am trying to run mempool on an ubuntu 20.04 server and have been experiencing some issues throughout the way. 
To give you some perspective as how I arrived at this point:

**Dependencies:**

**Bitcoin** : The node is placed on another server and is working at the moment.
**NodeJs, Nginx,MariaDB** : Followed the instructions at your [Readme.md](https://github.com/mempool/mempool/blob/master/README.md) and it worked flawlessly.
**Electrum** : After hitting some tough walls with packet headers and SSL issues while building the backend (it was having some issues with electrum that I got from electrum.org) I managed to skip that issue by getting the [Electrs package](https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder) from apt repositories. It took some time to sync and start the electrum server but it is done now and is serving data on a specific port.

**Frontend and Backend:**

**Backend :** Followed the instructions on your readme and it seems to be working now. (States that it's connected to Electrum server, database and it claims that it is serving data on appropriate port at the moment)
**Frontend :** There seems to be issues when I copy the nginx.conf and nginx-mempool.conf files to nginx as it returns 503 server unavailable. When I run the npm run start at frontend directory, I can see some data about current blocks on the browser but there is no data about the next block, incoming and latest transactions. 

P.S. I'm not receiving any errors anywhere

**Comment by wiz** [comment]
Hey there,

For manual deployments, the default nginx.conf is just an example, it will require tweaking for your specific use case. If you want something easier I would recommend trying the integrated one-click installation on Umbrel or the other popular Bitcoin fullnode distros with "app store" style easy installation.

If you have further questions feel free to join our chat groups for support

**Comment by nrazavi70** [comment]
I have no idea where those chat groups are. If you would let me know I'd be happy to join

**Comment by wiz** [comment]
The links are on the about page
