### ISSUE TITLE
  ELECTRS_API_URL

### ISSUE THREAD

**Issue by wchance** [mempool/mempool#103]
### Description

I followed all instructions but get stuck when trying to run the backend.    
Seems the following line "ELECTRS_API_URL": "http://localhost:50001" in mempool-config.json is missing a step.

I have bitcoin node credentials do we also need to have electrum wallet running on server?

Are there instructions to install this?

Updating mempool
getRawMempool error. { Error: connect ECONNREFUSED 127.0.0.1:50001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 50001 }
Error getMempoolInfo { Error: connect ECONNREFUSED 127.0.0.1:50001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 50001 }
updateBlocks error { Error: connect ECONNREFUSED 127.0.0.1:50001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 50001 }

#### Version

master v.2.0.0

**Comment by softsimon** [comment]
The master (v2) version other than bitcoin core, requires blockstream/electrs as backend, that is the url it wants "ELECTRS_API_URL".
Blockstream/electrs is very heavy and require around 1 TB SSD disk space.

**Comment by wchance** [comment]
Is there any public url I can use?

**Comment by softsimon** [comment]
Yes can use these actually:

https://blockstream.info/api/
https://mempool.space/api/

It needs to be set both in the backend config
`"ELECTRS_API_URL": "https://blockstream.info/api"`

But also on the frontend which is a bit more tricky. You might need to run the web app in development mode and change the URLs in the `proxy.conf.json` file under the

```
 "/api": {
    "target": "https://blockstream.info/api",
    "secure": false,
    "pathRewrite": {
      "^/api": ""
    }
  },
```

I think that should work.

**Comment by wchance** [comment]
Thanks guys!
