### ISSUE TITLE
After installation REST API is not woking properly

### ISSUE THREAD

**Issue by nrazavi70** [mempool/mempool#1030]
Some API calls are returning "Cannot GET /api/v1/" . Below you can find the list of all API calls that are not working, the rest of them are working as intended.

Get Address Transactions Chain
Get Address Transactions Mempool
Get Address UTXO
Get Block Raw
Get Block Status
Get Block Tip Hash
Get Block Transaction ID
Get Transaction Merleblock proof
Get Transaction Merkle Outspend
Get Transaction Raw

P.S. I know this is not the proper place for these issues but I couldn't find any info on your community in social media. Searching your name in telegram returned a channel. Nobody seems to be checking it though. If you'd be so kind as to let me know where I can contact your team about such matters, that would be great
Thanks

**Comment by wiz** [comment]
Is this a manual deployment? What backend are you using? It's probably related to your nginx configuration, which nginx file did you use?

**Comment by nrazavi70** [comment]
Yes it is a manual deployment. What do you mean by which backend? Used "npm install --prod" for the backend.
I can tell it's not nginx since it returns the same response from localhost:8999

**Comment by wiz** [comment]
What I meant by backend was, which of these are you using:

1) bitcoind RPC only
2) bitcoind RPC + romanz/electrs
3) bitcoind RPC + blockstream/electrs

**Comment by nrazavi70** [comment]
The second one.
I used romanz/electrs

**Comment by wiz** [comment]
It's likely your nginx configuration. Manual deployments require some sysadmin work to get everything working for your specific environment... check to make sure everything is correctly routed to the mempool backend and the mempool backend configuration is correct, you probably want a near-default config file.

**Comment by nrazavi70** [comment]
The thing is when I connect to the the backend on 8999 which is the default port for it, it returns similar results.
That is it returns appropriate results for some API calls and "Cannot GET /api/v1/" for the ones mentioned above.

**Comment by benichu** [comment]
Having the same kind of issue described here with my raspiblitz install that is running that script: https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/bonus.mempool.sh

`../api/v1/1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY/utxo` returns a 404 through NGINX or directly querying the backend endpoint: `http://127.0.0.1:8999/api/v1/1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY/utxo`

**Comment by wiz** [comment]
I would guess it's your mempool backend configuration and/or your nginx configuration. The examples provided in this repo should work out of the box.

**Comment by wiz** [comment]
Have you tried our Docker installation method? That might be easier for you. See the top-level README for instructions

**Comment by benichu** [comment]
No worries, I want to find out why it's not working on my vanilla raspiblitz install, it might be nothing, I'll report if I find anything on what makes some endpoints return `404` even querying directly at the backend level...

**Comment by harrybawsac** [comment]
@nrazavi70 What worked for me was changing `/etc/nginx/nginx.conf`. At the bottom of the file it says `127.0.0.1` but it only works when it's set to `0.0.0.0`.

**Comment by wiz** [comment]
For manual deployments you're on your own in terms of the nginx configuration - the nginx.conf supplied is merely an example - perhaps documentation could be clarified but if you want a one-click installation we're on Umbrel and the others

**Comment by pxsocs** [comment]
I believe this is an issue impacting most node implementations. I've tested on RaspiBlitz and Umbrel and both have the same behavior.

For example, when trying to get the API endpoint below: 
`http://raspberrypi.local:4080/api/address/1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY/utxo`

it returns:
`Cannot GET /api/v1/address/1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY/utxo`

While the API at mempool.space works fine:
`https://mempool.space/api/address/1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY/utxo`

@harrybawsac - On a RaspiBlitz implementation, following your suggestion, I've tried editing the `nginx.conf` at `/home/mempool` to:
```
http {
  server {
                  listen 0.0.0.0:80;
          }
}
```
But no success. Can you provide more details?

@lukechilds @mayankchhabra @rootzoll - maybe you can provide some insight?

**Comment by harrybawsac** [comment]
@pxsocs I've turned off mempool on my RPi completely. It was nearly impossible to compile everything anyways. Since I'm not running Docker, I saw no other option then to resort to the good ol' [btc-rpc-explorer](https://github.com/janoside/btc-rpc-explorer).

**Comment by pxsocs** [comment]
Got it... Will probably revert to btc-rpc as well... Thanks!

**Comment by void-the-dev** [comment]
@wiz , this issue is happening with docker too:

<img width="751" alt="api" src="https://github.com/mempool/mempool/assets/125810391/0083f4e8-3297-4965-bd55-57bd63a98e7d">

I'm running Fulcrum on ubuntu
Any ideas on how to solve this?
Thanks in advance

**Comment by void-the-dev** [comment]
It seems the code doesn't have those routes defined:

https://github.com/mempool/mempool/blob/feed25b6419d3e390ddf22efda76440b0ffc3678/backend/src/api/bitcoin/bitcoin.routes.ts#L122

There is no code implementation for those endpoints, it's mentioned in the `api-docs` but it lacks an implementation

**Comment by nymkappa** [comment]
> It seems the code doesn't have those routes defined:
> 
> 
> 
> https://github.com/mempool/mempool/blob/feed25b6419d3e390ddf22efda76440b0ffc3678/backend/src/api/bitcoin/bitcoin.routes.ts#L122
> 
> 
> 
> There is no code implementation for those endpoints, it's mentioned in the `api-docs` but it lacks an implementation

Only /api/v1 hits the nodejs backend. Other /api endpoints hits directly the bitcoin backend (fulcrum in your case). So your setup is wrong.

**Comment by 0xBEEFCAF3** [comment]
> @wiz , this issue is happening with docker too:
> <img alt="api" width="751" src="https://user-images.githubusercontent.com/125810391/272340725-0083f4e8-3297-4965-bd55-57bd63a98e7d.png">
> 
> I'm running Fulcrum on ubuntu Any ideas on how to solve this? Thanks in advance

Also running into this. Running electrs and bitcoind all in docker-compose using the signet network. 
The public instances respond to `address/{address}/utxo` fine. 
i.e ` curl -sSL "https://mempool.space/signet/api/address/tb1qxm3whcc0lw5fy5j6fk8cuaqlrjl873jxqrkt5z/utxo"`

**Comment by junderw** [comment]
> Running electrs and bitcoind all in docker-compose using the signet network.

How is your nginx.conf configured for the nginx container? Or do you have some other proxy setup?

mempool/backend doesn't have these endpoints, so you need a proxy that stands between the client and mempool/backend to divert certain paths to the electrs instance.

**Comment by 0xBEEFCAF3** [comment]
> > Running electrs and bitcoind all in docker-compose using the signet network.
> 
> How is your nginx.conf configured for the nginx container? Or do you have some other proxy setup?
> 
> mempool/backend doesn't have these endpoints, so you need a proxy that stands between the client and mempool/backend to divert certain paths to the electrs instance.

Ah I didn't know about this. I should be able to set up nginx for this. Thanks

How do you feel about having mempool backend act as this proxy to electrs? My understanding is that it already proxies other requests. I can help add this. Lmk
