### ISSUE TITLE
Add new panel "Mining info"

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1037]
### Description

add extra information panel(s)

### Problem to be solved

not a problem

### Proposed solution

Just like there now is a `difficulty adjustment` panel, i suggest a new panel (maybe ideas are needed for a second one to keep it symmetrical)
name: mining info, data to put there would be the network's hashrate, mempool size in MvB or MB, bitcoins to be mined, total unmined bitcoins, amount of blocks to the next halving (maybe 2 panels can be filled)

**Comment by antonilol** [comment]
should be labeled...

**Comment by wiz** [comment]
Mining Dashboard project is detailed in #1077 #1050 #1049 #1048 #1047
