### ISSUE TITLE
Implement SSR using Angular Universal, enable reverse-proxy cache in nginx configuration

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#104]
https://blog.angular-university.io/angular-universal/

https://medium.com/platformer-blog/enabling-server-side-rendering-on-an-existing-angular-application-with-angular-universal-5fdf7549b928

**Comment by softsimon** [comment]
- [ ] Go through all pages and make sure they are pre-renderable (fix document, window, setTimeout etc)
- [ ] Make unique URLs for tabs and paginations
- [ ] Support the "generated config" for the correct network dropdown menu
- [ ] Investigate if it's possible to pre-render the chartist graph on the backend
- [ ] Add TransferHttpCacheModule and enable transfer of data to remove the "flickering" and double loading
- [ ] Make API url's configurable on the frontend AND server.ts universal backend
