### ISSUE TITLE
Mining Dashboard (Phase 1): Backend support for block and pool data

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1047]
### Needed new database tables

1. Create a new table for block data in the database with the following fields:
Block height
Block size
Block weight
Tx count
Fees
Coinbase raw
Fee-span (Array)
Median fee
Difficulty
Pool identification ID (connected to a separate pools with pool id+name)

2. Create a new `pools` table that automatically stores the individual unique mining pools

### Blocks and mining pool APIs
1. Latest blocks and load more blocks API similar to current `/api/blocks/` API
2. API for block mining info `/api/v1/block/:height/pool`
3. Include mining pool info in WebSocket blocks info
4. Mining pool icons API

**Comment by nymkappa** [comment]
We already have most of those info in the existing `blocks` table. It would be nice to avoid duplication. Already existing data:
* Block height
* Block size
* Block weight
* Tx count
* Fees
* Median fee

Let's simply add the missing data we need?
* Coinbase raw
* Fee-span (Array)
* Difficulty
* Pool identification ID (connected to a separate pools with pool id+name)

Doing so we can also show block mining info [the block view](https://mempool.space/block/000000000000000000044768c2dfdb701e4ae41f4c1deab6b49e1f819927a78b) and also this will allow working on the following #882 #124 as well? Right now it seems we use Esplora to fetch the block details on demand.

**Comment by softsimon** [comment]
Here is a start
```

  private static currentVersion = 2;



if (version < 2) {
      queries.push(`DROP TABLE IF EXISTS blocks;`);

      queries.push(`CREATE TABLE blocks (
        height int(11) unsigned NOT NULL,
        hash varchar(65) NOT NULL,
        size int(11) unsigned NOT NULL,
        weight int(11) unsigned NOT NULL,
        timestamp int(11) unsigned NOT NULL,
        fee_span text NOT NULL,
        tx_count int(11) unsigned NOT NULL,
        fees double unsigned NOT NULL,
        median_fee double unsigned NOT NULL,
        difficulty bigint(20) unsigned NOT NULL,
        coinbase varchar(255) NOT NULL,
        pool_id int(11) NOT NULL,
        PRIMARY KEY (height),
        INDEX (pool_id)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8;`);

      queries.push(`CREATE TABLE pools (
        id int(11) NOT NULL AUTO_INCREMENT,
        name varchar(50) NOT NULL,
        url varchar(255) NOT NULL,
        PRIMARY KEY (id)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8;`);
    }
```

**Comment by nymkappa** [comment]
> coinbase varchar(255) NOT NULL
Should not this be a `text` instead? If you want to store the **raw** tx a varchar(255) won't be able to accommodate that.

**Comment by softsimon** [comment]
Closed in
https://github.com/mempool/mempool/pull/1162
https://github.com/mempool/mempool/pull/1235
https://github.com/mempool/mempool/pull/1233
