### ISSUE TITLE
make bitcoin assembly script (asm) resemble the output of `bitcoin-cli decodescript`

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1061]
right now bitcoin scripts in mempool use opcodes like `OP_PUSHNUM_2` or `OP_PUSHBYTES_75`

changes:
 - `OP_PUSHNUM_n` -> `OP_n`
 - remove `OP_PUSHBYTES_n`
 - display stack elements with <=4 bytes as little endian numbers
 - display errors as `[error]`

mempool:
![image](https://user-images.githubusercontent.com/49868160/147755120-84a532b4-a554-4136-bf13-1734497e923b.png)
`bitcoin-cli`:
```
$ bitcoin-cli -testnet decodescript 03ad8e20000438adcd6104421a4e110c314fcb6000000000000000000a636b706f6f6c0e2f6d696e65642062792072736b2f
{
  "asm": "2133677 0 1640869176 290331202 314fcb600000000000000000 636b706f6f6c0e2f6d69 OP_2DUP OP_VERIF OP_NOTIF [error]",
  ...
}
```
([tx](https://mempool.space/testnet/tx/801979482c5221a4542b5bee469d8910fdf36cfd5c05a95460c6d7f67a0ce534))

**Comment by softsimon** [comment]
Our script outputs are the way they are due to how Rust Bitcoin displays them https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/blockdata/opcodes.rs

`blockstream/electrs`, our main backend uses `rust-bitcoin`.

**Comment by antonilol** [comment]
did the opposite in #1502, so closing this
