### ISSUE TITLE
scroll click (open in new tab) mempool btc testnet from mainnet or signet

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1073]
### Description

when i scroll click on testnet from mempool.space nothing happens, but when i do exactly the same from liquid.network btc testnet mempool opens in a new tab (expected behaviour)
### Steps to reproduce
go to mempool.space and scroll click the testnet option in the networks dropdown
![image](https://user-images.githubusercontent.com/49868160/147829366-437f6d39-61b5-483e-9a6d-7d8666252c16.png)
from mempool.space this doesnt work, from liquid.network it does

### Expected behaviour
open in new tab

### Actual behaviour
nothing

**Comment by wiz** [comment]
I hink this is because the <a href> is not set properly, i.e. the URL is supposed to be visible in the status bar when you mouseover the link, but it's not

**Comment by antonilol** [comment]
the problem here is the first 3 are `<button>`s, the last 3 are `<a>`s.
when right clicking an `<a>`, my browser gives a menu which has a button open in new tab, but for the `<button>` the browser can't know that it is a link

![image](https://user-images.githubusercontent.com/49868160/149949353-0d6aa70e-9872-4d33-be5d-ddd32dfb4fed.png)
