### ISSUE TITLE
number of unconfirmed TXs doesn't match with number in mempool block

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1076]
### Description

title
#### Version
v2.3.0-dev [d1d74ebf]

### Steps to reproduce

can't reproduce reliably.
go to mempool.space (preferable testnet, it doesn't have that much transactions)
watch the number under 'Unconfirmed transactions' and the number in the mempool block
### Expected behaviour
numbers are the same

### Actual behaviour

they are different, but not less pooled TXs than unconfirmed (i mean it can be that the number in the block is lower because maybe TX are not pooled yet)
### Screenshots

![image](https://user-images.githubusercontent.com/49868160/147887757-0ecfb031-70b0-42fd-81ec-073ab5801cd7.png)

**Comment by wiz** [comment]
Well yes, the numbers could be off by a few due to the various race conditions internally between backends and the timings of how your browser connects websockets etc.
