### ISSUE TITLE
Use gettxout to flag transaction outputs as spent/unspent

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1088]
Use the `gettxout` API https://developer.bitcoin.org/reference/rpc/gettxout.html to flag transaction outputs as spent/unspent.

Currently we only display grey arrows due to the missing UTXO API.
Although it's not possible to know the TXID spending transaction, we can at least display red/green if they are spent or unspent.

<img width="200" alt="Screen Shot 2022-01-05 at 15 54 29" src="https://user-images.githubusercontent.com/8561090/148213639-60169616-d716-47d6-ae13-a7eb431f8af4.png">

**Comment by antonilol** [comment]
maybe it is possible by querying transactions by the output address and finding the one that spends it
