### ISSUE TITLE
empty witness stack elements are not displayed

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1089]
### Description

in bitcoin witness scripts a `0` has to be encoded as `00` (meaning 0 bytes follow) because of minimal encoding of data
(a `1` is encoded as `0101`, `255` as `02ff00`)

#### Version

mempool.space v2.3.0-dev [d1d74ebf]

### Steps to reproduce

look at then witness of

- https://mempool.space/testnet/tx/2f028410cb3083866fd553b1a3b9b5e8ca260c930d9eac07d3d07f18a6083217
- https://mempool.space/testnet/tx/996f8c3899dec3a1d3b0087830c5ecd6579e252584dc3255104ad24fdd3248a8

and compare it with `bitcoin-cli -testnet decoderawtransaction <hex>`

the first one has data, empty, data, empty, 2x data
the second one has 3x data, 2x empty, data
in mempool it looks like 4x data for both

#### Additional info

i made a `m` of `n` multisig without using `OP_CHECKMULTISIG{,VERIFY}`

i made a 3 of 5 multisig and spent it 2 times. once with keys 1 3 5 and once with keys 3 4 5. because of the way it works (5 `OP_CHECKSIG`s) i have to add an empty witness element instead of a signature for every key i did not sign it with.
so the witness looks like
sig5, empty, sig3, empty, sig1, witnessscript
and
sig5, sig4, sig3, empty, empty, witnessscript

**Comment by antonilol** [comment]
no `bug` label?

**Comment by antonilol** [comment]
idea: add `<` and `>` around witness stack elements
empty stack elements are visible as empty: `<>`
maybe make them grayish to not stick out above the data itself

example: (first input of c075e176959c807f50d053de9bba269c0920c3156918078f97d123316e54bfd2 with a little `F12`)
![image](https://user-images.githubusercontent.com/49868160/162048939-ea34ddde-8845-4476-a13e-2668633f902c.png)

**Comment by mmilata** [comment]
Another example is https://mempool.space/tx/73be398c4bdc43709db7398106609eea2a7841aaf3a4fa2000dc18184faa2a7e which has 500003 witness elements but only shows the 2 non-empty.

Btw I like the idea with `<` `>` separators, just spaces are sometimes hard to spot.

**Comment by vostrnad** [comment]
Blockstream Explorer just uses `<empty>` for empty witness elements which I think looks much nicer than wrapping every element in `<` and `>` and having the empty element be `<>`.

https://blockstream.info/testnet/tx/2f028410cb3083866fd553b1a3b9b5e8ca260c930d9eac07d3d07f18a6083217?expand
