### ISSUE TITLE
can't scroll when mouse on graph

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1090]
### Description

scrolling with my mouse when my pointer is on a graph doesn't result in the page being scrolled

#### Version

mempool.space v2.3.0-dev [d1d74ebf]

### Steps to reproduce

put your mouse on a graph (e.g. mempool size, with all the colors) and scroll

### Expected behaviour

the page gets scrolled

### Actual behaviour

nothing

#### Device or machine

archlinux 5.15.12
chromium

**Comment by softsimon** [comment]
This happens now due to the mempool graph captures the scrolling as it's being used for zooming in and out.

**Comment by antonilol** [comment]
but it doesn't zoom in or out

**Comment by nymkappa** [comment]
> but it doesn't zoom in or out
> 
> EDIT: oh wait you mean being used as in it's still in development?

It's already live. If you scroll on the chart, it will zoom in and out.
I think we can tweak that UX. I agree it's annoying to have to mouse the cursor on the side to be able to scroll, specially if you use a touchpad.

**Comment by antonilol** [comment]
> It's already live. If you scroll on the chart, it will zoom in and out.

scrolling on the graphs does nothing on mempool.space and mempool.ninja
am i doing something wrong here?

**Comment by nymkappa** [comment]
> > It's already live. If you scroll on the chart, it will zoom in and out.
> 
> scrolling on the graphs does nothing on mempool.space and mempool.ninja am i doing something wrong here?

What browser are you using?

**Comment by nymkappa** [comment]
> > It's already live. If you scroll on the chart, it will zoom in and out.
> 
> scrolling on the graphs does nothing on mempool.space and mempool.ninja am i doing something wrong here?

Okay I think I understand the missing part in your OP. You are referring to the main page right? https://mempool.space/
If you try to scroll in a chart on https://mempool.space/graphs it will zoom in/out.

I will fix the main page scrolling issue! Thanks for reporting.
