### ISSUE TITLE
multisig badge shows up even if not unlocked with multisig (special multisig configuration) + ideas about script detection / labeling P2SH and P2WSH

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1091]
i made a 3 of 4 multisig that allows spending with a master key or a multisig configuration (`1 or (3 of 4)`)

when spending from this address with the master key the multisig badge (![image](https://user-images.githubusercontent.com/49868160/148256860-c228842b-a341-411e-a62e-f8c2200c013a.png)) shows up

TXs:
unlocked with multisig: https://mempool.space/testnet/tx/a991d5485bece97b4f724508638e354e97cc97ea22228ca7bcd4d68c31bc6a1d
unlocked with master key: https://mempool.space/testnet/tx/f124530c94e94a234c4610940599189179a7bb05dc3e1bb62297e5bb436c17c6 (note that the `0` for the `OP_IF` is not visible due to https://github.com/mempool/mempool/issues/1089)

**Comment by antonilol** [comment]
made this multisig with https://github.com/antonilol/btc_stuff/blob/master/p2wsh_multisig_masterkey.js

**Comment by antonilol** [comment]
`(masterKey + 2 of 8) or (7 of 8)`: https://mempool.space/testnet/tx/24f3b4142af1efec9e59e7d4dc53663478c8ee23f2245b071655bbb2327e644e and https://mempool.space/testnet/tx/68f6c4b5f453016b624af619c37d0d6360b47bf7ece16916fd77f6ad870aa698

![image](https://user-images.githubusercontent.com/49868160/148564004-65af6e73-d6e0-476d-86dc-586febecb210.png)

**Comment by antonilol** [comment]
just a normal 1 of 1 multisig ([tx](https://mempool.space/testnet/tx/fbd7630b764dfee14ec8d4809ea231f69e040d45bb4744715b9267e61caf3f61)) with useless `OP`s in front of it and no multisig badge
![image](https://user-images.githubusercontent.com/49868160/148565258-a13003f2-ed78-4f80-afd3-e441f651c774.png)

**Comment by antonilol** [comment]
ok one more (1 of 1) https://mempool.space/testnet/tx/606c14cee2630f0bc3bc755262a9a7c8a33324605ff3efd26ff07f4215ecaa24

**Comment by antonilol** [comment]
last one for today `:)` (again a 1 of 1)
![image](https://user-images.githubusercontent.com/49868160/148568159-f6bf9db8-8d05-42b8-905f-73e6d014c188.png)
https://mempool.space/testnet/tx/1fd204fb642f27a440cac0cb51085d8fa90067b09e7f286055322c5b20037d5a

**Comment by ziggie1984** [comment]
have to agree, was just searching for Lightning Penalty Transactions, and found a penalty transaction which was clearly spend by the revocation path, but is listed as multisig: 

https://mempool.space/tx/bc0279a4b816b1ee2d6a2550c20e760ecb4f9da819fd6db732b064aba204bfa9

**Comment by softsimon** [comment]
> have to agree, was just searching for Lightning Penalty Transactions, and found a penalty transaction which was clearly spend by the revocation path, but is listed as multisig:
> 
> https://mempool.space/tx/bc0279a4b816b1ee2d6a2550c20e760ecb4f9da819fd6db732b064aba204bfa9

These are all helpful examples. Any help on how to identify certain types of script to label them is appreciated.

**Comment by antonilol** [comment]
> have to agree, was just searching for Lightning Penalty Transactions, and found a penalty transaction which was clearly spend by the revocation path, but is listed as multisig:
> 
> https://mempool.space/tx/bc0279a4b816b1ee2d6a2550c20e760ecb4f9da819fd6db732b064aba204bfa9

The lightning txs here do not have a tag, the multisig badge there is under the last 2 P2WSHs and these 2 have an `OP_CHECKMULTISIG`. (And a very complicated script wow)

**Comment by antonilol** [comment]
> Any help on how to identify certain types of script to label them is appreciated.

ok, the lightning channel close from **one** of the parties:

```
OP_IF
  <pubkey1>
OP_ELSE
  <blocks>
  OP_CSV
  OP_DROP
  <pubkey2>
OP_ENDIF
OP_CHECKSIG
```

`pubkey1` is the revocation key, you can see that it is used because the top stack element is a `0x01` the enter the first `OP_IF` branch
`pubkey2` is the key of the one who closed the channel, he can redeem the funds when this output has `blocks` confirmations.
if this transaction was followed by a new transaction in lightning, the revocation keys must be exchanged by both parties, so if one of the two tries to steal funds by using an old transaction, the penalty is that the other can redeem his own funds (of course), but also the funds of the other with the revocation key (this happened in https://mempool.space/tx/bc0279a4b816b1ee2d6a2550c20e760ecb4f9da819fd6db732b064aba204bfa9)

if this was the last lightning TX (meaning the one with `pubkey2` redeems it after `blocks` confirmations), the top stack element would be `0x` (yes, empty) but it is not displayed by mempool (https://github.com/mempool/mempool/issues/1089)

**Comment by antonilol** [comment]
a pubkey always matches
`04<64 bytes>` or `(02|03)<32 bytes>`
for more information just google `bitcoin compress pubkey` or something like that

**Comment by ziggie1984** [comment]
> The lightning txs here do not have a tag, the multisig badge there is under the last 2 P2WSHs and these 2 have an OP_CHECKMULTISIG. (And a very complicated script wow)

yes it has a multisig flag, but its not spend by the multisig path, because the HTLC is "Revoked" 

I would label all Scripts with more than 1 PATH as Non-Standard to avoid confusion.

**Comment by antonilol** [comment]
You mean the last 2 P2WSHs are also lightning?

**Comment by ziggie1984** [comment]
yes these are HTLCs

**Comment by ziggie1984** [comment]
What is your opinion to go for NON-STANDARD for all scripts which have multiples paths, or should we dive deep and actually investigate the SigScript and label them explicitly. This would mean a lot of more cases, but it would be cool that we could highlight the OP_Codes which were actually executed ?

**Comment by antonilol** [comment]
I would say label script types explicitly.
idea: add a function that detects scripts by peeling off opcodes from the top. A multisig detection would work as follows:
check if the top is OP CHECKMULTISIG, and pop it
pop a number, save it as `n`
pop `n` public keys
pop a number, save it as `m`
`return m + ' of ' + n + ' multisig'`
e.g. if a public key has to popped but it doesnt match the public key regex, try the next script type
And such checks for every known type of script, this way a new type can easily added
