### ISSUE TITLE
block fee range says 2 - 350 but block contains 1 sat/vB TXs

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1108]
https://mempool.space/block/000000000000000000007198b0f3f46e4b918ca1cc4074165d2b129568f26d6f

![image](https://user-images.githubusercontent.com/49868160/148678806-3f0b14da-7bba-4b86-a58c-46e1a3fca648.png)

![image](https://user-images.githubusercontent.com/49868160/148678816-a8cc430d-9e7c-4961-a629-989237072255.png)
^ 1 sat/vB

**Comment by softsimon** [comment]
It's intended. See similar issue here https://github.com/mempool/mempool/issues/101
