### ISSUE TITLE
show fee rate of 0 sat/vB TXs

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1115]
### Description

https://mempool.space/testnet/block/000000001efffa5b45762dd0be070a9fa949df27344f2969828e038a5c3f595b

the second TX has 0 sat/vB fee rate, it is not displayed unlike the third one which has 134 sat/vB fee rate

i think it is not showing because showing fee rate for coinbase TXs is useless, but coinbase TXs are not the only TXs with 0 sat/vB.

non coinbase mainnet example (F2Pool paying out there miners in their own blocks, 0 sat/vB):

[it](https://mempool.space/tx/11fa91a1a0a17373d3217f55a6a98ee637a58702c12251975532a7423358448c) shows after the coinbase of [block 717977](https://mempool.space/block/0000000000000000000ad0561808f0953e13434b614e53593e9142713807cee0)

0 sat/vB TXs now are sorted at the top (above the highest fee TXs) probably to get the coinbase at the top

### Screenshots

![image](https://user-images.githubusercontent.com/49868160/148830309-53686c9f-5097-4857-824e-ceb90973b019.png)

**Comment by softsimon** [comment]
The transactions are ordered the way they are included in the block by the miner.

This is a `blockstream/electrs` decision and there is no sorting.

**Comment by antonilol** [comment]
> The transactions are ordered the way they are included in the block by the miner.

oh didnt know it

**Comment by wiz** [comment]
> This is a blockstream/electrs decision and there is no sorting.

The order of transactions is decided by the miner, not our backend, and not specific to blockstream/electrs - any backend will return the data exactly how it is ordered in the blockchain

**Comment by antonilol** [comment]
that was only a part of this issues, the other (still unsolved) part is the fee is not displayed on 0 sat/vB non coinbase TXs (examples in post)
