### ISSUE TITLE
genesis block doesn't load on regtest

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1128]
### Description

when clicking on the genesis block in regtest mempool is stuck loading and the log says
`DEBUG: <regtest> getBlockTransactions error: Block not found`

![image](https://user-images.githubusercontent.com/49868160/149115506-6c220824-683d-4d97-8ee9-adffbad501be.png)

https://github.com/mempool/mempool/discussions/1023#discussioncomment-1953509

**Comment by softsimon** [comment]
We don't support Regtest.

**Comment by antonilol** [comment]
It does work tho
