### ISSUE TITLE
Add current amount of L-BTC circulation to Liquid network dashboard

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#113]
Currently we have an empty space on the Liquid dashboard where "difficulty adjustment" would be if Liquid had that. To fill this space, how about we add "L-BTC in circulation" statistic from the L-BTC asset https://mempool.space/liquid/asset/6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d

<img width="1168" alt="Screenshot 2020-09-27 at 18 09 59" src="https://user-images.githubusercontent.com/232186/94363614-5a344400-00fe-11eb-965f-7da041baef10.png">

**Comment by softsimon** [comment]
Fixed in https://github.com/mempool/mempool/pull/810
