### ISSUE TITLE
Liquid: Dashboard redirects while in Tor Browser to mempool onion address.

### ISSUE THREAD

**Issue by AUAggy** [mempool/mempool#1146]
### Description
When you go to https://mempool.space in a Tor browser and select Liquid network from the drop down, you are redirected to https://liquid.network. However, before the page is able to completely load the address bar is redirected to the mempool.space onion address, http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion, so you never actually get to view the Liquid dashboard.

#### Version
Tor Browser: 11.0.4
Mempool: v2.3.0-dev [ace5da94]

**Comment by wiz** [comment]
Sorry, the onion redirect should be fixed now
