### ISSUE TITLE
Title is not updated when navigating to home page

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#115]
### Steps to reproduce

1) Load an Address or Transaction page
2) Click on upper left mempool logo to navigate to home page, or change network from pull-down

### Expected behaviour

After step 1, page title is set to "Address: ..." or "Transaction: ..."
After step 2, page title is set to "mempool - Bitcoin Explorer"

### Actual behaviour

After step 2, page title does not get set to "mempool - [network] Explorer"

### Screenshots

<img width="564" alt="Screen Shot 2020-09-27 at 22 33 12" src="https://user-images.githubusercontent.com/232186/94366203-72fa2500-0111-11eb-8f03-a4e1616f90a7.png">

**Comment by softsimon** [comment]
Fixed in b95efca29d
