### ISSUE TITLE
genesis coinbase looks spent (romanz/electrs)

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1159]
### Description

because gettxout for the genesis coinbase returns nothing it looks like it was spent 😳

**Comment by softsimon** [comment]
I can't reproduce this. You need to be more specific.

**Comment by antonilol** [comment]
The pr only fixes the second point in this issue

**Comment by antonilol** [comment]
> I can't reproduce this.

yeah i forgot to update the frontend. after updating there is no link anymore there
