### ISSUE TITLE
Input/Output Address Abbreviation

### ISSUE THREAD

**Issue by 6102bitcoin** [mempool/mempool#116]
Currently addresses are not displayed in full (bc1q...abc). 

Sometimes its useful to search a page for an address, and this stops that functionality. 

Could the full address be shown rather than breaking and adding ... ?

**Comment by softsimon** [comment]
Currently it's difficult to display the whole without breaking to another row.. which is the reason it's cut off. 

A different design take would be required.

**Comment by softsimon** [comment]
Addresses can be very long... for example
`bc1q9kc30ur8hr0806pkdculcdh2s3aemhm6ummgg6uj7l4y62vnd2fqddrd30`

They need to be cut off to fit with the current design. I'm closing this issue until there is some concrete suggestion of how the design could be adapted to display full addresses. Most block explorers cut off the addresses and transaction IDs as well.
