### ISSUE TITLE
[frontend] caching issue with outspends

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1164]
reliably reproducible, see the video

[simplescreenrecorder-2022-01-19_15.34.44.mkv.zip](https://github.com/mempool/mempool/files/7897926/simplescreenrecorder-2022-01-19_15.34.44.mkv.zip)
(github doesn't let me upload videos directly but does allow zips)

**Comment by antonilol** [comment]
basically the outspends of the previous block are cached (i think) and when you press the back button on your browser it uses the old outspends with new TXs

**Comment by wiz** [comment]
@softsimon AFAIK the API queries for outspends always have the TXID in them so I don't see how this could be a caching issue?

**Comment by softsimon** [comment]
> @softsimon AFAIK the API queries for outspends always have the TXID in them so I don't see how this could be a caching issue?

You're right .. Every request are unique per TX.
In that case I don't know what the bug is here.. without trying to reproduce the issue myself.
