### ISSUE TITLE
BTC pricing data through local node API

### ISSUE THREAD

**Issue by BTCfan86** [mempool/mempool#1190]
Hello,

I am hoping to access BTC pricing and market cap data through the mempool API on my local node.  The node is running on Umbrel with the mempool app.  I can see that the node stores BTC/USD conversion rates somewhere, because the mempool homepage in my browser includes figures in USD.  Is there a way to access BTC/USD pricing data through an API URL?  I have been able to access txid and other data from the mempool app on my node via an API URL, so I know some API calls work.  Any help is much appreciated.  Thanks.

**Comment by wiz** [comment]
The mempool backend fetches price data from my Bisq price API server at https://price.bisq.wiz.biz/getAllMarketPrices

For more information see https://bisq.wiki/Bisq_Price_Indices

While the Bisq price server is not currently available as an Umbrel app, I suppose we could expose the prices together with the other mempool backend APIs, but it would just be proxying the data from my backend... need to consider that a bit. In the meantime you can just hit my server API.

**Comment by BTCfan86** [comment]
I appreciate the quick reply!  Thanks for your consideration on integrating the Bisq API data, and also for the offer to access the pricing data off your Bisq server.
