### ISSUE TITLE
Full node API call issue for addresses

### ISSUE THREAD

**Issue by BTCfan86** [mempool/mempool#1204]
Hello,

I have been using the mempool app on my full node running on Umbrel.  When I request API data from the mempool app for BTC addresses (http://local IP:port/api/address/address, with a BTC address at the end), I get mixed results.  Sometimes the app returns the address data quickly, sometimes it returns the data slowly, and sometimes the requests time out.  I have tried to access the address data through mempool using my browser and the API URL and scripts I've written in python.  I have not had similar issues getting block or txid data from my node, just address data.  I'm not sure what is going on.  Any help would be much appreciated.  The mempool app is very helpful otherwise.  Thanks!

**Comment by wiz** [comment]
This sounds like you're simply hitting the hardware limitations of your Raspberry Pi. You need to run our "production" setup for your use case, which can handle heavier address queries.

**Comment by BTCfan86** [comment]
Thank you very much for your help.  I reviewed the mempool/production github page, and the suggested hardware seems pretty high-cost (20C CPU, 64G RAM)... Since I'm doing this for my own purposes and not as a business or corporate venture, I'm hoping to complete these kinds of API calls without spending quite so much money.  Is there any middle ground hardware between my Pi4 and the 20C CPU production server that could accomplish these API pulls?  Maybe running Umbrel / mempool app on a more powerful home PC instead of the Pi4 would be enough?  Again, thanks for your guidance on this.
