### ISSUE TITLE
API for BSQ Tx query seems to be missing BSQ info

### ISSUE THREAD

**Issue by jmacxx** [mempool/mempool#1231]
Trying to get metadata from a BSQ transaction, Problem is the Tx API query does not provide any BSQ info.

BSQ Tx query results are identical to BTC query, i.e.
https://mempool.space/api/tx/1f4f91d1b321c06066b5f64ce9d0bef2540c3b6edc0240b18d88555ff9910727
gives same result as
https://mempool.space/bisq/api/tx/1f4f91d1b321c06066b5f64ce9d0bef2540c3b6edc0240b18d88555ff9910727

It would be useful if the BSQ Tx query provided information about the BSQ transaction.
Type (e.g. Proof of Burn), inputs and outputs as BSQ addresses.  Burnt amount if applicable.

We're [using the mempool API for Bisq2](https://github.com/bisq-network/bisq2/issues/68).  Having to get around the apparent problem by doing a second query, like:
https://bisq.mempool.emzy.de/api/address/Bbc1qpjjtrpzygawc86kczkhytejtepahzqadppvyyp
(where the address is pulled from the Tx and prepending B to it).  In order to find this, which could have been in the tx:

![image](https://user-images.githubusercontent.com/47253594/152900467-f424927c-af75-411d-b8e7-1873138a7649.png)

**Comment by wiz** [comment]
You need to query bisq.markets, i.e.
https://bisq.markets/bisq/api/tx/05ce5a423e2c5bfd823a84bc8d9afe2dad327a8fd119bf466703047e90581e10

**Comment by jmacxx** [comment]
Wiz, bisq.markets/bisq/api produces exactly the same results.  
The tx query should show results about the BSQ transaction.
Please could you or @softsimon reopen and look into the issue?

**Comment by jmacxx** [comment]
Sorry, you're right.  I screwed up with the previous comment.    Thanks Wiz.
