### ISSUE TITLE
ERR SSL WRONG VERSION NUMBER

### ISSUE THREAD

**Issue by Silarous** [mempool/mempool#1241]
Currently attempting to install mempool on my Ubuntu machine which is hosting a local Bitcoind and Fulcrum server.  I'm at the step for starting the backend and entered the command "npm run start".  It appears to start and is fetching transactions but it is displaying this message repeatedly

Electrum error: {"library":"SSL routines","reason":"wrong version number","code":"ERR_SSL_WRONG_VERSION_NUMBER"}

![Screenshot from 2022-02-10 11-19-12](https://user-images.githubusercontent.com/56011055/153461355-ddbc122d-55c4-4d76-9515-0971eca6ff45.png)

**Comment by wiz** [comment]
So don't use SSL then?

**Comment by Silarous** [comment]
How would I go about not using SSL?  I'm just trying to follow the install guide as written and from what I have seen, it does not mention not using SSL .  I'm by no means an expert at this.  Novice at best.

**Comment by wiz** [comment]
If you're just connecting over localhost then you don't need SSL, but I don't know how to disable SSL in the fulcrum configuration so I can't help you with that. We currently recommend electrs/romanz and nobody has reported any issues using that, with SSL or without SSL.
