### ISSUE TITLE
Highlight the receive address when looking at an address

### ISSUE THREAD

**Issue by Transisto** [mempool/mempool#1294]
People might want to check the amount they get from a receive transaction.

![image](https://user-images.githubusercontent.com/388716/155891324-f573ffa0-6734-4f5b-9e6c-71bc08215175.png)

**Comment by katesalazar** [comment]
What's the scope of this? As this isn't necessary
for txs with 1, 2, 3, maybe even 4 txos.

**Comment by antonilol** [comment]
already requested 2 months ago #1074

**Comment by Transisto** [comment]
@katesalazar Why would you have people read and compare addresses even if there's only 2 output?
