### ISSUE TITLE
GET Address Transactions :last_seen_txid not implemented/documented

### ISSUE THREAD

**Issue by gitithubfor** [mempool/mempool#1295]
### Description

As documented here https://github.com/mempool/mempool/blob/master/frontend/src/app/components/docs/api-docs-data.ts#L846, there should be a way to get all results using paging by providing the **:last_seen_txid** parameter. But I couldn't find an example or get it work.

#### Version

master

### Steps to reproduce

curl https://mempool.space/api/address/1HB5XMLmzFVj8ALj6mfBsbifRoD4miY36v/txs

**Comment by softsimon** [comment]
The endpoint to fetch "more" TXIDs goes like this:

After `https://mempool.space/api/address/1HB5XMLmzFVj8ALj6mfBsbifRoD4miY36v/txs` the last TXID you use to request more like this:

`https://mempool.space/api/address/1HB5XMLmzFVj8ALj6mfBsbifRoD4miY36v/txs/chain/84a98b041cd6b4f5089b787aaf952790ddbc0fb8478651fcb858fd6ab1bc72fd`

**Comment by wiz** [comment]
@hunicus maybe consider improving documentation based on this support request
