### ISSUE TITLE
Upgrade Liquid Testnet to support Taproot

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1299]
Example Taproot transactions from Matrix Swap

https://liquid.network/testnet/tx/4d85b480122fc6b4d64e9c2409b06db51b25d5b9df14b07496f29d20d5dda224
https://liquid.network/testnet/tx/912d9072b74b62f1ee3c8d6e48d3a6f30ca33b11560372e3c5857a1d3035353d

**Comment by wiz** [comment]
ok fixed
