### ISSUE TITLE
Server sponsor profile photos from mempool backend instead of hotlinking to Twitter

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#133]
Not only for privacy, but if you block third party images then the sponsors won't load

<img width="337" alt="Screen Shot 2020-10-12 at 14 58 09" src="https://user-images.githubusercontent.com/232186/95710308-5d513780-0c9b-11eb-84c8-e071b2203664.png">

**Comment by softsimon** [comment]
Notes:

- Patch the DB with the 2 new rows
- On first run, the database posts for the donations will be auto-migrated with the new downloaded and stored profile photos
- Still compatible with people running old frontend
