### ISSUE TITLE
Privacy concerns with checking BTC Price.

### ISSUE THREAD

**Issue by visskiss** [mempool/mempool#1365]
### Description

Checking of the BTC Price for this project isn't really critical, and should be optional, especially given privacy concerns. The ability to remove BTC Price checks and instead display relevant data in native units (BTC) should be added.

### Problem to be solved

Requesting BTC Price requires an external API call which will leak information about the node. It is possible to use the tor option for fetching external data, but another option would be to add a privacy configuration option.

### Proposed solution

Add a configuration option to disable all external calls.

**Comment by wiz** [comment]
Yes this is currently possible by setting the price server requests to be routed via Tor to the onion hostname, or if you want to disable it completely just set it to an invalid URL like "localhost"

**Comment by wiz** [comment]
You can verify the current configuration by checking the log print on startup, it will indicate clearnet or Tor being used, and what hostname it is fetching from. If you set an invalid hostname like "localhost" then it will fail and the fiat prices will simply appear as zero but all other functionality should work.

**Comment by visskiss** [comment]
Thanks for the reply. Using journalctl, I don't see any mention of the host or Tor use. Is there another log besides syslog? Is there a log level setting? I see `"STDOUT_LOG_MIN_PRIORITY": "debug"` in the config file but I don't see a list of possibilities anywhere. Is there documentation for the config file?  Thanks

**Comment by visskiss** [comment]
I realize that none of the above config is available in the latest release.  Will return when the next release happens. Thanks

**Comment by wiz** [comment]
Yes, the Tor proxy feature is currently only available in master branch which is still under development - probably a few weeks away until we can ship that.
