### ISSUE TITLE
Refactor the handling of medianFee and feeRange

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1385]
Currently we calculate medianFee and feeRange locally based on the transactions in the block, when the new blocks comes in. But we no longer need to load fetch transactions on new blocks coming in to calculate these values.

Migrate fully to the blockStats RPC API way of getting this information.

**Comment by nymkappa** [comment]
AFAIK it has been fixed already, see https://github.com/mempool/mempool/blob/master/backend/src/api/blocks.ts#L120
Please confirm and close this issue if you agree 👍🏻

**Comment by softsimon** [comment]
Yes, this has been fixed now!
