### ISSUE TITLE
Store historical USD prices

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1389]
- [ ] Find historical USD price data API to store in the blocks table when blocks are indexed
- [ ] When new blocks comes in, store the current BTC/USD price
- [ ] When viewing an old block or a transaction. Use the stored USD price for that block to display the block reward and transferred value in USD
- [ ] Create a new graph that show the historical USD reward for all blocks.

**Comment by wiz** [comment]
Duplicate of #176
