### ISSUE TITLE
Live 3d visualization stream of mempool transactions 

### ISSUE THREAD

**Issue by metacoma** [mempool/mempool#139]
Hey folks, just checkout ;-)

https://www.twitch.tv/btc_live

![promo2-min](https://user-images.githubusercontent.com/5146707/95852363-b042f180-0d64-11eb-8ba8-f6ce04b39ef5.gif)

**Comment by softsimon** [comment]
Looks neat. Are you using the mempool.space API for the data?

Anyway this is no issue or suggestion so closing. Continue discussion on Keybase: https://keybase.io/team/mempool
