### ISSUE TITLE
Display nicer loading indicators when synchronizing mining data

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1394]
Instead of a date it should show percentage and perhaps a colorful progress bar.

This task is dependent on this parent task: https://github.com/mempool/mempool/issues/1334

**Comment by knorrium** [comment]
The missing hash rate graph should be replaced with the progress indicator:

![Screenshot from 2022-03-23 19-12-35](https://user-images.githubusercontent.com/100320/159830352-7ed04bae-6415-41c9-a319-aabf9494a90d.png)
