### ISSUE TITLE
After a difficulty adjustment estimated block times are not 10 minutes

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#1402]
Obviously after the difficulty adjusts the estimated block time is exactly 10 minutes, but a wildly off estimate is being used/displayed:

<img width="1663" alt="Screen Shot 2022-03-17 at 23 03 01" src="https://user-images.githubusercontent.com/232186/158902056-d639b12c-f0de-4c3b-a613-f6c32916a374.png">

**Comment by softsimon** [comment]
We should set it to default 10 min as long as our estimate is a dash -, which is the first 146 blocks after an adjustment
