### ISSUE TITLE
Can't see any 2000+ sat transactions in mempools

### ISSUE THREAD

**Issue by Transisto** [mempool/mempool#142]
![image](https://user-images.githubusercontent.com/388716/96930456-b97d3e00-1489-11eb-94e3-a9326cc80c89.png)

I've been watching "Next block" for about 12 block and those 2244 sat transaction are still there.

**Comment by Transisto** [comment]
maybe there's some stuck or invalid transaction in there.

**Comment by softsimon** [comment]
It's a good question what happened here. Mempool.space is a mirror of the state of _our_ Bitcoin node mempool with that 2244 sat transaction hanging around for a long, but as far as I can see, it eventually it got confirmed after all.

Invalid transactions are not accepted by the Bitcoin node, and I don't think transactions can get "stuck" like this unless miners actually don't have the transaction or chose to not include it for some reason.

**Comment by Transisto** [comment]
So basically a high fee transaction with a chain of unconfirmed parents
still show up as aimed for next block?

Jochen-hoenicke.de mempool didn't show any tx above 500sat during that many
blocks period.

**Comment by softsimon** [comment]
Ah yes. This is most likely due to the lack of CPFP support #5
