### ISSUE TITLE
Asset download should happen over socks5 if config uses that

### ISSUE THREAD

**Issue by visskiss** [mempool/mempool#1426]
### Description

mempool-config includes an option to set up a tor proxy. This is currently used to download price data. However when the external pools asset file is downloaded, the proxy setting is not used

#### Version

0bada4b07932a996dd4c9b0d3860b86109c612ec

### Expected behaviour

If config includes socks5 then it should be used for all requests

### Actual behaviour

socks5 is only used for price data

**Comment by wiz** [comment]
@visskiss could you please test this on latest master and let us know it solves your issue?
