### ISSUE TITLE
Feature Request: Show the raw input/output scripts

### ISSUE THREAD

**Issue by bubersson** [mempool/mempool#144]
It would be really useful for debugging and educational purposes to be able to see the raw input and output Script content. Even cooler would be if opcodes are clearly stated.

E.g.
```asm
OP_DUP
OP_HASH160
44513fafafafafafafafafafafafafaffafaffaf2ed5
OP_EQUALVERIFY
OP_CHECKSIG
```

**Comment by softsimon** [comment]
The only question is where to display it actually. Or more specifically where to add the button that toggles scripts. If you have any ideas!

Closing due to duplicate -> #46
