### ISSUE TITLE
SSR: Always display up to 8 mempool blocks and let the user scroll

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#148]
We should maybe leave it as it is on the TV view though since the TV screen won't usually be scrollable?

- [ ] Always render the 8 mempool blocks except on the TV view (keep the legacy style)
- [ ] When opening a transaction or block, animate the blockchain to that position to reveal the arrow
- [ ] Add a "snap to" feature so the scrollable blockchain can be centered again

**Comment by wiz** [comment]
Right, the TV view and status view don't scroll

**Comment by softsimon** [comment]
- [ ] Always render the 8 mempool blocks except on the TV view (keep the legacy style)
- [ ] When opening a transaction or block, animate the blockchain to that position to reveal the arrow
- [ ] Add a "snap to" feature so the scrollable blockchain can be centered again
