### ISSUE TITLE
Retarget estimate should be about 2 weeks, not 1 month

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1494]
<img width="597" alt="Screen Shot 2022-03-31 at 23 01 04" src="https://user-images.githubusercontent.com/8561090/161129885-22f5a5d4-89dd-4066-bf3f-eb6b07a0dd29.png">

**Comment by TomKein** [comment]
It's wrong:
const remainingTime = (remainingBlocks * timeAvg) + (now * 1000);
const estimatedRetargetDate = remainingTime + now;
You calc remainingTime as estimatedRetargetDate 
And double wrong calc estimatedRetargetDate 
It's right:
const remainingTime = remainingBlocks * timeAvg;  //in milliseconds
const estimatedRetargetDate = remainingTime + now * 1000;  //in milliseconds

**Comment by hunicus** [comment]
Seeing "~1 week" displayed right now for a remaining period of 2009 blocks / ~2 weeks.
