### ISSUE TITLE
Websocket is constantly spamming loading indicator to everyone

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1559]
This shows up even though I am just sitting at the / dashboard.

<img width="268" alt="Screen Shot 2022-04-21 at 16 16 36" src="https://user-images.githubusercontent.com/8561090/164456199-23c6db20-4af2-4493-a12c-4532f6d6b40d.png">

**Comment by nymkappa** [comment]
Related to https://github.com/mempool/mempool/issues/1334
The /block-extras has loading indicator websocket push, even tho I did not implement any loading indicator (and it's near instant anyway) so I can just remove it.
