### ISSUE TITLE
The number of transactions on this address exceeds the Electrum server limit

### ISSUE THREAD

**Issue by OliverOffing** [mempool/mempool#1603]
### Description

I'd like to be able to view transactions for addresses that have many txs, without having to use the official Mempool website.

![image](https://user-images.githubusercontent.com/84942996/166960893-b18fa087-7225-4bbc-baf2-64ce90be64e2.png)

### Problem to be solved

(I'm guessing) Lack of instructions on how to set up mempool so that it behaves like the official mempool server.

### Proposed solution

Adding instructions on how to set up mempool (et al) so that it behaves like the official mempool server.

#### Additional info

Here's one example (random address):

https://mempool.space/address/bc1qnsupj8eqya02nm8v6tmk93zslu2e2z8chlmcej

**Comment by OliverOffing** [comment]
Why `fulcrum`? It's a project focused on BCH and [this guy makes a valid comment](https://github.com/raspibolt/raspibolt/issues/894#issuecomment-1030895657):

>  [The fulcrum team] say keeping compatibility with Bitcoin Core is trivial and very important to them [but] if for some reason Bitcoin Cash changes enough to make Fulcrum not compatible with Bitcoin anymore, we could have a problem on our hands.

**Comment by wiz** [comment]
The address index backend you choose is completely up to you, and it's outside of the scope of the mempool open source project to provide one. We have detailed instructions on how to setup a "production" installation using blockstream/electrs which would do what you want.
