### ISSUE TITLE
Looked-up address gets hidden behind "Load all" button

### ISSUE THREAD

**Issue by OliverOffing** [mempool/mempool#1604]
### Description

When I'm looking up the transactions in an address, I'd like to know exactly how many Bitcoins went in our out of this address. However, it's hard to identify that information when the addresses for a transaction are displayed in a random order. Even worse is when the information I'm looking for is hidden behind the "Load all" button, in which case I can't even use the "Search in document" function of my web browser.

[Here's an example](https://mempool.space/address/1MW4maqRuqi62YiRNMaBiHT65WJJMEAvQw) (random address):

![image](https://user-images.githubusercontent.com/84942996/166962879-95868c13-cb78-4672-874d-eca7e2bbddc3.png)

### Problem to be solved

The address being looked up gets hidden behind the "Load all" button.

### Proposed solution

**For each transaction, make the address being looked up the first item in the list**.

Alternatively, or additionally, for each UI block that represents a transaction, we could add somewhere the information about how many Bitcoins did this wallet receive on each specific transaction. Example:

![image](https://user-images.githubusercontent.com/84942996/166963572-0419b6bd-4335-4d63-96e3-639445033eb4.png)

#### Additional info

Happy to open a PR if this is something you'd be open to.

**Comment by softsimon** [comment]
> I'd like to know exactly how many Bitcoins went in our out of this address

This is what the second green (or red) button next to the confirmation amount is displaying.

**Comment by OliverOffing** [comment]
That's nice thank you. I guess we could make this UI a bit more intuitive to avoid others having the same problem. Additionally, it'd be cool to be able to select the amount given that today it's inside a button and the text seems impossible to select. Anyway, my immediate problem is resolved — ­thank you.
