### ISSUE TITLE
Use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#1605]
Can you look into this to improve the scrolling performance?
https://web.dev/uses-passive-event-listeners/

**Comment by nymkappa** [comment]
The documentation mentioned
> Add a passive flag to every event listener that Lighthouse identified.

Do you have such a list of identified event listeners? I only found an occurrence of `addEventListener` on the documentation component.

**Comment by wiz** [comment]
Thanks, that might be the only one.

This bug report is simply a copy/paste from the lighthouse report which mostly contains easy to fix things that improve the site, so I guess it's a new one since I ran the test last time.
