### ISSUE TITLE
sometimes mempool wont show me the bisq donation address and give a `429 Too Many Requests`

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1631]
### Description

title, this address has around 70k txs but other address with even more txs dont have this problem

https://mempool.space/address/38bZBj5peYS3Husdz7AH3gEUiUbYRD951t

#### Version

mempool.space v2.4.0-dev [074e484c]

### Steps to reproduce

go here -> https://mempool.space/address/38bZBj5peYS3Husdz7AH3gEUiUbYRD951t

sometimes it will show a ratelimit error without spamming `F5`, i got this the first time opening this address

### Expected behaviour

no rate limit on the first request

### Screenshots

![3684ec11-cae0-4ce7-9c03-460a0b6b1527](https://user-images.githubusercontent.com/49868160/167878331-8b6d141a-27c4-4824-a22b-110170dfa991.png)

#### Device or machine

chromium

**Comment by antonilol** [comment]
just tried to list another address with a large amount of transactions and after trying to get it load (refresh every 30s until it shows up), i cant scroll all the way to the bottom for more transactions and it gives a refresh button after trying 4 times with again 429 error codes

![image](https://user-images.githubusercontent.com/49868160/168469098-f38b9ec3-7d99-48bc-985f-53ad6bfe128f.png)


![image](https://user-images.githubusercontent.com/49868160/168469020-13c5a347-831d-4e3b-bd08-6bb4a747acbc.png)

clicking this button also gives a 429 in the console

i think it tries to 'infinite scroll' but gets 429 errors from the server so fails

**Comment by wiz** [comment]
We've made some changes which should fix this. Can you please re-test and let me know if it's still an issue?

**Comment by antonilol** [comment]
works great again :)
thanks
