### ISSUE TITLE
Change from https to Axios for fetching from Github API

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1650]
@nymkappa @softsimon I don't think it is good to fetch static assets using the native 'https' module while we already use axios which is more convenient, promise native and have an ability to use proxies like tor, would you mind if I change this to axios?

_Originally posted by @ayanamidev in https://github.com/mempool/mempool/issues/1511#issuecomment-1126908118_

**Comment by wiz** [comment]
@softsimon just in case you didn't see it, he already made a PR which I've linked to this issue
