### ISSUE TITLE
Replace the "waiting for blocks" with a skeleton blockchain loader

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#168]

**Comment by wiz** [comment]
@softsimon: After @MiguelMedeiros is done with his PR for the new API docs page, maybe we can ask him to look into replacing the "waiting for blocks" with an animated loading animation of the mempool block logo?

**Comment by MiguelMedeiros** [comment]
> @softsimon: After @MiguelMedeiros is done with his PR for the new API docs page, maybe we can ask him to look into replacing the "waiting for blocks" with an animated loading animation of the mempool block logo?

Good idea!

**Comment by softsimon** [comment]
> maybe we can ask him to look into replacing the "waiting for blocks" with an animated loading animation of the mempool block logo?

This whole issue is to remove the loading spinner and replace it with a skeleton loader, not replace it with another loading spinner ....

**Comment by wiz** [comment]
ah yeah good point, the skeleton loader is best. i just hate that "waiting for blocks..." text
