### ISSUE TITLE
Date span selector misplaces on Liquid base module

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1681]
It should be more up right like on the base explorer

<img width="1329" alt="Screen Shot 2022-05-19 at 22 37 02" src="https://user-images.githubusercontent.com/8561090/169375661-07c99a15-2264-42f4-9dda-e9c7ac12fb1f.png">

**Comment by nymkappa** [comment]
No the actual bug is that we show the `Mempool` button no?
