### ISSUE TITLE
mempool size graph bug with numbers > 999

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1721]
### Description

mempool block fee graph doesnt seem to handle numbers larger than 999 sat/vB 

#### Version

mempool.space v2.4.0-dev [774cd98a]

### Steps to reproduce

wait for a transaction with fee rate > 999 sat/vB and click the mempool block

### Expected behaviour

4 digits

### Actual behaviour

3 digits

### Screenshots

![image](https://user-images.githubusercontent.com/49868160/170212091-969de706-a821-4088-ad8c-3bf015ab69af.png)

#### Device or machine

chromium linux pc

**Comment by antonilol** [comment]
other remark: this graph does not give any direct insight other than 'there is someone paying extreme fee', 20 sat/vB is maybe 1 pixel higher than 1 sat/vB

**Comment by mononaut** [comment]
Fixed by #3843
