### ISSUE TITLE
Improve the fee suggestion widget, add new "economy

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#1725]
### Problem
<img width="630" alt="Screen Shot 2022-05-25 at 19 23 08" src="https://user-images.githubusercontent.com/232186/170240976-d2bfa0c5-0628-474f-a815-c3b3aafbed4d.png">

In this type of mempool situation, people complain "low" is too high, and we also need an "economy" rate which is somewhere in between "low" and "minimum"

Move the minimum fee from the 2nd widget up to the top widget, and add a new "economy" fee rate"

### Sparrow Wallet UI for inspiration 
https://twitter.com/SparrowWallet/status/1370011461238554625?s=20&t=f81B3KfF_SlkSetuzHJHmw

**Comment by nymkappa** [comment]
Note: Duplicate of https://github.com/mempool/mempool/issues/1726
