### ISSUE TITLE
Switching from MySQL to MariaDB is potentially dangerous

### ISSUE THREAD

**Issue by Sjors** [mempool/mempool#1731]
Is there something specific about MariaDB why you're recommending it in the [README](https://github.com/mempool/mempool#3-get--configure-mysql)? 

When the user has an existing MySQL installation, the installer will basically break it without warning:

<img width="1115" alt="Schermafbeelding 2022-05-26 om 11 54 17" src="https://user-images.githubusercontent.com/10217/170468856-e03c0bec-e079-452b-ade1-62571e334f43.png">

If MariaDB is not required, then I would suggest putting a warning in the README to stick to their current MySQL installation. If it is required, then a warning would be useful. Manual migration is probably not difficult, but not a fun surprise (and afaik you have to do the database dump _before_ it uninstall mysql).

**Comment by wiz** [comment]
hey @Sjors 👋 
What OS is this dialog from? AFAIK we require MariaDB v10.5 or later, so mempool will likely not work on MySQL
As you can see here, the major Bitcoin fullnode distros like Umbrel are using official MariaDB docker images: https://github.com/getumbrel/umbrel/blob/master/apps/mempool/docker-compose.yml#L48

**Comment by wiz** [comment]
We're also in the middle of completely rewriting the README docs, so we can take your feedback into consideration
cc @hunicus

**Comment by Sjors** [comment]
Ok, that's useful to know. I'll see if I can (carefully) move over to MariaDB then.

This is on Ubuntu 22.04 running MySQL 8.0.29.

**Comment by Sjors** [comment]
(Done, though it involved a fair amount of collation pain)
