### ISSUE TITLE
rsync deletes other sites in /var/www

### ISSUE THREAD

**Issue by Sjors** [mempool/mempool#1732]
The `rsync` command in the README is not safe for servers that have other things in `/var/www`.

**Comment by wiz** [comment]
Good point, we should change it to /var/www/mempool

**Comment by Sjors** [comment]
It's also not very practical, because you probably want to build the source with a different user.

**Comment by wiz** [comment]
True, but I suppose if you're doing a manual installation and building from source, the README is more of an example in this case, and you are free to configure nginx to serve those files from wherever you'd like :)

**Comment by Sjors** [comment]
In my case I'm putting the static html in /var/www, but I have a separate `mempool` user that runs the backend and where I compile the frontend.

**Comment by hunicus** [comment]
In my draft of updated install docs, this step is taken out entirely since different people will want to do different things.

https://github.com/hunicus/mempool/tree/install-manual/frontend#2-run-the-frontend
