### ISSUE TITLE
p2tr tapscript not visible on mempool.space

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1748]
### Description

the 'P2TR Tapscript' field doesnt show up on mempool.space but does on my local hosted mempool (bitcoind)

#### Version

mempool.space v2.4.0-dev [774cd98a]

### Steps to reproduce

https://mempool.space/testnet/tx/7a58768481f63f310119a5a8b02bd94613cddd3f380a108c5134f1be6a774d0b

### Expected behaviour

mempool.space show the tapscript just like my local one

### Actual behaviour

it doesn't

### Screenshots

mempool.space:
![161579823-49c04213-8c0d-448a-a9d8-089e25111a1c](https://user-images.githubusercontent.com/49868160/170986011-513f026a-4c81-47f1-b3be-5308321f418d.png)
local hosted:
![161579925-3f60dc97-c6fb-4eca-928f-dfb282e1b75e](https://user-images.githubusercontent.com/49868160/170986051-fb2c0488-efd5-466a-b065-90f505764eb2.png)

#### Additional info

https://github.com/rust-bitcoin/rust-bitcoin/pull/944
https://github.com/Blockstream/electrs/pull/48
https://github.com/mempool/mempool/pull/1502#issuecomment-1087711742

**Comment by softsimon** [comment]
As soon as it's merged and released in the `blockstream/repo` it will be supported.

**Comment by softsimon** [comment]
Fixed in https://github.com/mempool/electrs/pull/2
