### ISSUE TITLE
Allow user to select popular fiat currencies instead of USD

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#176]
### Frontend
- [ ] Add new currency selector at bottom of home page
- [ ] Save preference with localStorage
- [ ] Get and display data from backend using user preferred fiat currency

**Comment by dorveille** [comment]
Would also love to have an environment variable to set a default fiat for the docker containers.

**Comment by wiz** [comment]
Fixed by #2901 and #3061
# :tada:
