### ISSUE TITLE
mempool block does not say 'Stack of n mempool blocks' when zoomed in and does not display the fee graph of the stack

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1775]
### Description

title and see screenshots

#### Version

v2.4.0-dev [b4beb29f]

### Steps to reproduce, expected behaviour and actual behaviour

see screenshots

### Screenshots

![2022-06-01-162038_1918x1058_scrot](https://user-images.githubusercontent.com/49868160/171427731-d815e7ef-8309-4f92-9deb-4aecaa3deb6d.png)
^ Clicking on a stack of blocks does not give this title 'Stack of n mempool blocks' and not a graph starting from 1 sat/vB

![2022-06-01-162048_1918x1058_scrot](https://user-images.githubusercontent.com/49868160/171427748-c236a2b5-4e5d-4f1e-b5dd-eacb87128102.png)
^ When zooming out, it is not a stack anymore

![2022-06-01-162059_1918x1058_scrot](https://user-images.githubusercontent.com/49868160/171427763-d70e3832-1f3e-4d20-a976-8269a71b8c29.png)
^ Then you can see a smaller stack and clicking this one works as expected (title and graph)

![2022-06-01-162105_1918x1058_scrot](https://user-images.githubusercontent.com/49868160/171427770-70c32d5a-6a24-49d8-b165-e04fe154e218.png)
^ When zooming in again, more blocks are stacked up again but the white arrow stays

#### Device or machine

chromium

**Comment by nymkappa** [comment]
Already fixed https://mempool.space/mempool-block/7
