### ISSUE TITLE
Write setup guide for regtest development

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#1788]
What I use https://gist.github.com/nymkappa/ed398c119169d941e89bff40591b5927
Something I found helpful to get started https://gist.github.com/System-Glitch/cb4e87bf1ae3fec9925725bb3ebe223a

@hunicus How do you suggest we integrate this into mempool's repo? Maybe in the backend readme?

**Comment by hunicus** [comment]
Ahh sorry I didn't get a notification about this for some reason. Yeah I think another section in the [development tips area of the backend setup docs](https://github.com/mempool/mempool/tree/master/backend#development-tips) would be good.
