### ISSUE TITLE
mempool homepage charts cut off date below time

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#1880]
### Description

title and screenshots

#### Version

mempool.space v2.4.0 [f901f069]

### Expected behaviour

the date fully visible or no date at all (if it is unwanted because it's always today's date)

### Screenshots

![image](https://user-images.githubusercontent.com/49868160/173434280-10889bf7-2c1a-4bdb-9eac-0b290d17d550.png)
^ something is cut off

![image](https://user-images.githubusercontent.com/49868160/173434476-b274b30d-f639-42c9-b95a-06a2d8f2016d.png)
^ edited the height of the chart with the inspector

#### Device or machine

chromium Version 102.0.5005.115 (Official Build) Arch Linux (64-bit)

**Comment by nymkappa** [comment]
Your chart looks very small. What screen resolution is that? Do you have custom font scaling on your OS, custom font size on your browser?

**Comment by antonilol** [comment]
i have a full hd (1920x1080) screen, window.innerHeight and width are 1918x985

i did not explicitly set a different font scaling or size

full screenshot:
![image](https://user-images.githubusercontent.com/49868160/173518060-7f7d8daf-f1e3-48b1-92e3-f557f7d97948.png)

also when in fullscreen mempool (with `F11`, window.innerHeight and width are 1920x1080 then) this text gets cut off
![image](https://user-images.githubusercontent.com/49868160/173518877-91ccf306-0a98-4dba-a9b9-89c0e862bf54.png)

**Comment by nymkappa** [comment]
Oh okay my bad I did not catch the `homepage` part. Does it render fine on https://mempool.space/graphs/mempool ?

**Comment by antonilol** [comment]
yes, with date

![image](https://user-images.githubusercontent.com/49868160/173525674-1a295650-9fc0-4e1c-ace2-543265dbb147.png)
