### ISSUE TITLE
Incorrect /api/blocks/tip/height result on RaspiBlitz

### ISSUE THREAD

**Issue by pxsocs** [mempool/mempool#1897]
### Description

Local instance installed on a RaspiBlitz returns an incorrect tip height through the mempool.space API.

Currently, I have a RaspiBlitz that is synchronizing and way behind on the tip height:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/40473443/174449795-db18e115-1503-46ed-9dbc-17d4c4ad3d6e.png">

On this same raspiblitz when calling the endpoint:
`http://raspberrypi.local:4080/api/blocks/tip/height` 
it returns:
`741319` 

Is the expected result of this endpoint to return the latest tip of the blockchain instead of where the synchronization is? If so, would be helpful to have an endpoint that would return the later to check synch progress through the API.

**Comment by wiz** [comment]
The tip refers to the block height of the valid chain with the most proof of work, which is contained in block headers. It is not related to any indexing or IBD status.
