### ISSUE TITLE
Graph legend seems to be shifted by one

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#190]
Got this bug report that seems to suggest that the legend labels are shifted by one

> It looks like there is an issue on the mempool,space graps#2h It burns 20-30 span, while actually it should be 30-40

> I mean it shows they got confirmed or mined (the height of the given span 20-30 is decreasing) but actually I have not confirmed transaction from the 30-40 span.

**Comment by jambolo** [comment]
You can verify this bug by comparing the lowest fee range with transactions removed by the latest block shown in the graph to the lowest fees in the that block's transactions.

**Comment by wiz** [comment]
Funny, I always just figured this was just a quirk of your implementation, never thought to report it as a bug

**Comment by jambolo** [comment]
I believe the problem is in mempool-graph.component.ts. ngOnInit() creates a legend whose first element is "1 sat/vb", but handleNewMempoolData() returns a series array that doesn't match for a non-liquid graph:

```javascript
 handleNewMempoolData(mempoolStats: OptimizedMempoolStats[]) {
    ...
    // Only Liquid has lower than 1 sat/vb transactions
    if (this.stateService.network !== 'liquid') {
      finalArrayVbyte.shift();
    }
    ...
```
I believe a solution is to also remove the first element of the the legend array for a non-liquid graph.

**Comment by jambolo** [comment]
Fix like this?
```javascript
    if (this.showLegend) {
      legendNames = [1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200,
            250, 300, 350, 400].map((sat, i, arr) => {
              if (sat === 400) {
                return '350+';
              }
              if (i === 0) {
                return '0 - 1';
              }
              return arr[i - 1] + ' - ' + sat;
            });
      // Only Liquid has lower than 1 sat/vb transactions
      if (this.stateService.network !== 'liquid') {
        legendNames.shift();
      }
      this.mempoolVsizeFeesOptions.plugins.push(
        Chartist.plugins.legend({ legendNames: legendNames })
      );
    }
```
