### ISSUE TITLE
Going to the Genesis block causes UI bug

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#1909]
How to reproduce:

1. Click on/open the latest block that has been mined
2. Now search for "0" in the search bar to go to the Genesis block

Now the left arrow to go to block 1 is missing.

<img width="284" alt="Screen Shot 2022-06-23 at 00 07 17" src="https://user-images.githubusercontent.com/8561090/175160579-c03f8e95-91ae-42e9-866e-1c1d57921f7b.png">

**Comment by nymkappa** [comment]
Not happening anymore
