### ISSUE TITLE
Get `runMainLoop error: Unknown column 'slug' in 'field list'.` error when running `mempool/backend` with `MEMPOOL_NETWORK=regtest`

### ISSUE THREAD

**Issue by oleonardolima** [mempool/mempool#1916]
### Description

Cannot start `mempool/backend` from docker image or docker-compose when using `MEMPOOL_NETWORK` parameter as `regtest`. It seems to not do the database migrations successfully and keeps logging the warning message: `runMainLoop error: Unknown column 'slug' in 'field list'.`

Endpoints that seems to no rely on the database works fine such as: `/api/v1/blocks/tip/height`, but others like `/api/v1/block/:hash` does not and returns 500 status code, with internal server error message:  `Unknown column 'pools.slug' in 'field list'`, while logging: `ERR: <regtest> Cannot get indexed block 17c74d3ca3c3714d235d5533d881fd24c8fbd7ec361c4f908c44ebd95517f46f. Reason: Unknown column 'pools.slug' in 'field list'`

#### Version

- db: `mariadb:10.5.8`
- web: `mempool/frontend:latest`
- api: `mempool/backend:latest`

### Steps to reproduce

The simple way to reproduce is to use the [docker-compose.yml file](https://github.com/mempool/mempool/blob/master/docker/docker-compose.yml), using the simple setup with Bitcoin Core RPC only, and updating the parameters:
 - `MEMPOOL_NETWORK`: "regtest"
 - `CORE_RPC_HOST`: "your-rpc-host" `mine is "host.docker.internal"`
 - `CORE_RPC_PORT`: "your-rpc-port" `mine is "18443"`

Even without creating any block it's possible to see the message in backend logs: `runMainLoop error: Unknown column 'slug' in 'field list'.`, and when creating a new block with some commands like: `generatetoaddress` to your RPC, it's possible to see that the `GET /api/v1/blocks/tip/height` endpoint returns correctly, but the `GET /api/v1/block/:hash` returns 500 and the error message: `Unknown column 'pools.slug' in 'field list'`

### Expected behaviour

The expected behaviour in my understanding would be the work properly with the `regtest` parameter, but it does not work.

It only works properly when using the default one `mainnet` while running it pointing to the `regtest` RPC port.

### Actual behaviour

It logs and returns the errors mentioned above and only works properly with the 'mainnet' parameter.

### Screenshots

![image](https://user-images.githubusercontent.com/16902160/175394531-55ce9671-d2c3-4970-a578-2dbd15218485.png)

#### Device or machine

OS+version: macOS 12.4
Docker Desktop: 4.8.2 (79419)

#### Additional info

It's possible to check that when running with 'mainnet' it creates the slug column in the pools table, but when running with  `regtest` it does not, even though the schema version and migrations seems to work.

**Comment by oleonardolima** [comment]
Please let me know if it's really a bug, or if I'm not supposed to use the parameter as `regtest`.

Also, I'll be more than happy to add more info and try to investigate the possible causes for the bug and contribute to the fix.

Until now I have not had any success in finding the cause for it, but the workaround to use as `mainnet` works

**Comment by wiz** [comment]
Regtest is not a valid configuration value for network, see https://github.com/mempool/mempool/blob/master/backend/src/config.ts

**Comment by oleonardolima** [comment]
Oh, thanks for the help!

Sorry for creating the GitHub issue though, my bad I've misunderstood the parameters 😅 

So it's really supposed to with mainnet network, event when RPC client is running on regtest. ?

**Comment by wiz** [comment]
We don't officially support regtest, which is why it's not in the list of network option, but yes it probably mostly works if you do that. It's for advanced users doing their own hacking so we don't have it documented or anything.

**Comment by oleonardolima** [comment]
Great! I'll do it that way, thanks for the help!!
