### ISSUE TITLE
RTL issues

### ISSUE THREAD

**Issue by EZ0010** [mempool/mempool#1921]
Hi, here are some RTL issues I found.

#### Version
v2.4.1-dev [[001bd1d4](https://github.com/mempool/mempool/commit/001bd1d4)]

### Screenshots
long input and output addresses are mirrored causing difficulty to read them
![image](https://user-images.githubusercontent.com/75021359/175614232-6834f911-0341-40b7-9b6d-2c49bf24e56f.png)

the indicator should be mirrored
![image](https://user-images.githubusercontent.com/75021359/175613467-0a1de66b-42ad-47b6-afc1-f59a7f7049a9.png)

overlapping icons
![image](https://user-images.githubusercontent.com/75021359/175614931-efcb6adf-6297-4657-82a1-3f41ed9c9859.png)

no space between icon and TXID
![image](https://user-images.githubusercontent.com/75021359/175614475-f97b6af0-e920-47eb-bbbf-124b6e32d504.png)
(LTR version)
![image](https://user-images.githubusercontent.com/75021359/175614574-c0f0417a-63b7-4bbc-b994-f1d3183a991d.png)

**Comment by wiz** [comment]
@TechMiX did you want to look into fixing these?

**Comment by TechMiX** [comment]
@wiz I'll take care of these issues. Thanks for reporting @EZ0010
