### ISSUE TITLE
Trim mining API responses using JSON arrays

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#1926]
Instead of sending an array of JSON object, containing hundreds of repeated fields name, switch to JSON arrays to make API response smaller (and faster).

**Comment by wiz** [comment]
I think the bigger and more obvious issue here is that you're storing raw JSON in MySQL. After fixing that so they're in proper columns of a table, you can present the data in the most efficient way.

**Comment by nymkappa** [comment]
Agreed. Thanks for the reminder. That's quite a big refactoring so I will keep this for later (2.5).
________________________________

**Comment by nymkappa** [comment]
Not sure this is still relevant, closing
