### ISSUE TITLE
Non-English users can't access English frontend

### ISSUE THREAD

**Issue by erikarvstedt** [mempool/mempool#2055]
Example:
A user visiting `mempool.space/en-US` with `Accept-Language` header `es-ES,...` is redirected to `mempool.space`, which defaults to the Spanish UI.
This redirect happens client-side in JS.
There's no way for the user to access the English version of mempool.

However, English-language users can access all UI languages via either `mempool.space` (English) or `mempool.space/<lang>` .

### Discussion
While fixing this, it might make sense to add an `en` alias for `en-US`, so that `mempool.space/en` works.

**Comment by wiz** [comment]
The way for users to override what their browser requests is to set a language preference, which saves a cookie, using the pull-down on the home page. We don't send any users to mempool.space/en-US so nobody goes there, not sure how you got that URL.

**Comment by erikarvstedt** [comment]
Ah, I didn't spot the language pulldown. This fixes it, thanks!
