### ISSUE TITLE
Improve support for packaging

### ISSUE THREAD

**Issue by erikarvstedt** [mempool/mempool#2092]
Here are a few simple ways to make mempool easier to package for (Linux) package managers.
By defining clear component scopes and boundaries, this can also simplify development.

## Backend

General principle: Clearly define which files and directories are required by the backend process at runtime.\
Ideally, these should only be `node_modules` and `dist`.\
Treat these dirs as immutable.

#### Current Issues
1. Problem: The config file location is hardcoded to a path in the src directory.\
   Fix: Make it configurable by an optional cmdline arg or env var.

2. Problem: File `./src/tasks/price-feeds/mtgox-weekly.json` is required at runtime.\
   Fix: Copy this file to `dist` during building and use module-relative addressing via `__dirname` at runtime.

3. Problem: `backend-info.ts` fetches `version` and `gitCommit` from outside of `dist`.\
   Fix: Move this part of `backend-info` to build time and store version info in `dist`.\
   This is more correct anyways because now the version info always reflects the actual version that was used for building.\
   *(Priority: Low)*

4. Problem: The backend requires to be run with `dist/..` as its working dir.\
   As a service process, the backend should never assume a specific working dir.\
   Fix: Convert `PWD`-relative paths to module-relative paths (`__dirname`).\
   *(Priority: Low)*

## In general

Try to keep the build process as deterministic as possible by not fetching files from the internet during building.
If fetching can't be avoided, try pulling in a Git repo by a known `rev` or check file hashes after downloading.
`frontend/sync-assets.js` is an offender here - but because external content fetching is restricted to this single place, it can be dealt with reasonably well.

## Discussion
Would you be interested in making `mempool` easier to package?\
I'd gladly help with providing fixes for the above issues. This would also allow me to finish the `nix-bitcoin` `mempool` package.

**Comment by wiz** [comment]
Fixed by #2096
