### ISSUE TITLE
ECONNREFUSED for mempool docker on localhost node

### ISSUE THREAD

**Issue by azbub** [mempool/mempool#210]
### Description

mempool docker doesn't connect to localhost node
#### Version

mempool:v1.0

### Steps to reproduce

run bitcoin node : 

`bitcoind -datadir=/path/ -wallet=/path/wallets/default -server -listen=1 -rpcworkqueue=64 -debug=rpc`

install and run mempool docker : 

```
docker pull mempool/mempool:v1.0

docker create -p 80:80 -e BITCOIN_NODE_HOST=127.0.0.1 -e BITCOIN_NODE_USER=user -e BITCOIN_NODE_PASS=password --name mempool mempool/mempool:v1.0

docker start mempool
```

### Expected behaviour

Expecting mempool to run on 127.0.0.1:80 and fetch data from bitcoin node

### Actual behaviour

checking logs, I see this : 
```

Error getBlockCount Error: connect ECONNREFUSED 127.0.0.1:8332
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8332
}
Error getMempoolInfo Error: connect ECONNREFUSED 127.0.0.1:8332
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8332
}
Updating mempool
getRawMempool error. Error: connect ECONNREFUSED 127.0.0.1:8332
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8332
}

```

### Screenshots

![image](https://user-images.githubusercontent.com/73410786/100522998-ef919a00-317a-11eb-88e0-ca311168820d.png)

#### Device or machine

Ubuntu Desktop 20.04 LTS

#### Additional info

bitcoin.conf : 

```
rpcuser=user
rpcpassword=password
zmqpubrawblock=tcp://127.0.0.1:8337
zmqpubrawtx=tcp://127.0.0.1:8337
txindex=1
printtoconsole=1
datadir=/path/
server=1
minrelaytxfee=0.000001
mintxfee=0.000001


```

I am able to connect to the node using the same credentials with a personal electrum server and c-lightening

**Comment by wiz** [comment]
@azbub can you please try again with v2 ? if still having issues feel free to re-open
