### ISSUE TITLE
Add Taproot to transaction features menu

### ISSUE THREAD

**Issue by Bosch-0** [mempool/mempool#2107]
Hey guys,

To help with spreading awareness, and hopefully adoption, of bech32m (P2TR), Mempool could add a Taproot option in the features section when viewing a transaction. When hovering over it you could highlight the fee savings and potential privacy benefits this transaction could have had if using this address type. 

Highlighted the section below:

![image](https://user-images.githubusercontent.com/55287964/178893908-8ec23889-ad9a-4bb4-8389-cd19d0b2dbbd.png)

**Comment by softsimon** [comment]
We do have a Taproot feature tag showing up when the transaction is a taproot-spend with a basic tooltip.

https://mempool.space/tx/d3bdc0d73c31ba6fb28c88caf66a9ebcb842fc03c0e206954fe5a57253dd339d

<img width="414" alt="Screen Shot 2022-07-14 at 12 57 20" src="https://user-images.githubusercontent.com/8561090/178967461-5875dd21-c66e-42c9-aaab-eed6414d977b.png">

So the question is what we should write in the tooltip. The Segwit tag I believe already contain the segwit savings.

**Comment by Bosch-0** [comment]
Oh cool, missed that. Some suggestions below:

**Multisig transactions**

Could include a grey pill called 'Privacy' that when hovered over suggests that this multisig output could be more private if using PT2R. This wouldn't be shown on P2TR multisig wallets obviously as we wouldn't know that they exist <3 

For the Taproot pill tooltip, the copy could state "This transaction uses Taproot. Future outputs will will be cheaper by x%" Hard to give an exact number, could just drop the "by x%" part and mention how overall future outputs will be cheaper. 

![image](https://user-images.githubusercontent.com/55287964/179143373-93f61085-3933-4cb5-bfcd-d449286d655b.png)

**P2TR transactions**

The tooltip could say "This transaction uses Taproot. Future outputs will will be cheaper by x%." Like I mentioned above, could drop the by x% and make it more general as its hard to know exact figures. 

![image](https://user-images.githubusercontent.com/55287964/179144006-e1734a53-1b97-430c-a3af-34aefbdb1934.png)

**Transactions with no P2TR outputs**

For transactions that don't use Taproot at all you could show a red strikethroughed Taproot like the SegWit pill below. The tooltip could say "This transaction could make future outputs cheaper by using Taproot."

![image](https://user-images.githubusercontent.com/55287964/179145359-62168aca-ef46-442c-9e4e-21c42e502735.png)

If these don't suffice could always link off to a more in-depth overview of Taproot in the tooltip. It's difficult to condense all the nuances down into a nice tooltip sized piece of info. 

Got a lot of my info from this post for reference btw: https://d.elor.me/2022/06/designing-for-taproot/
