### ISSUE TITLE
The lightning network seems to die if you are offline for too long

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#2156]
Unsure if that's an issue with lnd or our nodejs backend (or a combination of both with bad timings), but that's obviously incorrect. It happens when you go offline for a while.

<img width="1126" alt="Screen Shot 2022-07-23 at 10 53 01 AM" src="https://user-images.githubusercontent.com/9780671/180598053-5f7c563b-f4c1-494c-a521-cf6a356fd14e.png">

**Comment by softsimon** [comment]
Maybe the LND has shifted to graph in sync = false, but nodejs was still running so it doesn't check for it anymore? So maybe checking the isSync status again before the daily stats logging might fix it

**Comment by nymkappa** [comment]
Note: The issue is probably related to our lnd node running over Tor. That's going to be something that we need to handle for rpi users.
An basic safety mechanism would be to "freeze" updates on the nodejs backend end if the LN graph size drop by more than a specific threshold, indicating a network issue.

**Comment by nymkappa** [comment]
Afaik we can close this because we will by default run stats update often (every few minutes).
Also we update current day stats every time we run the update.
So the bad stats when your ln gets out of sync will be overriden when it goes back on track.
