### ISSUE TITLE
Add dummy node for tor connections on the map

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#2164]
There should be a dummy node placed somewhere (Antarctica? Somewhere in the ocean?) representing connections to tor nodes.

**Comment by nymkappa** [comment]
Hmmm I'm not sure that's a very good idea. What information does this provide? We already know the share of clearnet vs tor nodes with the other chart right.

Showing this on the map will pollute it a lot with false location information, probably slow down the rendering a lot as well.

I think maybe the reasonable way to show tor nodes on the map would be to only show one bright point, named "Tor nodes: XXXX", without showing the related channels.
