### ISSUE TITLE
when lightning is enabled every log message shows `<lightning>` instead of mainnet, testnet or other network

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#2191]
the cause is src/logger.ts:75

```ts
  private getNetwork(): string {
    if (config.LIGHTNING.ENABLED) {
      return 'lightning';
    }
    if (config.BISQ.ENABLED) {
      return 'bisq';
    }
    if (config.MEMPOOL.NETWORK && config.MEMPOOL.NETWORK !== 'mainnet') {
      return config.MEMPOOL.NETWORK;
    }
    return '';
  }
```

**Comment by softsimon** [comment]
It's intended. Because in production environment we have one server per network and use it to distinguish between them.

Correct me if I am wrong @wiz

**Comment by antonilol** [comment]
i would like something like "lightning mainnet"/"lightning testnet" or a separate lightning tag that only shows up on lightning related log messages

**Comment by wiz** [comment]
I think the title of this issue could be worded better, but yes lightning is a layer 2 network so we need <testnet> <lightning> not just <lightning> or perhaps we can use the :zap: emoji

**Comment by antonilol** [comment]
just found out this has been changed (#2416), closing
