### ISSUE TITLE
Line up the two graphs on the graphs page

### ISSUE THREAD

**Issue by jambolo** [mempool/mempool#232]
It would be easier view the interaction between the two graphs on the graph page if they lined up vertically. Currently, the upper graph is smaller and shifted to the right because of the legend, and that makes it difficult to compare the two graphs.

**Comment by softsimon** [comment]
We should try moving the legend onto the graph so that the graph can be full width.

**Comment by softsimon** [comment]
Both graphs are now lined up so I can close this issue.
