### ISSUE TITLE
Show the blocks on the main page using the mempool colors according to the transactions that they contain

### ISSUE THREAD

**Issue by jambolo** [mempool/mempool#233]
It would be helpful if the colors of the blocks on the main page matched the colors in the mempool graph according to the transactions that they contain. Each block would be colored by how much of the block is taken up by transactions at the different fee rates. This would give a quick indication of what fees are being included in the blocks and what fees will be included in the next blocks.

**Comment by softsimon** [comment]
I did experiments on this but decided that it would be too colorful, so settled on the current green to red gradient for the blocks.

Here's how it would look like:

<img width="545" alt="Screenshot 2020-11-30 at 10 33 29" src="https://user-images.githubusercontent.com/8561090/100566055-98fd9a80-32f7-11eb-8b61-1d4fce730a5e.png">
More dimmed:
<img width="512" alt="Screenshot 2020-11-30 at 10 33 40" src="https://user-images.githubusercontent.com/8561090/100566058-9ac75e00-32f7-11eb-9b52-8103c4b90f50.png">
<img width="499" alt="Screenshot 2020-11-30 at 10 33 48" src="https://user-images.githubusercontent.com/8561090/100566063-9d29b800-32f7-11eb-8ee4-efb8d5b8639f.png">
