### ISSUE TITLE
Esplora doesn't support Taproot tapscripts

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#2380]
This could either be a `blockstream/electrs` or a `rust-bitcoin` deficiency, but it's still a problem that we still don't support showing Tapleaf scripts in production.

When running your local Bitcoin Core (or Elements Core) we support it simply by doing the same thing as with Segwit: https://github.com/mempool/mempool/blob/master/backend/src/api/bitcoin/bitcoin-api.ts#L412

So it should be an easy fix / addition for Esplora as well. But requires some investigation where the problem lies. 

Here is a Liquid Testnet Taproot transaction for example: a0dc0d0128aff1c35cd6a911153abb57b1baa854e4037104f04cb36394ab1fc1

Elements Core:
<img width="552" alt="Screen Shot 2022-08-23 at 23 07 21" src="https://user-images.githubusercontent.com/8561090/186243486-65b843ca-9793-477b-8cf8-4ac8933a6f9d.png">

Blockstream/electrs
<img width="552" alt="Screen Shot 2022-08-23 at 23 07 25" src="https://user-images.githubusercontent.com/8561090/186243594-dead27ef-dd60-4ede-b5ad-6aead1fce411.png">

**Comment by wiz** [comment]
This is an ops issue, I probably just need to upgrade the electrs and re-index it. I'm sure it works on blockstream.info, right?

**Comment by softsimon** [comment]
> This is an ops issue, I probably just need to upgrade the electrs and re-index it. I'm sure it works on blockstream.info, right?

Esplora does not support it. Another example:

https://blockstream.info/tx/977b937e7ab7ca52d87ec25a50e36ff164dacb00165ef30dbb13f63c0e7bf7eb

With Bitcoin Core only:

<img width="548" alt="Screen Shot 2022-08-24 at 12 52 13" src="https://user-images.githubusercontent.com/8561090/186375020-c8d83748-fb95-4103-80b0-a07f0d43e158.png">

**Comment by wiz** [comment]
If so then I would just report the issue to Blockstream, it's not a bug in this repository

**Comment by ProgramComputer** [comment]
I checked the version of electron.blockstream.info which blockstream.info is based on 
```
var ElectrumClient = require("electrum-client-js")

const config = {
  host: 'electrum.blockstream.info',
  port: 50002,
  protocol: 'ssl',
}

const main = async () => {
  console.log('Connecting...')
  const client = new ElectrumClient(config.port, config.host, config.protocol)

  await client.connect()

  try {
    const ver = await client.server_version()
    console.log('Negotiated version:', ver)

    }
    catch (err)
    {
    console.log(err)
    }

  await client.close()
}

main().catch(console.error)
```
 It seems the version  [v0.4.1](https://github.com/Blockstream/electrs/releases/tag/v0.4.1) that it runs on does not contain the tapscripts. The [commit](https://github.com/Blockstream/electrs/commit/5cd986896a7e7039a3f929ba9cd63ee1d05cef4f) with the tapscripts came after  v0.4.1. There hasn't been a [newer stable release](https://github.com/Blockstream/electrs/tags) since then. As @wiz mentioned, it's an issue with a Blockstream not this repository.

**Comment by softsimon** [comment]
Fixed in https://github.com/mempool/electrs/pull/2
