### ISSUE TITLE
Make channel closing date more prominent

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#2479]
**A)**

In the Closed Channels list. Replace the Fee Rate with Closed Date and maybe only show it humanly readable like "< 1 hour ago"

**B)**

On a closed channels page, make it more apparent when the channel was closed on top by adding Closed date: <date> <date ago>

**C)**

When fee rate is missing, instead write `N/A` on the channels page

**Comment by nymkappa** [comment]
C is fixed in https://github.com/mempool/mempool/pull/2504
