### ISSUE TITLE
Make green badge for zero base fee channels

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#2490]
On the channels page. Add a "feature" badge after the Base Fee .. and it should be GREEN when the channel is zero fee base fee and yellow if not.

**Comment by nymkappa** [comment]
Following the same idea we can create a zero base fee node list.
You could either access it through the dashboard (a new widget) or when you click on the badge described in this feature request.

**Comment by softsimon** [comment]
> Following the same idea we can create a zero base fee node list. You could either access it through the dashboard (a new widget) or when you click on the badge described in this feature request.

The Top 100 node list should have a Zero base fee toggle that grey out the ones that are not :)
