### ISSUE TITLE
The difficulty and hashrate graph are not on equivalent units.

### ISSUE THREAD

**Issue by Transisto** [mempool/mempool#2491]
https://mempool.space/graphs/mining/hashrate-difficulty

The scales used for the different units should match so that the hashrate is overlapping the difficulty adjustments.

Example https://bitcoin.sipa.be/speed-lin-10k.png
![image](https://user-images.githubusercontent.com/388716/187963672-6ec682ed-cf4c-4500-aeeb-82f267431010.png)

![image](https://user-images.githubusercontent.com/388716/187963792-9ac33701-cdfa-4931-b338-f9a109896fc0.png)

I'm not sure of the exact hashrate to difficuly conversion but if reported hashrate is 100% stable the 0% difficulty adjustment line should end up on top of each others.

**Comment by Transisto** [comment]
One of the Y scale, difficulty or hashrate start at an the closest round amount

Hashrate start at 150 EH/s while Difficulty start at 25 T

25T should line up with the equivalent  25 * 2^32/600 = **178.95 EH/s** NOT 150 

From https://minerdaily.com/2021/how-are-bitcoins-difficulty-and-hash-rate-calculated/#:~:text=In%20this%20equation%20the%20probability,10%20minute)%20target%20block%20pace.


https://github.com/mempool/mempool/blob/3406758fd2fa25bafa088ec60786bb1dc16857dc/frontend/src/app/components/hashrate-chart/hashrate-chart.component.ts

The problem seems to be in that component, but couldn't pinpoint to it.

**Comment by nymkappa** [comment]
Honestly it looks fine to me right now. The scales are set automatically by apache echart library and I think it's doing a pretty good job at maximizing the use of chart space. Seeing the lagging difficulty movement from the hashrate is also straightforward.

What would a chart on equivalent does mean in practice? Both series starting and ending points at the same level?

**Comment by Transisto** [comment]
I still use sipa charts because I like to see the average for the epoch
turn into a fix value. For example if 90% of an epoch was 10% above last
hashrate I can visualize almost exactly where the next difficulty will land
on the chart.

Seems also easier for people to understand how bitcoin difficulty
adjustment works when they see how the new difficulty is exactly the
average of last 2016 blocks hashrate.

Difficulty adjustment is like a jumpy moving average but many less people
will see that from looking at those two offsetted lines.

**Comment by nymkappa** [comment]
Even the example of sipa chart the difficulty serie never really lands on the hasharte serie. Looking at the latest chart, I don't see what you are referring from `I can visualize almost exactly where the next difficulty will land
on the chart`. From the screenshot below, you cannot visually guess where the difficulty will land, series don't visually match at any point. Maybe I just don't get what you're trying to say, but if you want to make a PR feel free to do so and I will review it 👍🏻 

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/9780671/220843114-c1fea514-98dc-4434-a550-14c5609079a5.png">

**Comment by Transisto** [comment]
If you offset the difficulty line by one 2016 block period to the left
there should be exactly half of the area above and half below and the lines
will cross at least once per period.

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/220956674-553930c9-c073-41cf-ba6c-24c59985ef52.png)

**Comment by nymkappa** [comment]
Thank you for taking the time to clarify. I'll see if I can fix that.
