### ISSUE TITLE
Lightning: ISP View - City column should probably be called Location instead

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#2492]
Since we can't provide the exact location for all nodes, consider changing the label to a more generic term "Location".

![Screenshot from 2022-09-01 21-21-29](https://user-images.githubusercontent.com/100320/188058695-35e82022-9cda-48ec-880d-da78a80e44bc.png)

**Comment by nymkappa** [comment]
Oh yeah, before it was only the city and I forgot to change the label.
