### ISSUE TITLE
Lightning: Make Lightning ranking widgets consistent with Mining ranking widgets

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#2499]
Use the same number of nodes as the blocks/adjustments (6), drop the ranking position and adjust the alignment so both screens have similar looking widgets:

![Screenshot from 2022-09-01 22-27-22](https://user-images.githubusercontent.com/100320/188065550-56853b0f-626a-4f31-bc02-a868ad25927a.png)

**Comment by nymkappa** [comment]
If we drop the rank number and only show 6 lines, it will look very empty, so won't fix the way you've described.
@wiz suggested we could show the company/node operator logo in there if they allow us. I'm not sure if we have any lead on that part?
