### ISSUE TITLE
Wrong direction for RTL languages

### ISSUE THREAD

**Issue by TechMiX** [mempool/mempool#255]
### Description

The text direction for Right-to-Left languages is wrong.
Also the order of some components like tables should be the other way around. Titles of a sections should also be arranged from right to left.

#### Version

a831d04694201912647515032a0e8152fbb06b00

### Steps to reproduce

1. Change language to Persian
2. Change language to English

### Expected behaviour

After step 1, you should see all the texts translated to Persian and rendered from right to left.
After step 2, you should see all the texts in English and rendered from left to right.

### Actual behaviour

The texts are always rendered from left to right.

### Screenshots

![Screenshot_2020-12-03_15-41-15](https://user-images.githubusercontent.com/1241343/101046544-68c92c80-3581-11eb-9173-e360ad36b72e.png)
![Screenshot_2020-12-03_15-48-02](https://user-images.githubusercontent.com/1241343/101046576-6ebf0d80-3581-11eb-9153-78d583ab66bf.png)
![Screenshot_2020-12-03_15-48-51](https://user-images.githubusercontent.com/1241343/101046627-7b436600-3581-11eb-846f-2f7959d1c332.png)
![Screenshot_2020-12-03_15-51-04](https://user-images.githubusercontent.com/1241343/101046655-81394700-3581-11eb-86d8-c2dff9626758.png)
![Screenshot_2020-12-03_15-51-31](https://user-images.githubusercontent.com/1241343/101046681-85fdfb00-3581-11eb-8cdc-71fbffad0d3a.png)
![Screenshot_2020-12-03_15-55-14](https://user-images.githubusercontent.com/1241343/101046694-88605500-3581-11eb-9e89-03a4a4999bd4.png)
![Screenshot_2020-12-03_15-55-46](https://user-images.githubusercontent.com/1241343/101046704-8a2a1880-3581-11eb-8ed7-b845e153c3ef.png)

#### Additional info

Adding `dir='rtl'` to `html` tag would fix the rendering problem. But the elements in About and Graph page get scrambled..

**Comment by wiz** [comment]
> Adding `dir='rtl'` to `html` tag would fix the rendering problem. But the elements in About and Graph page get scrambled..

For starters I can try setting RTL on html tag and LTR tag on About and Graph page elements
