### ISSUE TITLE
Nodes with no URIs is tagged as "tor only"

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#2570]
Example is the BitGo node which has no public URIs https://mempool.space/lightning/node/03a9364a1f954fc146fdea379957aa778273d641805299d18cae5621563d541851

So "Tor only" is wrong since there are no Tor address available (?)

<img width="1174" alt="Screen Shot 2022-09-21 at 16 17 54" src="https://user-images.githubusercontent.com/8561090/191529000-9aa805ae-cecc-41fb-a9b1-2d826d7e28a2.png">

**Comment by nymkappa** [comment]
You're right. I think I show the `Tor` badge when we don't have any ISP info, which is not a correct assumption.
