### ISSUE TITLE
[UI] Reverse the arrow of time in the block view

### ISSUE THREAD

**Issue by mutatrum** [mempool/mempool#2588]
### Description

Currently, the arrow of time is pointing to the left in the block view. This is counter-intuitive, as time normally flows in the other direction.

![image](https://user-images.githubusercontent.com/56344102/193007546-4729831a-5bf7-4b91-800a-b7c3d531ff30.png)

### Problem to be solved

The more intuitive way of reading the arrow of time would be to go to the right. This is in alignment with the other graphs.

### Proposed solution

Put mined blocks to the left of the divider, and future blocks (mempool) on the right side.

Ugly mock-up:

![image](https://user-images.githubusercontent.com/56344102/193007690-9de84108-e727-4ff9-945a-dd854f65809d.png)

#### Additional info

For right-to-left reading countries, this could be a switchable toggle.

Idea is from @dergigi, see https://twitter.com/dergigi/status/1575214771846402048.

**Comment by wiz** [comment]
@mononaut I think it would be cool to have a user preference (toggle switch?) to be able to reverse the flow of the timechain
