### ISSUE TITLE
Testnet payment to Taproot address displays that it's not a Taproot tx

### ISSUE THREAD

**Issue by SamSamskies** [mempool/mempool#2609]
### Description

Taproot is crossed out in the `Features` section.

https://mempool.space/testnet/tx/7baf2bf13ce1d182be4d6f4870b5244dc57eccfcbfbc7fe4ad5208be1afeb194

![Screen Shot 2022-10-05 at 6 45 29 PM](https://user-images.githubusercontent.com/3655410/194183475-e329deef-36a7-4e65-aa91-82173a91c295.png)

**Comment by brando2131** [comment]
@SamSamskies 

Your transaction needs to be "from" a taproot output in order to be a taproot transaction. 

You are just sending "to" a taproot output.

**Comment by SamSamskies** [comment]
Ahhhh okay. Thanks.
