### ISSUE TITLE
RTL mode improvements

### ISSUE THREAD

**Issue by TechMiX** [mempool/mempool#261]
### Description

When you change the language to a right-to-left language like Persian:
1. It appears that the content of all cells in all tables is aligned to left. It should be aligned to right.
2. The arrows in Transaction page for inputs/output should point from right to left.
3. Titles should be also aligned to right instead of left. That includes tables and pages.
4. Some units like 'MB', 'B', 'kWU' are not available for translation. They either should be available for translation or the text containing them should be treated as left to right. 'MB 1' does not make sense in an RTL language.
5. Scrolling through the recent blocks on phone isn't possible with the RTL layout where it is possible in the LTR layout.

#### Version

1af1f7211e704a5a95d1038b9f5479fc513affd5

### Steps to reproduce

1. Change the language to Persian.
2. Go to blocks pages.

### Expected behaviour

You should see the content of the tables aligned right to left.

### Actual behaviour

Everything is still aligned to left.

### Screenshots

![Screenshot_2020-12-04_21-22-21](https://user-images.githubusercontent.com/1241343/101229017-8c35c980-369e-11eb-889c-9343c475baa8.png)

**Comment by EZ0010** [comment]
Agreed, the current RTL layout has some issues, and btw LTR layout with Arabic language or Persian will work without any issues and people will understand the UI much much better than the current one.

**Comment by TechMiX** [comment]
> ... btw LTR layout with Arabic language or Persian will work without any issues and people will understand the UI much much better than the current one.

Nope. LTR layout with Persian would break the text in many places. Specially when numbers and text are mixed. Bi-directional won't work.

**Comment by EZ0010** [comment]
> > ... btw LTR layout with Arabic language or Persian will work without any issues and people will understand the UI much much better than the current one.
> 
> Nope. LTR layout with Persian would break the text in many places. Specially when numbers and text are mixed. Bi-directional won't work.

for Arabic, this UI is readable, and it is much better than the current one. [I'm Arab and I prefer it]
<img width="1792" alt="Screen Shot 2020-12-07 at 12 38 20 PM" src="https://user-images.githubusercontent.com/75021359/101334666-3a04cc00-3889-11eb-888b-3f41972e4c10.png">

Also scrolling through the recent blocks on phone isn't possible with the RTL layout where it is possible in the LTR layout.

**Comment by TechMiX** [comment]
> Also scrolling through the recent blocks on phone isn't possible with the RTL layout where it is possible in the LTR layout.

Good point. I added this to the improvement list.

> for Arabic, this UI is readable, and it is much better than the current one. [I'm Arab and I prefer it]

Interesting. What about other page? blocks, transactions, etc.
For example I checked and the API page is not translated in Arabic yet, but if you check that in Persian in LTR layout the text is scrambled, where as in RTL layout they're rendered in the right order.

BTW, from the image you shared, aren't these wrong? shouldn't the order of words and numbers be the other way around?
![arabic_wrong1](https://user-images.githubusercontent.com/1241343/101346331-acc17780-3888-11eb-9262-05b2ad33ff6d.png)
<img width="158" alt="arabic_wrong2" src="https://user-images.githubusercontent.com/1241343/101346335-adf2a480-3888-11eb-95ef-0b2b060c360c.png">
<img width="177" alt="arabic_wrong3" src="https://user-images.githubusercontent.com/1241343/101346342-b054fe80-3888-11eb-8e78-5ebe45203f15.png">

**Comment by EZ0010** [comment]
> <img alt="arabic_wrong3" width="177" src="https://user-images.githubusercontent.com/1241343/101346342-b054fe80-3888-11eb-8e78-5ebe45203f15.png">

the text in these images you shared aren't in correct order yes that should be corrected, but not like with the current solution, I'm against mirroring the whole UI of the site just to fix RTL languages, doing this will case a lot of issues with the UI. lot of things will not work [like the scrolling thru the blocks] and lot of things will look ugly because the whole design of the site was made for LTR in first place. So I think RTL should be

**Comment by TechMiX** [comment]
I created this issue to point out the problems in RTL mode. Not using it at all could be a new issue by itself I guess.
Current solution was chosen because there were no practical way to go through all the texts to see which one is rendered wrong and fix it. If we can find a practical way, I too prefer that approach.
IMO, Localization is not just about replacing the words. But to make a tool usable in another locale. So I agree with you in not breaking the usability.

**Comment by TechMiX** [comment]
#268 fixed this.
