### ISSUE TITLE
Dropdown logo misaligned in RTL layout

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#2613]
Bitcoin logo in the network dropdown in RTL layout

<img width="76" alt="Screen Shot 2022-10-06 at 21 55 02" src="https://user-images.githubusercontent.com/8561090/194384756-110f6b94-d6b1-44da-b25d-b418063e24f4.png">

**Comment by TechMiX** [comment]
This is fixed as far as I can see @softsimon
