### ISSUE TITLE
Taproot tooltip is wrong when savings are negative

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#2630]
Sometimes the savings of switching to Taproot is in the negative, but the tooltip will still say "This transaction could save -10%...".

Example TX: https://mempool.space/tx/7ccf52f0270db329061b49814df51e105e2179237dfc6b860ff0de9f1db7d3a6

**Comment by Saberhabeelshohdy** [comment]
1. ### [_[](url)``_](url)

**Comment by Saberhabeelshohdy** [comment]
Thanks
