### ISSUE TITLE
clicking the input in a coinbase tx in the flow diagram gets you to tx `00000000....00000000`

### ISSUE THREAD

**Issue by antonilol** [mempool/mempool#2640]
### Description

title

#### Version

mempool.space v2.5.0-dev [ddb1e97c]

### Steps to reproduce

go to https://mempool.space/, click a block, then click the coinbase transaction, then click the input arrow of the flow diagram

### Expected behaviour

arrow is not clickable

### Actual behaviour

it waits until tx 0000000000000000000000000000000000000000000000000000000000000000 get broadcasted (it never will)

### Screenshots

![image](https://user-images.githubusercontent.com/49868160/195889859-ef5497ae-beeb-42a7-aed9-699fc8cdb556.png)

**Comment by mononaut** [comment]
Good catch! This should be fixed by PR #2627
