### ISSUE TITLE
Mobile view rearrange tiles

### ISSUE THREAD

**Issue by MaxHillebrand** [mempool/mempool#2688]
### Description

In the mobile view, move the mempool fee rate chart tile above the difficulty adjustment tile.

### Problem to be solved

The default starting view on mobile does not show the chart, yet it is arguably the number one reason why people visit the site.

![IMG_20221114_132806.jpg](https://user-images.githubusercontent.com/30683012/201660049-4daa3886-3dd0-4cdc-b253-9b4d2cc195ed.jpg)

### Proposed solution

Move the `Difficulty Adjustment` tile below the feechart tile, only in mobile view.

**Comment by hunicus** [comment]
This seems like it's already the case? Maybe something changed when the difficulty adjustment widget was updated in the past few days.

Feel free to re-open if necessary.

![Screen Shot 2023-03-23 at 03 17 11](https://user-images.githubusercontent.com/93150691/227131297-8c963ffd-be71-44de-9339-358a390020ef.png)
