### ISSUE TITLE
Can't use mempool.js to broadcast raw transaction to signet

### ISSUE THREAD

**Issue by h76oeI6pMxU9g4p8aCpc6Q** [mempool/mempool#2693]
I installed the lastest version of mempool.js from npm.
https://www.npmjs.com/package/@mempool/mempool.js

Node.js version is v19.1.0

My code is....
```ts
import mempoolJS from '@mempool/mempool.js'

const { bitcoin: { transactions } } = mempoolJS({
    hostname: 'mempool.space',
    network: 'signet'
})

const txhex = 'a_valid_txhex';
const txid = await transactions.postTx({ txhex });

console.log(txid);
```
Run the program, then throwing this exception.
'sendrawtransaction RPC error: {"code":-22,"message":"TX decode failed. Make sure the tx has at least one input."}'

I copied the same txhex to https://mempool.space/signet/tx/push
The transaction is broadcast successfully!

Also, I saw the API doc is inconsistent with the actual code.

The "txhex" param on "transactions.post()" function is lowercase on "h" but is uppercase "txHex" on the API doc.
I prefer to use "txHex" (camelcase) which is commonly using in javascript / typescript

https://mempool.space/docs/api/rest#post-transaction
https://mempool.space/signet/docs/api/rest#post-transaction
https://mempool.space/testnet/docs/api/rest#post-transaction

**Comment by wiz** [comment]
Is this a different issue from #2165 ?

**Comment by Bzvwf16WSDKoSZd8** [comment]
This is same. I reopen it because the problem haven't solved after 3 month.
I also add the API doc is inconsistent issue.

**Comment by natsoni** [comment]
Fixed in https://github.com/mempool/mempool.js/pull/165
