### ISSUE TITLE
Dashboard slowly leaks memory and eventually crashes browser

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#273]
Need to investigate, but leaving the dashboard open on a Raspberry Pi will crash it after a few days

**Comment by mmikeww** [comment]
i was just going to post this... i'm on windows and on Chrome, and i like to leave mempool always opened in a tab, but every now and then i check Chrome's Task Manager and the mempool tab is using up GBs worth of memory

**Comment by wiz** [comment]
If I roll up the dashboard to hide the charts my RPI no longer crashes
