### ISSUE TITLE
Track transactions that weren't in the mempool

### ISSUE THREAD

**Issue by unruhschuh** [mempool/mempool#2736]
Would it be possible to track transactions that weren't in the mempool? This way we could see transactions directly sent to miners or issued by them. Just wondering how common this is.

**Comment by mononaut** [comment]
Is this solved by the block audit feature?

<img width="1102" alt="Screenshot 2023-03-13 at 6 56 17 PM" src="https://user-images.githubusercontent.com/83316221/224667960-69ecd106-7f66-4148-8044-8a3ccda96cab.png">
