### ISSUE TITLE
Fractional vsize

### ISSUE THREAD

**Issue by carnhofdaki** [mempool/mempool#2746]
### Description

As far as I know, there is no fractional `vsize` in Bitcoin Core.

Look at transaction https://mempool.space/testnet/tx/7bf2c6165971818834dc008ef44b4714b591be0b92cf3615076c27bfb91c1665

Decoded by Bitcoin Core, it is this:

```json
{
  "txid": "7bf2c6165971818834dc008ef44b4714b591be0b92cf3615076c27bfb91c1665",
  "hash": "442880d143f73d6473f02f69263351032db597452df6f03d36804c7fccffc059",
  "version": 2,
  "size": 203,
  "vsize": 122,
  "__comment": " ... etc. above is from bitcoin-cli getrawtransaction 7bf2c6165971818834dc008ef44b4714b591be0b92cf3615076c27bfb91c1665 true"
}
```

But mempool.space shows Virtual size as `121.25`

#### Version

```
node206.fra.mempool.space (v2.5.0-dev) [ddb1e97c]
```

### Steps to reproduce

Send a minimal-fee transaction from one UTXO to one output which is a TapRoot address and watch it on mempool.space

### Expected behaviour

I would expect the **Fee rate** to be `1.0 sat/vB`.

### Actual behaviour

The **Fee rate** shows `1.01` as computed with the `121.15` vsize.

**Comment by vostrnad** [comment]
`vsize` is just `weight` divided by 4. When the weight isn't a multiple of 4, some software shows the fractional part, while other shows a rounded amount, and there's nothing wrong with either approach.

**Comment by carnhofdaki** [comment]
@vostrnad Yes, I see your point. It is precise and technically correct. Just that the result may be misleading if `vsize=weight/4` ends with a fractional result and `feerate=vsize/txfee` is not showing the feerate one chose when forming the transaction (i.e. `fee_rate` option of Bitcoin Core `sendtoaddress` RPC).

What do you think? Would it make sense to normalize the feerate shown by mempool.space and `fee_rate` requested in the API call?

**Comment by 0xB10C** [comment]
fwiw from BIP-141:

> Virtual transaction size is defined as Transaction weight / 4 (rounded up to the next integer).

https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#transaction-size-calculations
