### ISSUE TITLE
changing from Arabic to English isn't possible

### ISSUE THREAD

**Issue by EZ0010** [mempool/mempool#275]
### Description

there is some kind of bug when changing language of mempool from Arabic language to English, it doesn't work probably. it works on other languages but not Arabic I don't know why.

#### Version

current version on mempool.space (maybe `c7abb7a0`)

### Steps to reproduce

1. visit mempool from a browser that sends  `accept-language: ar` in the headers.
2. it will show Arabic as default language, change language to English, it won't do anything, it will refresh the page.
3. type mempool.space/en in the URL, it will change the language.
4. refresh the page after the language changed it will go back to Arabic ( it doesn't save preferences).

 ### Expected behaviour

change language and save preferences

### Actual behaviour

doesn't change language and save preferences

**Comment by wiz** [comment]
Yeah we're about to deploy a new server side rendering system which will change the way i18n works entirely, but for now you can clear your cache and it should work

**Comment by wiz** [comment]
Re-opening due to possibly reproducing again
