### ISSUE TITLE
Getting stuck on "loading blocks" after fresh install

### ISSUE THREAD

**Issue by rootzoll** [mempool/mempool#277]
### Description

On first install (for example on a RaspiBlitz) when user call mempool WebUI they report it as an error that they get stuck on the "loading blocks" message. Normally after quite a while (when mempool gathered enogh block data) it will then show results ... but then users already started support requests or even deinstalled app thinking it was broke.

#### Version

v1.0.1 (if this is fixed/improved in newer version already, please let me know)

### Steps to reproduce

Make a fresh install of mempool (on RaspiBlitz) and call WebUI.

### Expected behaviour

Letting the user know why its taking so long. If mempool just needs to gather more data - it should tell the user to wait.

### Actual behaviour

User just sees "loading blocks" spinner and thinks install did not work.

### Screenshots

![Bildschirmfoto 2020-12-22 um 23 15 17](https://user-images.githubusercontent.com/2472225/103034617-90e6f280-4565-11eb-937e-48ea0fe1fa34.png)

**Comment by wiz** [comment]
We will soon release mempool v2.0 for Raspberry Pi devices which solves this issue. Please wait a few weeks

**Comment by softsimon** [comment]
I am running the development version of Mempool V2 using my Raspiblitz node as we speak.. The initial startup sync is very fast as well. It will solve all the issues with V1 so flagging all the V1 issues as wont-fix and hopefully the V2 version will be shipped in the new Raspiblitz, Mynode and other node solutions in time.

<img width="1029" alt="Screenshot 2020-12-16 at 18 52 02" src="https://user-images.githubusercontent.com/8561090/103277184-0423b500-49fb-11eb-9247-689916a2a051.png">
