### ISSUE TITLE
Add support for rpccookiefile in bitcoind.conf

### ISSUE THREAD

**Issue by ShadwDrgn** [mempool/mempool#2806]
### Description

In order to avoid username/passwords which are not the recommended config for bitcoind it would be great if i could import the rpccookiefile for bitcoind instead of using user/pass

### Problem to be solved

lnd, electrs, and most other tools i use utilize the cookie file to avoid using a static user:pass, but I'm unable to use mempool with this configuration because it appears as though there is no support for the cookie file

### Proposed solution

allow mempool to use the cookie file for bitcoind rpc authentication

**Comment by federicociro** [comment]
I second this request? How can I help with this issue? Any pointers to start with?

**Comment by BeardMatt** [comment]
I third this request!

**Comment by BeardMatt** [comment]
> #1023, i wanted this almost a year ago, and there are more people that want this (#2803), i think i can implement this in the coming week if i find some free time

Awesome, thank you!
