### ISSUE TITLE
Missing vsize value in /api/tx/:txid

### ISSUE THREAD

**Issue by djbooth007** [mempool/mempool#282]
The transaction API via /api/tx/:txid is missing the virtual size of the transaction.

Knowing the vSize value is useful for fee-bumping techniques such as RBF and Child Pays For Parent.

**Comment by wiz** [comment]
@shesek is this something you can add into electrs easily?

**Comment by softsimon** [comment]
`vsize` is just the `weight` property divided by 4 so I don't think it's necessary to have as a own property.

Anyway it's nothing we can add since it's from the `blockstream/electrs` backend and needs to be suggested there.

**Comment by djbooth007** [comment]
> `vsize` is just the `weight` property divided by 4 so I don't think it's necessary to have as a own property.

Fair enough.

**Comment by shesek** [comment]
Indeed, `vsize` isn't available because its redundant. The esplora block explorer frontend also divides the weight by 4 to display it.
