### ISSUE TITLE
Is it possible, to backport fee-api.ts to v1.0 branch?

### ISSUE THREAD

**Issue by DocBrown101** [mempool/mempool#286]
### Description
The estimate of fees in the master seems to be much more accurate.
It would be very nice if we could have that in version 1 as well.

From here:
https://github.com/mempool/mempool/blob/master/backend/src/api/fee-api.ts
to here:
https://github.com/mempool/mempool/blob/v1.0/backend/src/api/fee-api.ts

That shouldn't be too hard.

On my [raspiblitz](https://github.com/rootzoll/raspiblitz) runs unfortunately only version 1

**Comment by softsimon** [comment]
V1 is deprecated but will soon be replaced by V2 and the updated fee api.
