### ISSUE TITLE
WARN: runMainLoop error: connect ECONNREFUSED 172.20.0.1:8332. Retrying in 40 sec.

### ISSUE THREAD

**Issue by Bianconiglio** [mempool/mempool#2870]
Hello,
i have this problem: WARN: runMainLoop error: connect ECONNREFUSED 172.20.0.1:8332. Retrying in 40 sec.

i have fulcrum server and bitcoind sync and installed in the locahost.

fulcrum server work and there is connection when up the docker of mempool i have problem to connect to bitcoind. If i do a telnet in localhost on port 8332 there is connection.

in bitcoind i have this configuration:

rpcallowip=0.0.0.0/0
rpcport=8332
txindex=1
server=1
rpcuser=mempool
rpcpassword=mempool
proxy=127.0.0.1:9050

in docker-compose.yml i have this configuration:

version: "3.7"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 80:8080
  api:
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "172.20.0.1"
      ELECTRUM_PORT: "50002"
      ELECTRUM_TLS_ENABLED: "true"
      CORE_RPC_HOST: "172.20.0.1"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "mempool"
      CORE_RPC_PASSWORD: "mempool"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache
  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    user: "0:0"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql

when start docker-compose up this is the result:

pi_1  | Dec 23 09:57:26 [98] NOTICE: Starting Mempool Server... (a210a3f)
api_1  | Dec 23 09:57:27 [98] INFO: Connected to Electrum Server at 172.20.0.1:50002 (["Fulcrum 1.9.0","1.4"])
api_1  | Dec 23 09:57:27 [98] INFO: Database connection established.
api_1  | Dec 23 09:57:27 [98] INFO: Starting statistics service
api_1  | Dec 23 09:57:27 [98] INFO: Starting currency rates service
api_1  | Dec 23 09:57:27 [98] INFO: Currency rates service will be queried over clearnet using https://price.bisq.wiz.biz/getAllMarketPrices
api_1  | Dec 23 09:57:27 [98] NOTICE: Mempool Server is running on port 8999
api_1  | Dec 23 09:57:27 [98] INFO: Updating latest mining pools from https://raw.githubusercontent.com/mempool/mining-pools/master/pools.json over clearnet
api_1  | Dec 23 09:57:32 [98] WARN: runMainLoop error: connect ECONNREFUSED 172.20.0.1:8332. Retrying in 10 sec.
api_1  | Dec 23 09:57:42 [98] WARN: runMainLoop error: connect ECONNREFUSED 172.20.0.1:8332. Retrying in 20 sec.
api_1  | Dec 23 09:58:02 [98] WARN: runMainLoop error: connect ECONNREFUSED 172.20.0.1:8332. Retrying in 40 sec.

do y can help me? Thank's

**Comment by wiz** [comment]
connection refused means it cannot connect to your bitcoind RPC at the configured IP and port - this is not a bug in mempool

**Comment by Bianconiglio** [comment]
yes i know but sorry i dont understand where put this question
