### ISSUE TITLE
CPFP button disappears unexpectedly

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#2905]
Step to reproduce:

1. Go to a TX that does not have CPFPs like: 61e3293d156f2b54dc8f416508fa8e6e5a2bcb89b81a6abecf1cd430a0777a77
2. Use the Search bar to paste a CPFP-transaction like 000044572d9f4d0a60eae9752bae23a8660306b839bb5f69d3830954267aed5d
3. The CPFP button is hidden
4. Reload the page... and it's visible

**Comment by softsimon** [comment]
> I think I have a fix for this, if it's still unresolved?

Correct. I tried to fix it but was unable to due to the trickieness with the RxJS entering a fail state and not recovering.

**Comment by mononaut** [comment]
Cool, I've just opened a PR which I think resolves the issue: #2955
