### ISSUE TITLE
Tip Hash endpoint is broken

### ISSUE THREAD

**Issue by jaonoctus** [mempool/mempool#2968]
### Description

```
Cannot GET /api/v1/blocks/tip/hash
```

#### Version

v2.4.0 [f901f069]

### Steps to reproduce

- do a GET request to `/api/blocks/tip/height` endpoint

### Expected behaviour

Returns the hash of the last block.

### Actual behaviour

404 Not Found

### Screenshots

![image](https://user-images.githubusercontent.com/7918067/214692512-e2151976-5b7a-4278-a2b9-8b80893023e8.png)

### Device or machine

Docker images

 image | tag | digest
---|---|---
mempool/frontend | v2.4.0 | sha256:f71722f1e3abfb3d8a3df6f2a32e384d39434e311bb83d810629077b4fa6ffaf
mempool/backend | v2.4.0 | sha256:6036cc6866b782efadc765e8189958940202b3fa1770eb35c35210c86efd2f47

**Comment by vforvilela** [comment]
Same thing here.
`/api/blocks/tip/hash` does not work
![image](https://user-images.githubusercontent.com/80433106/214698604-4ade5bf8-74b1-4f63-92f8-10069de1ef06.png)


while `/api/blocks/tip/height` does.
![image](https://user-images.githubusercontent.com/80433106/214698678-a9a05dae-bb49-4013-a0a9-8da89a6cd55a.png)

**Comment by MiguelMedeiros** [comment]
Hey @jaonoctus @vforvilela !

I was searching for this endpoint on my node and realized that I was using 'electrum' on my `config.MEMPOOL.BACKEND` variable. Take a look here: https://github.com/mempool/mempool/blob/59eb27178236eaba39cff304db6d1773415d31e6/backend/src/config.ts#L9

This endpoint is only available on `esplora` as your `MEMPOOL.BACKEND` config: 
https://github.com/mempool/mempool/blob/59eb27178236eaba39cff304db6d1773415d31e6/backend/src/api/bitcoin/bitcoin.routes.ts#L100-L123

**Comment by MiguelMedeiros** [comment]
Yes, @vforvilela.  I have the same error. 

`/api/blocks/tip/hash`
![image](https://user-images.githubusercontent.com/5798170/214700498-2ea2faeb-002d-4d3e-9d72-c88b4fe6b74f.png)

`/api/blocks/tip/height`

![image](https://user-images.githubusercontent.com/5798170/214700170-a4ff3e4c-e2ed-4442-b6ca-cf8eb11a614d.png)

**Comment by antonilol** [comment]
works for me on v2.5.0-dev [69f5d483] (backend: electrum + bitcoin core)
![image](https://user-images.githubusercontent.com/49868160/219743566-b6d460e2-b567-4530-b966-227db8371967.png)
and on mempool.space on v2.5.0-dev [49754745]
![image](https://user-images.githubusercontent.com/49868160/219743967-f5e31f2c-bb56-4cdc-8715-f60abd250587.png)
https://mempool.space/api/blocks/tip/hash

**Comment by jaonoctus** [comment]
@antonilol updated to this dev docker image, works for me. thank you for mentioning
