### ISSUE TITLE
Add detailed overlay for mempool graph.

### ISSUE THREAD

**Issue by ascisco** [mempool/mempool#297]
I think it would be a great addition to add a detailed overlay to the mempool graph page. Whereas when you hover over the graph a overlay shows a breakdown of size of txs for each sat/vbyte level.

A great example of this feature can be found at mempoolstats.com under their "Mempool Size in MB" graph.

This would better help visualize and estimate fees for transactions. 

Thanks for your consideration, keep up the great work!

**Comment by softsimon** [comment]
I agree this is needed.

Related to  #94

**Comment by manakill** [comment]
Came here to suggest the same thing lol

**Comment by softsimon** [comment]
Fixed in https://github.com/mempool/mempool/pull/738
