### ISSUE TITLE
Expose median timestamp

### ISSUE THREAD

**Issue by AlexLloyd0** [mempool/mempool#2998]
Median timestamp is a useful property of blocks due to being monotonically increasing. It's included in the response from bitcoin-core for [many endpoints](https://developer.bitcoin.org/reference/rpc/getblock.html)

We're building an app using mempool's API to query the blockchain, and having a monotonically increasing timestamp is crucial for us. We're currently computing the median timestamp ourselves, but it would be really useful to pass this through and expose via mempool's API (and maybe in the UI?)

Happy to implement this with a couple of pointers

**Comment by nymkappa** [comment]
Related https://github.com/mempool/mempool/pull/3070. Once this PR is merged I'll update the blocks API to expose the median block timestamp.
