### ISSUE TITLE
[Lightning] Charts on the home screen look broken when there are few data points

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#3004]
When we don't have enough historical data to zoom out the chart, the legends overlap the lines:

![Screenshot from 2023-01-31 21-08-32](https://user-images.githubusercontent.com/100320/215956937-cf608e99-0c37-454f-acc2-ae6c65e1a49a.png)

**Comment by nymkappa** [comment]
Not sure what we can do about the rendering since we don't have much data points. The same issue exists for all charts.
The legend positioning can be fixed tho, right now it's hardcoded.
