### ISSUE TITLE
My browser language preferences are set to English, but website renders in Portuguese

### ISSUE THREAD

**Issue by fiatjaf** [mempool/mempool#3008]
The website is being displayed in Portuguese: 
![2023-02-01-192728_916x752_scrot](https://user-images.githubusercontent.com/1653275/216178086-ad254f23-5238-48a4-aeeb-5bcf8909a46c.png)

But my browser preferences are for English everywhere:
![2023-02-01-192841_295x250_scrot](https://user-images.githubusercontent.com/1653275/216178347-660f2e7c-146c-4f39-93f0-51aeca3e76e2.png)
![2023-02-01-192921_158x91_scrot](https://user-images.githubusercontent.com/1653275/216178397-f5a284c1-2ad4-4779-989a-4cb7891a3d8b.png)

**Comment by softsimon** [comment]
Perhaps you changed before, or someone sent you a link with the /pt/ language already in the URL.

Anyway change to English on the main page bottom and it will set a cooke.

**Comment by fiatjaf** [comment]
Hm. Makes sense. Someone has probably sent me this poisoned URL.

Thank you.
