### ISSUE TITLE
Links to Block Health Section in FAQ

### ISSUE THREAD

**Issue by cryptoquick** [mempool/mempool#3026]
### Description

Maybe it'd make sense to add links to make the [Block Health](https://mempool.space/docs/faq#what-is-block-health) section more more discoverable.

### Problem to be solved

The colors in the blocks seemed interesting, but it was hard to figure out what they meant.

### Proposed solution

I'd recommend adding a prompts to the tx view like, "Why was this transaction included?" to aid in discoverability, similar to the "Why is this block empty?" info button on this block:
https://mempool.space/block/000000000000000000037a742ade26b8ce39bb54abcde129ee8fb30b58f10a26

#### Additional info

There seems to be a lot of stuff written about this in #2662... In particular, this table seemed helpful and might be good to have in the FAQ also:
![Screenshot from 2023-02-08 20-50-53](https://user-images.githubusercontent.com/285690/217713503-8d296b04-e121-492b-93f1-1cbdd3a9687a.png)

Ideally the FAQ would also provide some background on the impact of censorship on the blockchain; why it's done, and why it matters.

**Comment by hunicus** [comment]
> Problem to be solved
>
> The colors in the blocks seemed interesting, but it was hard to figure out what they meant.

#3045 addresses this and is now live.
