### ISSUE TITLE
Latest blocks and Adjustments UI is not aligned anymore

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#3034]
Note the two widgets at the bottom are not the same height. Seems like we had a regression on the UI. I don't remember seeing this before.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/9780671/218309966-c5ffad8d-14e5-4b06-a020-26c2207e313a.png">

<img width="792" alt="image" src="https://user-images.githubusercontent.com/9780671/218314848-44243fd5-b179-4129-ad8f-ae883a467330.png">

**Comment by softsimon** [comment]
I don't understand. Why would the difficulty adjustment block heights be the same as the latest blocks.
