### ISSUE TITLE
Suggestion: Always visible BTC/fiat toggle in header bar.

### ISSUE THREAD

**Issue by wonder75** [mempool/mempool#3046]
Would be nice to be able to choose between BTC or FIAT values on every page when rates are available.

Some pages allow it like the info page for a single block. The toggle is hard to find though.
Others don't have a button to toggle like the latest blocks list for example.

One button to switch currency on the header bar might be a nice improvement.

**Comment by wiz** [comment]
I don't understand what you mean - AFAIK we display both bitcoin and fiat prices on all pages except the TX page, which you can toggle by pressing the blue button with the amount in it?

**Comment by wiz** [comment]
Ah I found one place, on the lightning dashboard

**Comment by wiz** [comment]
@nymkappa as we discussed, how about we modify the lightning dashboard to show fiat values instead of percentage change?
