### ISSUE TITLE
Clarify electrs usage

### ISSUE THREAD

**Issue by dennisreimann** [mempool/mempool#32]
I'm trying to set up this project on my own node (so thanks for this nice interface btw!). Currently I'm struggling to find out how electrs is involved here. Is it a dependency which I need to run myself or do I link to the Blockstream Esplora API for that? The README doesn't contain that information, but the config file and nginx setup configure things regarding that – thanks for any kind of guidance on how to get this going!

**Comment by wiz** [comment]
Hey @dennisreimann, yeah we need to update our README docs on the master branch. I think what you are looking for is the https://github.com/mempool-space/mempool.space/tree/v1.0.0 release tag which can be used with either bitcoind or electrs. If you follow the docs there I think it will make more sense 😅

**Comment by dennisreimann** [comment]
Awesome, thanks – got it working now 👌

Unrelated question: Do you think about shipping releases via npm so that installation and maintenance could be easier? (imho doing something like `npm install -g mempool-space` and shipping a prebuild version would be better and more reliable than using git and creating the build locally).

**Comment by wiz** [comment]
Yes, we will ship it as an npm module in the v2 release
