### ISSUE TITLE
Add support for Signet

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#328]
`Run bitcoind with the -signet flag to use the default global signet (or put signet=1 in the bitcoin.conf file).`

- [x] Run Signet node
- [x] Configure nginx to handle the new signet network
- [x] Add Signet as a new network along with a signet icon in the dropdown (frontend)

**Comment by 7hacker** [comment]
hi @softsimon , I noticed Signet is already configured at mempoo.space but I'm curious how to turn it on for a signet cluster running on my computer (localhost: 127.0.0.1:38332). Any tips?

**Comment by wiz** [comment]
We are currently waiting for @shesek to release an update of @blockstream/electrs with signet support - after that we can add instructions on how to self-host mempool for signet
