### ISSUE TITLE
Add support for getting raw tx

### ISSUE THREAD

**Issue by s-5Q2X8mgeGR** [mempool/mempool#329]
As the title says: It'd be neat to be able to get the raw tx (and perhaps decoded in json too). 

Many use cases to mention as for why: 
- users not running their own nodes, ability to get the raw tx to rebroadcast later in case it gets dropped
- if mempool is flooded enough so you cannot broadcast a newly received tx bc all the parents arent already in your mempool, and thus would need to first broadcast the parents to your own mempool, before possible to broadcast the newly-receiced tx to your own mempool, and thus have it show up in transactions/activity 

Blockchair offers raw tx + decoded in json for any tx. Not sure what other block explorers does as well, but don't think that many do. 

Perhaps could be accessed via clicking a small Raw tx button in the end of the Details section

**Comment by softsimon** [comment]
It now exists a Transaction Hex link on Transaction page details to get the transaction HEX.
