### ISSUE TITLE
Confirmations incorrect on coinbase of latest Block

### ISSUE THREAD

**Issue by sjorsvanheuveln** [mempool/mempool#3294]
### Description

If you inspect the Actual Block's coinbase of the latest block. It has more than 1 confirmation. Also, with new blocks I observe the latest block's coinbase has multiple confirmations, where it should only be 1.

#### Version

2.5.0

### Screenshots

https://nostr.build/i/nostr.build_28b26cbd6851489e5b32e12bf92cd7634882acd02d3fad3dd0095ec973e8d021.png

#### Device or machine

Mac OS 12.6.3

**Comment by nymkappa** [comment]
Thanks. We've also noticed this issue and we'll fix it before the next release.

**Comment by softsimon** [comment]
Is there a way to reproduce this?

**Comment by nymkappa** [comment]
- Open mempool.space
- Start tracking a tx that will most likely be included in the next block
- Wait for **two** confirmations
- Press the back button of the web browser
- Press the forward button of the web browser
- Arrow points to the wrong block
