### ISSUE TITLE
Show cumulated stats on last mempool block

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#3357]
The last mempool block display inconsistent data.

We should always show cumulated stats on the last mempool block page.

![3E720309-9492-47CF-953B-B857B6921704](https://user-images.githubusercontent.com/9780671/224696577-47b00841-1462-4c09-9a08-8d7521bba521.jpeg)

![F9A923F2-C567-469E-858B-75F8495BDC46](https://user-images.githubusercontent.com/9780671/224695985-247a947f-86b0-4e4d-8b64-0ddd9511a63f.jpeg)

**Comment by antonilol** [comment]
related: #1775

**Comment by nymkappa** [comment]
Already fixed https://mempool.space/mempool-block/7
