### ISSUE TITLE
Overflow when switching to french

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#3358]
![50DDDBEB-25F1-43BB-84EA-B73A5B7B5DE9](https://user-images.githubusercontent.com/9780671/224708709-dbce626f-8122-4e81-8cc9-4f92a43b9668.png)

**Comment by softsimon** [comment]
So shorten the word Recompense :P

**Comment by nymkappa** [comment]
Updated the PR


https://user-images.githubusercontent.com/9780671/226156826-f3290bd5-80b2-4aa6-b6d5-7f890ccce7ce.mov
