### ISSUE TITLE
Bug: Graph grows too fast on monthly view

### ISSUE THREAD

**Issue by thorie7912** [mempool/mempool#337]
### Description

If you leave the browser on the monthly graph view, it will slowly move faster than necessary, and result in an incorrect display.

#### Version

Not sure

### Steps to reproduce

Load the monthly graph and wait 30 minutes, 1 hour, maybe longer... gradually you will see it.

### Expected behaviour

Shouldn't update the monthly graph so quickly

### Actual behaviour

Graph updates quickly and shows too many new values and thus not accurate anymore.

### Screenshots

![Screenshot from 2021-02-12 19-47-09](https://user-images.githubusercontent.com/869094/107840951-a4475a80-6d6b-11eb-8ca3-c82e3f8ac456.png)

This screenshot (ABOVE) is what the monthly chart looks like after leaving the page open for a few hours. The right side of the graph has a kind of "smothered linear data set". If you refresh, you immediately get a much different graph (BELOW) where the right side is back to the normal "spikey data set".

![Screenshot from 2021-02-12 19-51-38](https://user-images.githubusercontent.com/869094/107840966-c2ad5600-6d6b-11eb-8a3c-7430ad5f271a.png)

#### Device or machine

Linux, Chrome

* Note, I haven't tested any of the other time periods. They may or may not have the same issue.

**Comment by softsimon** [comment]
Interesting. The monthly graph shouldn't auto update at all

**Comment by softsimon** [comment]
Closing as this is not something we've seen or anyone else reported.
