### ISSUE TITLE
Can't start backend due to 'Javascript heap out of memory'

### ISSUE THREAD

**Issue by sangaman** [mempool/mempool#339]
### Description

I'm following the manual installation instructions but can't start the backend due to js heap memory errors. I suspect my device (specs at bottom of issue) doesn't meet the requirements for mempool.space, but I couldn't find any system requirements listed. Electrumx and bitcoind are running on another machine on the LAN.

#### Version

52a1425498c2b68a967a40a948230f5a86ae99ff

### Steps to reproduce

Manual installation instructions on a device with specs listed at the bottom of this issue.

### Expected behaviour

Backend starts.

### Actual behaviour

```
฿ npm start

> mempool-backend@2.0.0 start
> node --max-old-space-size=4096 dist/index.js


<--- Last few GCs --->

[18938:0x3834588]      233 ms: Mark-sweep 0.9 (2.2) -> 0.9 (2.2) MB, 13.8 / 0.0 ms  (average mu = 0.385, current mu = 0.125) allocation failure GC in old space requested
[18938:0x3834588]      247 ms: Mark-sweep 0.9 (2.2) -> 0.9 (2.2) MB, 10.6 / 0.0 ms  (average mu = 0.331, current mu = 0.243) allocation failure GC in old space requested
[18938:0x3834588]      265 ms: Mark-sweep 0.9 (2.2) -> 0.9 (2.2) MB, 14.0 / 0.0 ms  (average mu = 0.271, current mu = 0.208) allocation failure GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
Aborted
npm ERR! code 134
npm ERR! path /home/bitcoin/mempool/backend
npm ERR! command failed
npm ERR! command sh -c node --max-old-space-size=4096 dist/index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitcoin/.npm/_logs/2021-02-13T17_30_08_321Z-debug.log
```

#### Device or machine

ODROID HC1 w/ 2 GB RAM and 4 GB swap, arm7l. Ubuntu 18.04. Node v14.15.1

**Comment by wiz** [comment]
Unfortunately, 2GB is probably not enough RAM to run mempool v2 without further work to optimize the memory utilization. However, as a temporary workaround, you can try changing the `--max-old-space-size=4096` in `backend/package.json` to `2048` or even `1024` and see if it runs. Disabling the disk cache might also be needed, but I don't think there is an easy way to disable that in the code.

**Comment by wiz** [comment]
Simon just optimized the memory usage in the mempool backend, so if you upgrade to the latest master commit, you should be able to run it with `--max-old-space-size=1024` - please try it and let us know how it works

**Comment by wiz** [comment]
Okay, we did lots of testing and confirmed a 2G heap size limit is safe for the newly optimized mempool backend, so we've also gone ahead and reduced the default heap size limit to 2G. Please just try the latest master as-is and it should hopefully work for you now 😅

**Comment by sangaman** [comment]
So far so good on 2743b35ea2033ef44a37713776a8e68bb0cbc00c. I'll continue through the rest of the setup process and close this issue if javascript heap errors don't resurface. Thank you!
