### ISSUE TITLE
"Lightning" Tab Not Appearing

### ISSUE THREAD

**Issue by TheFockinFury** [mempool/mempool#3409]
### Description

I'm deploying Mempool on a LND node that roughly matches the [Raspibolt](https://raspibolt.org/guide/lightning/lightning-client.html) stack. I've configured it to display Lightning Network stats, but the "Lightning" tab is not appearing in the top nav as it does on the version hosted on mempool.space.

#### Version

v2.4.0

### Steps to reproduce

1. Deploy mempool following the [docker](https://github.com/mempool/mempool/tree/master/docker) instructions
2. Navigate to the instance on the web

### Expected behaviour

I see the "Lightning" tab in the top nav and am able to view lightning network stats

### Actual behaviour

"Lightning" tab is not shown; when navigating directly to /lightning, the page loads but stats are incomplete

### Screenshots

I'm currently hosting this mempool instance at https://mempool.thefockinfury.wtf 

#### Device or machine

Raspibolt stack running on Ubuntu 22.04 virtual machine running inside of Proxmox

#### Additional info

Logs from the api container show nothing compelling in the way of errors, though it's interesting that I can't connect to github or kraken. I am able to CURL those URLs from inside the container:
```
Mar 16 21:35:22 [103] NOTICE: <lightning> Starting Mempool Server... (5361148)
Mar 16 21:35:22 [103] INFO: <lightning> Connected to Electrum Server at host.docker.internal:50002 (["electrs/0.9.11","1.4"])
Mar 16 21:35:22 [103] INFO: <lightning> Database connection established.
Mar 16 21:35:22 [103] INFO: <lightning> [Mining] Downloading pools-v2.json for the first time from https://raw.githubusercontent.com/mempool/mining-pools/master/pools-v2.json over clearnet
Mar 16 21:35:32 [103] ERR: <lightning> Could not connect to Github. Reason: timeout of 10000ms exceeded
Mar 16 21:35:32 [103] INFO: <lightning> Restoring mempool and blocks data from disk cache
Mar 16 21:35:33 [103] INFO: <lightning> Starting statistics service
Mar 16 21:35:33 [103] NOTICE: <lightning> Mempool Server is running on port 8999
Mar 16 21:35:33 [103] INFO: <lightning> [Lightning] Starting lightning network sync service
Mar 16 21:35:34 [103] INFO: <lightning> [Mining] Cannot save block price for 781105 because the price updater hasnt completed yet. Trying again in 10 seconds.
Mar 16 21:35:40 [103] INFO: <lightning> Core index 'txindex' is synced. Best block height is 781105
Mar 16 21:35:57 [103] INFO: <lightning> [Mining] Fetching daily price history from exchanges and saving missing ones into the database
Mar 16 21:35:59 [103] INFO: <lightning> [Lightning] Starting closed channels scan for the first time
Mar 16 21:36:04 [103] INFO: <lightning> [Lightning] Checking if channel has been closed 12002/63904
Mar 16 21:36:19 [103] WARN: <lightning> Could not connect to https://api.kraken.com/0/public/OHLC?interval=60&pair=XBTAUD (Attempt 1/1). Reason: timeout of 10000ms exceeded
Mar 16 21:36:19 [103] ERR: <lightning> Could not connect to https://api.kraken.com/0/public/OHLC?interval=60&pair=XBTAUD. All 1 attempts failed
Mar 16 21:36:21 [103] INFO: <lightning> [Lightning] Starting Lightning Stats service
Mar 16 21:36:22 [103] NOTICE: <lightning> The mempool is now in sync!
Mar 16 21:36:29 [103] WARN: <lightning> Could not connect to https://api.kraken.com/0/public/OHLC?interval=60&pair=XBTJPY (Attempt 1/1). Reason: timeout of 10000ms exceeded
Mar 16 21:36:29 [103] ERR: <lightning> Could not connect to https://api.kraken.com/0/public/OHLC?interval=60&pair=XBTJPY. All 1 attempts failed
Mar 16 21:36:41 [103] INFO: <lightning> Starting lightning network forensics service
Mar 16 21:36:41 [103] INFO: <lightning> Running forensics scans
Mar 16 21:36:41 [103] INFO: <lightning> [Lightning] Caching funding txs for currently existing channels
Mar 16 21:36:41 [103] INFO: <lightning> Lightning topology folder is not set. Not importing historical LN stats
Mar 16 21:36:46 [103] NOTICE: <lightning> [Mining] Inserted 107 daily historical prices into the db
Mar 16 21:36:46 [103] INFO: <lightning> [Mining] Fetching hourly price history from exchanges and saving missing ones into the database
Mar 16 21:37:00 [103] WARN: <lightning> Could not connect to https://api.kraken.com/0/public/OHLC?interval=60&pair=XBTEUR (Attempt 1/1). Reason: timeout of 10000ms exceeded
Mar 16 21:37:00 [103] ERR: <lightning> Could not connect to https://api.kraken.com/0/public/OHLC?interval=60&pair=XBTEUR. All 1 attempts failed
Mar 16 21:37:13 [103] WARN: <lightning> Could not connect to https://api.kraken.com/0/public/OHLC?interval=60&pair=XBTCAD (Attempt 1/1). Reason: timeout of 10000ms exceeded
Mar 16 21:37:13 [103] ERR: <lightning> Could not connect to https://api.kraken.com/0/public/OHLC?interval=60&pair=XBTCAD. All 1 attempts failed
```

Docker-compose.yml. Note, the networking stuff at the bottom is just to ensure my container can get a predictable IP range that I can in turn add as a `tlsextraip` in `lnd.conf`. 
```
version: "3.7"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    networks:
      - default
    user: "0:0"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 4080:8080
  api:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/home/lnd/.lnd:/lnd:ro'
      - 'mp-data:/backend/cache'
    environment:
      ELECTRUM_HOST: "host.docker.internal"
      ELECTRUM_PORT: "50002" 
      ELECTRUM_TLS_ENABLED: "true"
      MEMPOOL_BACKEND: "electrum"
      CORE_RPC_HOST: "host.docker.internal"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "user"
      CORE_RPC_PASSWORD: "password"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
      STATISTICS_TX_PER_SECOND_SAMPLE_PERIOD: 150
      LIGHTNING_ENABLED: "true"
      LIGHTNING_BACKEND: "lnd"
      LIGHTNING_TOPOLOGY_FOLDER: ""
      LIGHTNING_STATS_REFRESH_INTERVAL: 600
      LIGHTNING_GRAPH_REFRESH_INTERVAL: 600
      LIGHTNING_LOGGER_UPDATE_INTERVAL: 30
      LND_TLS_CERT_PATH: "/lnd/tls.cert"
      LND_MACAROON_PATH: "/lnd/data/chain/bitcoin/mainnet/admin.macaroon"
      LND_REST_API_URL: "https://host.docker.internal:8080"
    image: mempool/backend:latest
    user: "0:0"
    networks:
      - default
    restart: always
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
      
  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    user: "0:0"
    restart: always
    stop_grace_period: 1m
    networks:
      - default
    volumes:
      - mp-mysql:/var/lib/mysql
      #- ./mysql/data:/var/lib/mysql
      
volumes:
  mp-mysql:
  mp-data:
  mp-lnd:
  
networks:
  default:
    name: 'mempool'
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1
```

**Comment by wiz** [comment]
need to set LIGHTNING to true in frontend config, I believe @knorrium added a Docker variable for this

**Comment by Sjors** [comment]
TIL this was already included in v2.4.0… Trying on v2.5.0beta1 now though!

**Comment by TheFockinFury** [comment]
I'm going to go ahead and close this issue since it seems (based on discussion above and in the elements support channel) that an upcoming release will enable the lightning config on the docker deployment. 

Errors I'm getting about "could not connect to ..." are unrelated and are likely due to a DNS issue with my Wireguard tunnel that I need to dig into separately. 

Thanks for jumping on this!

**Comment by aphex3k** [comment]
I have the same issue

> "Lightning" tab is not shown; when navigating directly to /lightning, the page loads

```
    environment:
      LIGHTNING_ENABLED: "true"
```

I set that for the frontend docker container.

**Comment by chuegel** [comment]
same here with version v2.5.0

**Comment by nclgvnzz** [comment]
@TheFockinFury @aphex3k I believe the LIGHTNING_ENABLED: "true" you are both referring to is related to the backend.

As @wiz stated, the reason why the Lightning Network icon is not displayed in the header of our self-hosted Mempool installations is that the **mempool-frontend-config.sample.json** in the **frontend** folder has the parameter LIGHTNING set to "false" by default.

I am not using Docker but I guess you should have the **mempool-frontend-config.sample.json** in the frontend folder as well. This is what worked for me:

1) I created a copy of **mempool-frontend-config.sample.json** and call it **mempool-frontend-config.json**. NOTE: This step is not specified in the installation instructions for the frontend but **npm run build** will look for a config file with that specific name and, if it doesn't exist, a default configuration will be used.

2) I edited the **mempool-frontend-config.json** and set the LIGHTNING variable to true

3) I run **npm run build** inside the **frontend** directory

And here it is, the Lightning Network icon between the mining and the graphs icons.

![Screen Shot 2023-05-21 at 21 28 38](https://github.com/mempool/mempool/assets/133590254/ff871be6-e18d-4a7b-ad40-070e58b7f748)

**Comment by aphex3k** [comment]
The documentation provided by mempool team read that you can set environment variables and could enable lighting without rebuilding containers and use the officially provided containers instead.

**Comment by nclgvnzz** [comment]
> The documentation provided by mempool team read that you can set environment variables and could enable lighting without rebuilding containers and use the officially provided containers instead.

As mentioned in my previous comment, I didn't use Docker to install Mempool on my machine so I don't know what Docker does in the background while building Mempool but I got curious and wanted to understand why you guys don't have the Lightning tab. I checked /var/www/mempool/browser/resources on my machine and I noticed that there's a config.js file that looks like this:

> (function (window) {
>   window.__env = window.__env || {};
>     window.__env.TESTNET_ENABLED = false;
>     window.__env.SIGNET_ENABLED = false;
>     window.__env.LIQUID_ENABLED = false;
>     window.__env.LIQUID_TESTNET_ENABLED = false;
>     window.__env.BISQ_ENABLED = false;
>     window.__env.BISQ_SEPARATE_BACKEND = false;
>     window.__env.ITEMS_PER_PAGE = 10;
>     window.__env.KEEP_BLOCKS_AMOUNT = 8;
>     window.__env.NGINX_PROTOCOL = 'http';
>     window.__env.NGINX_HOSTNAME = '127.0.0.1';
>     window.__env.NGINX_PORT = '80';
>     window.__env.BLOCK_WEIGHT_UNITS = 4000000;
>     window.__env.MEMPOOL_BLOCKS_AMOUNT = 8;
>     window.__env.BASE_MODULE = 'mempool';
>     window.__env.MEMPOOL_WEBSITE_URL = 'https://mempool.space';
>     window.__env.LIQUID_WEBSITE_URL = 'https://liquid.network';
>     window.__env.BISQ_WEBSITE_URL = 'https://bisq.markets';
>     window.__env.MINING_DASHBOARD = true;
>     window.__env.AUDIT = false;
>     window.__env.MAINNET_BLOCK_AUDIT_START_HEIGHT = 0;
>     window.__env.TESTNET_BLOCK_AUDIT_START_HEIGHT = 0;
>     window.__env.SIGNET_BLOCK_AUDIT_START_HEIGHT = 0;
>     window.__env.LIGHTNING = true;
>     window.__env.HISTORICAL_PRICE = true;
>     window.__env.GIT_COMMIT_HASH = '57eddac7';
>     window.__env.PACKAGE_JSON_VERSION = '2.5.0';
>   }(this));

I believe you should have this file on your machine as well after building Mempool via Docker. Maybe check if the **window.__env.LIGHTNING** variable is set to true?

For testing purposes, I set **window.__env.LIGHTNING** to false and restarted the Mempool service to see if the Lightning tab would disappear and it disappeared indeed:

![Screenshot 2023-05-22 at 12 58 12](https://github.com/mempool/mempool/assets/133590254/de1396db-612d-47f1-bcb0-05756563000f)

Then I set **window.__env.LIGHTNING** to true once again, restarted the Mempool service and the Lightning tab was back:

![Screenshot 2023-05-22 at 13 00 06](https://github.com/mempool/mempool/assets/133590254/4d8df502-2aeb-4243-bbf1-c7da5a43b9ac)

Maybe this is what you guys need to do without rebuilding containers.

**Comment by chuegel** [comment]
The corresponding ENV are described here: https://github.com/mempool/mempool/tree/master/docker
In my case:

```sh

api:
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "xxxx"
      ELECTRUM_PORT: "50002"
      ELECTRUM_TLS_ENABLED: "true"
      CORE_RPC_HOST: "xxxx"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "user"
      CORE_RPC_PASSWORD: "xxxxx"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "xxxx"
      STATISTICS_ENABLED: "true"
      LIGHTNING_ENABLED: "true"
      LIGHTNING_BACKEND: "lnd"
      LIGHTNING_STATS_REFRESH_INTERVAL: 600
      LIGHTNING_GRAPH_REFRESH_INTERVAL: 600
      LIGHTNING_LOGGER_UPDATE_INTERVAL: 30
      LIGHTNING_TOPOLOGY_FOLDER: "/lnd_topology"
      LND_TLS_CERT_PATH: "/lnd/tls.cert"
      LND_MACAROON_PATH: "/lnd/data/chain/bitcoin/mainnet/admin.macaroon"
      LND_REST_API_URL: "https://xxxx:8080"
      LND_TIMEOUT: 10000
````
but still...the icon doesn't appear.

**Comment by chuegel** [comment]
I gave it another try and looked into the docker container.  Despite having the env vars set in `docker-compose.yml`
the `config.js`file inside container shows that the variables are not set:

```sh
    'LIGHTNING': {
        'ENABLED': false,
        'BACKEND': 'lnd',
        'TOPOLOGY_FOLDER': '',
        'STATS_REFRESH_INTERVAL': 600,
        'GRAPH_REFRESH_INTERVAL': 600,
        'LOGGER_UPDATE_INTERVAL': 30,
        'FORENSICS_INTERVAL': 43200,
        'FORENSICS_RATE_LIMIT': 20,
    },
    'LND': {
        'TLS_CERT_PATH': '',
        'MACAROON_PATH': '',
        'REST_API_URL': 'https://localhost:8080',
        'TIMEOUT': 10000,
    },
```
However, the `mempool-config.json` file inside the container contains the correct envs:
```sh
  "LIGHTNING": {
    "ENABLED": true,
    "BACKEND": "lnd",
    "STATS_REFRESH_INTERVAL": 600,
    "GRAPH_REFRESH_INTERVAL": 600,
    "LOGGER_UPDATE_INTERVAL": 30,
    "TOPOLOGY_FOLDER": "/lnd_topology"
  },
  "LND": {
    "TLS_CERT_PATH": "/lnd/tls.cert",
    "MACAROON_PATH": "/lnd/data/chain/bitcoin/mainnet/admin.macaroon",
    "REST_API_URL": "https://xxxx:8080",
    "TIMEOUT": "10000"
  },

```

So I'm not quite sure whats happening here.

**Comment by nclgvnzz** [comment]
@chuegel I was about to reply to your second last message just to point out that you were still looking into the backend configuration and then I received the notification with your last message confirming that you enabled the Lightning icon in the frontend which is what needed to be done.

**Comment by wizard872** [comment]
services:
  web:
    environment:
      LIGHTNING: "true"

it works to me!

i can show lightning tab now
