### ISSUE TITLE
difficulty adjustment widget shows random values while syncing

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#3414]
Restart backend a few times and you'll see weird stuff

<img width="1238" alt="Screenshot 2023-03-17 at 20 22 00" src="https://user-images.githubusercontent.com/232186/225892957-e8000a3d-761c-4f14-843d-097bd8ffe041.png">
<img width="554" alt="Screenshot 2023-03-17 at 20 30 48" src="https://user-images.githubusercontent.com/232186/225892969-45b7f7fa-92b5-4895-ae74-8edd796d5e1b.png">

**Comment by nymkappa** [comment]
Could also be related to https://github.com/mempool/mempool/issues/2016
