### ISSUE TITLE
blockchain blocks sometimes disappear while restarting backend

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#3415]
<img width="1272" alt="Screenshot 2023-03-17 at 20 50 35" src="https://user-images.githubusercontent.com/232186/225896785-6448cca0-2f53-45df-8baa-1f3c23edb61b.png">

**Comment by softsimon** [comment]
Possibly fixed in https://github.com/mempool/mempool/pull/3578 ?  But maybe not..
