### ISSUE TITLE
Lack of CPFP calculation enables potential manipulation of fee estimates to high values

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#353]
### Description

Due to a lack of CPFP calculation in the mempool backend, it might be possible for someone to manipulate the mempool backend fee estimates very high

#### Version

v2.1.2

### Steps to reproduce

1) Create a very huge low fee transaction and intentionally get it stuck in the mempool
2) CPFP the above transaction with a very high fee, say 9000 sats/vByte
3) Because the parent TX is so large, this still isn't enough to raise the average fee for the unconfirmed mempool chain high enough so that the chain gets mined into a block
3) Repeat this over and over until you have hundreds and hundreds of 9000 sats/vByte transactions stuck in the mempool

### Expected behaviour

Fee estimation is not affected by this manipulation

### Actual behaviour

Due to the lack of CPFP average fee calculation in the mempool backend, and the way that the mempool backend suggests fees to users using the median fee in the next projected block, the fee estimates could be manipulated much higher by a malicious person

**Comment by wiz** [comment]
Seems it's already causing weird issues, even unintentionally

<img width="540" alt="Screen Shot 2021-02-23 at 1 34 26" src="https://user-images.githubusercontent.com/232186/108738892-6a4e3380-7577-11eb-95b8-bbf051721948.png">

**Comment by andrewtoth** [comment]
Hi, please let me know if this is a good solution and whether this makes sense. Transactions are ordered by fee per vsize. Would the solution instead be to order using `fees.ancestor/ancestorsize` from `getmempoolentry` response?

**Comment by wiz** [comment]
Unfortunately, using Bitcoin Core RPC is too slow
