### ISSUE TITLE
Minor graph bug: Last color filter on chart doesn't match the peg

### ISSUE THREAD

**Issue by thorie7912** [mempool/mempool#356]
### Description

If you go through and click on each color box, the corresponding chart color matches the remaining unchecked colors. Until, the very last one. The last unchecked color doesn't match between the checkbox and the graph.

### Steps to reproduce

Check each color one by one until the end. The last color doesn't match the graph.

### Expected behaviour

Should match.

### Actual behaviour

Doesn't match.

### Screenshots

Good
![Screenshot from 2021-02-23 16-32-34](https://user-images.githubusercontent.com/869094/108927422-1bdf7a00-75f5-11eb-8b7f-343265b1d2c0.png)

Good
![Screenshot from 2021-02-23 16-32-40](https://user-images.githubusercontent.com/869094/108927431-20a42e00-75f5-11eb-8ef6-a6d677c73315.png)

Wrong Color
![Screenshot from 2021-02-23 16-32-47](https://user-images.githubusercontent.com/869094/108927443-2437b500-75f5-11eb-9bb7-7ea9f0beadd6.png)

#### Device or machine

Chrome

**Comment by jambolo** [comment]
Dup of #283

**Comment by thorie7912** [comment]
Closed as dup
