### ISSUE TITLE
Difficulty adjustment API should not send `0` for the first 146 blocks of the currenty difficulty epoch

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#3565]
Issue time: block 782279

# Problem

Difficulty adjustment is not yet calculated because it's too early to display (too volatile). While the frontend properly handles this, the backend does not.

The websocket sends:

```
  ...
  "da": {
    "progressPercent": 3.4722222222222223,
    "difficultyChange": 0,
    ...
```

The REST API sends:

```
nymkappa @ /Users/nymkappa $ curl -s "http://localhost:8999/api/v1/difficulty-adjustment" | jq
{
  "progressPercent": 3.5218253968253967,
  "difficultyChange": 0,
  ...
}
```

# Solutions

- Send `null` (opiniated since we decide that the value is probably wrong and do not want to serve it). This means we change the API response format (breaking change afaik)
OR
- Send the actual value after the first block (neutral but can fluctuate by a lot). No API changes.

@softsimon @wiz feedback welcome on this before implementation of a fix

**Comment by softsimon** [comment]
I am in the opinion that the REST API shouldn't make "opinions" on how many blocks it should wait until the data is accurate. The API should always send the difficultyChange.

The frontend on the other hand should keep the current < 24h show dash-logic

**Comment by softsimon** [comment]
fixed in https://github.com/mempool/mempool/pull/3576
