### ISSUE TITLE
Percentage change malpositioned using RTL

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#3583]
As reported by one of our RTL language translator, the + change should be on the left side

<img width="266" alt="Screenshot 2023-03-27 at 16 22 09" src="https://user-images.githubusercontent.com/8561090/227869290-5fa63f6e-7490-4e9a-a933-21832900e353.png">

**Comment by wiz** [comment]
is @TechMiX available for this?

**Comment by TechMiX** [comment]
I can look into it.
