### ISSUE TITLE
What is the time range of "Average block time" ?

### ISSUE THREAD

**Issue by nostitos** [mempool/mempool#3715]
Something feels wrong when the average is above 10, we're 24h away from an adjusment, 40 blocks behind and expecting -2.7% .

![image](https://user-images.githubusercontent.com/48504624/235976710-f45e2ad3-d730-41eb-86ae-f5bebb4923dd.png)

**Comment by mononaut** [comment]
"Average block time" is the average over the entire difficulty epoch so far (i.e. the last 1872 blocks, at the time of writing)

So the numbers do appear to line up correctly:
 - ~10.2 minute average block time is ~2% higher than the 10 minute target.
 - expected adjustment is ~2% down.
 - 40 blocks behind is ~2% of the target number of blocks.
 - we expect the remaining 144 blocks in this epoch to take `144 × 10.2 mins = 24.5 hrs`, so the next difficulty adjustment will happen about this time tomorrow.

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/236217823-2ea9b66c-020d-443f-936d-dde7b935f250.png)

Only 2h left, If difficulty is going down it mean we were ~2% slower than 10min on average but average still show us above average.

**Comment by mononaut** [comment]
A *higher* average block time means blocks were mined *slower* than expected, which is consistent with the predicted reduction in difficulty.

**Comment by Transisto** [comment]
🤦‍♂️

**Comment by nostitos** [comment]
🤦‍♂️
