### ISSUE TITLE
Also draw horizontal line on /graphs/mempool

### ISSUE THREAD

**Issue by AbelLykens** [mempool/mempool#3747]
### Description

![image](https://github.com/mempool/mempool/assets/47113175/397830a4-291e-4550-bd87-e988dea42bd6)

It's not easy to read y axis and not easy to compare old days, 
Please also draw a horizontal line (like the vertical line) on hover, so comparing is easier and reading the y axis is easier.

**Comment by Lepart23** [comment]
> ### Description
> 
> 
> 
> ![image](https://github.com/mempool/mempool/assets/47113175/397830a4-291e-4550-bd87-e988dea42bd6)
> 
> 
> 
> It's not easy to read y axis and not easy to compare old days, 
> 
> Please also draw a horizontal line (like the vertical line) on hover, so comparing is easier and reading the y axis is easier.
> 
>
