### ISSUE TITLE
Feerate filter isn't working

### ISSUE THREAD

**Issue by feelancer21** [mempool/mempool#3769]
### Description

On mempool.space the filter by the mempool feerates isn't working at the moment. 

#### Version

node206.fra.mempool.space (v2.6.0-dev) [[97c8ace8](https://github.com/mempool/mempool/commit/97c8ace8)]

**Comment by nymkappa** [comment]
@mononaut I think you broke it 5257716e1a528f3e1b959ecc6ad90ab87a999e64 can you confirm?
