### ISSUE TITLE
CPFC tagged transactions with wrong descendant and ascendant transactions

### ISSUE THREAD

**Issue by yahiheb** [mempool/mempool#3777]
Descendant and ascendant transactions are sometimes messed up for CPFC tagged transactions. I have noticed that mainly for coinjoin transactions.

Example:
 https://mempool.space/tx/b94294123adfd7179317eade4d010a24bf148434a3cfe586030b21c1e793b3a1

1. It shows this [CJ TX](https://mempool.space/tx/3eb8c8e60e89ba09a009b3f0002c60384577df33f1e40087063bd2fcfff00dc9) as descendant which is wrong.
2. It doesn't show these 2 direct descendants:
   - https://mempool.space/tx/85eac257958e3fddf197437cb409a7491d72351b5316dfeda54975546bd1f992
   - https://mempool.space/tx/75d7dcd5a6c82ab7a7792bd74316fe97fcc20319880a690fb6f7bd77b1690d3e

**Comment by mononaut** [comment]
We identify CPFP relationships in mined blocks using a heuristic that assumes the block was constructed using Bitcoin Core's `getBlockTemplate` algorithm.

Core's algorithm greedily selects "packages" of related transactions sponsored by a single CPFP "root" transaction. (technically speaking, each package forms a disjoint rooted directed acyclic graph).

The list of ancestors/descendants displayed under the CPFP toggle is strictly limited to transactions in the same CPFP package.

This has two effects which produce the results you've noticed:

1. CPFP relationships within a package can be more complex than just "ancestors" and "descendants". Two transactions in the same package might actually be "siblings" or "cousins" or have some other complex relationship that becomes awkward to describe using family tree terminology.
    - To simplify data and UI requirements, we label all CPFP relationships as either "ancestor" or "descendant" based on simple order of inclusion in the block. This produces correct labels in most cases, but can be misleading for indirectly related transactions.
2. Each package can only be sponsored by one root transaction. This means direct descendants of some transactions may not be included in the CPFP package or contribute to the final effective fee rate.

In your example, the full CPFP graph identified by our heuristic looks like this:

<img width="339" alt="Screenshot 2023-05-15 at 1 22 39 PM" src="https://github.com/mempool/mempool/assets/83316221/8786c2d1-bbe3-415c-a06d-1b0e7efb15dd">

so transactions [`b942`](https://mempool.space/tx/b94294123adfd7179317eade4d010a24bf148434a3cfe586030b21c1e793b3a1) and [`3eb8`](https://mempool.space/tx/3eb8c8e60e89ba09a009b3f0002c60384577df33f1e40087063bd2fcfff00dc9) are not directly related, but both belong to a CPFP package ultimately sponsored by [`b189`](https://mempool.space/tx/b189d09d3b8c2cacbcf7befd79dcd30fd885d202a704f819fde06912b81f126d).
