### ISSUE TITLE
Expose RBF transaction history via API

### ISSUE THREAD

**Issue by BullishNode** [mempool/mempool#3779]
It would be very useful for a service to be able to expose RBF history to its end user. That service could be a wallet, or an exchange. It may be difficult for them to reproduce the RBF history logs that Mempool produces, so exposing it via API would make it possible for them to have all the info the need, and then they just display it properly.

**Comment by softsimon** [comment]
You mean like this?

[https://mempool.space/api/v1/tx/3988bc10e20a41b096018ab8fd6cdf167202e89d3afdf24f5a30706588eb78f2/rbf](https://mempool.space/api/v1/tx/3988bc10e20a41b096018ab8fd6cdf167202e89d3afdf24f5a30706588eb78f2/rbf)

**Comment by BullishNode** [comment]
Yes! fantastic. I assume you mean 24h after the last transaction is confirmed? Thanks very much for sharing.
