### ISSUE TITLE
Unknown block should be tagged to F2Pool?

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#3782]
https://mempool.space/block/00000000000000000001aadcd2ac42e0fabcc46b9a2d2150963d4c594f22e294

**Comment by softsimon** [comment]
In this block they added an extra output that might have screwed with the output address detection. And the fish emoji detection isn't being used/working.

**Comment by nymkappa** [comment]
Ah yes I think the current code assume the miner uses the first output

**Comment by nymkappa** [comment]
More of those, so that's something we need to fix

<img width="808" alt="image" src="https://github.com/mempool/mempool/assets/9780671/4486581f-739e-42b4-8bb8-f9261c2e4611">

**Comment by nymkappa** [comment]
@softsimon do you want to take look?
