### ISSUE TITLE
 mempool/docker/README.md change from ELECTRUM_HOST to ELECTRS_HOST

### ISSUE THREAD

**Issue by JavierRSobrino** [mempool/mempool#379]
### Description

I wasn't able to make the docker running, and that was related to ELECTRUM_HOST and ELECTRUM_PORT environment variables, which apparently changed to ELECTRS_HOST and ELECTRS_PORT.

Please change that in the documentation.

**Comment by wiz** [comment]
Actually it's the other way around, everything was changed to ELECTRUM for consistency, but it's only on master and you're running an older version - so this should be "fixed" simply by releasing the next version

**Comment by JavierRSobrino** [comment]
Ok, I understand. And by any means why can't I login into Core? I have many other services like LND working perfectly with the same user and password, but with mempool I get this error:

`mempool_api_1  | Mar  7 16:09:18 [111] WARN: runMainLoop error: Invalid params, response status code: 401. Retrying in 60 sec.`

Note: I'm using the latest docker image.

**Comment by Code1110** [comment]
I just realized, that the Docker image `mempool/backend:latest` is still using the old `ELECTRS_` convention. So the Docker image should be updated.

**Comment by tadeubas** [comment]
I think this issue should be closed, I am using `ELECTRUM_HOST` and `ELECTRUM_PORT` on docker-compose `environment` and the latest image from backend, everything working fine, see backend log below:

```
mempooldocker-api-1  | Jun 25 21:37:47 [85] INFO: Connected to Electrum Server at 192.168.0.11:50001 (["electrs/0.9.8","1.4"])
```
