### ISSUE TITLE
Taproot annex interpreted as script

### ISSUE THREAD

**Issue by joostjager** [mempool/mempool#3828]
### Description

The taproot annex seems to be not properly recognized and is interpreted as script instead.

#### Version

v2.5.0

### Steps to reproduce

View transaction with taproot annex. This means that the last witness element starts with 0x50 followed by the annex bytes.

### Expected behaviour

Even though the annex is non-standard, it is consensus-valid. It would therefore be better to either not try to interpret the annex as script or add a new display field that shows the annex bytes.

### Actual behaviour

Annex interpreted as script.

### Screenshots

![image](https://github.com/mempool/mempool/assets/4638168/c45c5f91-5c03-42a1-b715-a22f40198d54)

**Comment by softsimon** [comment]
Possibly related to https://github.com/mempool/electrs/pull/2

**Comment by junderw** [comment]
That ASM is trying to parse the signature, not the annex.

I think my fix for Electrs should fix it (see Simon's link)

It would be nice to get an actual link to the transaction so we can check it on blockstream . info to see if they have the same problem.

**Comment by junderw** [comment]
It looks like you're spending the 2nd output of this tx:

https://mempool.space/tx/9540d763880ee09a52ab8ddacc760557a9d28a8df9c51cc81382ce1416d88a27

But on the public mempool.space your transactions does not appear.

More important than the mempool version, do you know the version (or git commit hash / repository) of the electrs backend?

romanz/electrs, blockstream/electrs, mempool/electrs

+ commit hash if possible.

Any info on which backend the mempool/backend app is talking to would help.

**Comment by joostjager** [comment]
I am not using electrs, `"BACKEND": "none"`. So I suppose this is bitcoind directly then?

The tx isn't visible because it is non-standard and only exists in my mempool. The raw tx can be found here: https://twitter.com/joostjgr/status/1664672721794367498

**Comment by junderw** [comment]
I checked the code we use to augment the "none" etc. backends, just in case, and I found the issue.

It should be fixed in the next release.

**Comment by junderw** [comment]
If you can try to apply this patch to your mempool/backend process, I think it should show properly.

**Comment by junderw** [comment]
Thanks for testing the PR for us!

If you have time:

1. Could you search for a no-annex keyspend taproot and no-annex scriptspend taproot and see if they show properly?
2. Could you possibly create a with-annex scriptspend and test it too? (This one is probably a bit more involved, so don't worry if you can't)

**Comment by junderw** [comment]
@joostjager That is fine. The current mempool production servers don't show any taproot script spend scripts yet. (My PR for the esplora backend needs to get merged and deployed)

Thanks for checking! From what I can see in your screen shot it looks like it's working well!
