### ISSUE TITLE
Missing fee range

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#3835]
Maybe related or is that an older bug? https://github.com/mempool/mempool/pull/3811

When catching up locally (bitcoin only)...the min fee of the block fee span is always zero

<img width="939" alt="Screenshot 2023-06-06 at 17 40 17" src="https://github.com/mempool/mempool/assets/9780671/93ab69c5-d3c6-427f-bd2d-5f48f910384a">
<img width="1101" alt="Screenshot 2023-06-06 at 17 40 00" src="https://github.com/mempool/mempool/assets/9780671/e79dd13d-c394-4a8b-a078-f83e9c3be5eb">

**Comment by nymkappa** [comment]
> looks like the same issue as #3805.
> 
> does it still happen running latest master with PR #3811?

Oh let me pull latest change that's a smart suggestion 😆

**Comment by nymkappa** [comment]
Probably related. After wiping my cache and deleting the last 50 blocks from my db, my local does not match prod.

Local
<img width="480" alt="Screenshot 2023-06-06 at 18 09 15" src="https://github.com/mempool/mempool/assets/9780671/c3332580-ce27-4eea-9f29-1807b07faa90">

Prod
<img width="481" alt="Screenshot 2023-06-06 at 18 09 35" src="https://github.com/mempool/mempool/assets/9780671/69632a60-2a9b-41c2-9312-5e84187d2b69">

Also, expanding a block shows different values on prod

Local
<img width="431" alt="image" src="https://github.com/mempool/mempool/assets/9780671/950011cb-0763-4a1c-92e6-f0edf52db068">

Prod
<img width="397" alt="image" src="https://github.com/mempool/mempool/assets/9780671/3119ca3f-166c-47b3-82c6-a472cf020181">

**Comment by softsimon** [comment]
It is an expected issue because we are "fast forwarding" the blocks to save time.

**Comment by nymkappa** [comment]
> It is an expected issue because we are "fast forwarding" the blocks to save time.

Okay so we have different calculation metho between "real time" blocks (when we are online and running) and "historical" blocks (when we are catching up on missed blocks).

So my question is: can we use the same calculation method so that fee spans are the same regardless of how we get the block?

For the second issue, I need to confirm if the bug exist on master. It definitly exists in prod right now.

**Comment by nymkappa** [comment]
See https://github.com/mempool/mempool/issues/3836 and https://github.com/mempool/mempool/issues/3837
