### ISSUE TITLE
Bitcoin address showing wrong balance?

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#3841]
The following address has a below zero value. Basically Electrs is reporting more spent than received. What happened?

```
{
    "address": "38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx",
    "chain_stats": {
        "funded_txo_count": 70,
        "funded_txo_sum": 6092865,
        "spent_txo_count": 78,
        "spent_txo_sum": 6215351,
        "tx_count": 56
    },
}
```

https://mempool.space/address/38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx

<img width="606" alt="Screenshot 2023-06-07 at 17 45 39" src="https://github.com/mempool/mempool/assets/8561090/5b5d45d2-8c17-47d6-87e8-a9efe4a73090">

**Comment by mononaut** [comment]
see https://github.com/mempool/electrs/issues/11
