### ISSUE TITLE
Do not focus search control automatically when opening the website

### ISSUE THREAD

**Issue by yahiheb** [mempool/mempool#3845]
Whenever I open the https://mempool.space/ website the cursor is focused on the search control which doesn't allow me to scroll up and down directly using the arrow keys.
This is bad UX imo.

**Comment by ncois** [comment]
As a heavy user, being able to paste a tx id directly into the search bar seems very practical. 
Plus, the whole UI almost fits entirely on a standard computer screen.

**Comment by nymkappa** [comment]
> Whenever I open the https://mempool.space/ website the cursor is focused on the search control which doesn't allow me to scroll up and down directly using the arrow keys.
> 
> This is bad UX imo.

I don't think many users use the keyboard for scrolling.

As @ncois mentioned, the primary purpose of the autofocus is to allow searching for anything bitcoin related without having to click in the search field. This is very useful for power users (developers and merchants are two examples that comes to my mind) who need to inspect multiple addresses or txs manually.

**Comment by yahiheb** [comment]
FWIW this is now fixed, I guess by #4028.
