### ISSUE TITLE
add user preference to display in WU instead of vB

### ISSUE THREAD

**Issue by TheBlueMatt** [mempool/mempool#3850]
Currently the bitcoin ecosystem largely uses "virtual Bytes" as the unit for transaction cost. This grew largely as a backwards compatibility cudgel to map pre-segwit logic to post-segwit logic, where transaction cost is on an arbitrary weight scale unrelated to the transactions byte size, but rather a rough network-wide cost function.

The continued presence of vB across the network generates confusion that these units are somehow meant to be connected to the transaction's size in bytes. It's time to move on and just talk about transaction cost in terms of weight.

Specifically, I'd suggest (a) a drop-down setting somewhere to get feerate units in sat/WU, rather than sat/vB (and some explainer just saying this is 4x more), and (b) wholesale removing the transaction's vB "size" from the details panel.

**Comment by softsimon** [comment]
Too soon? Of all the wallets out there, are there a single one that lets you enter the fee rate in sats/WU? AFAIK all of them are using sats/vB or sats/B.
