### ISSUE TITLE
View sat/vb range for each block but further than just the last 8 blocks

### ISSUE THREAD

**Issue by otech47** [mempool/mempool#387]
One of my favorite features of mempool.space is the transaction fee rate range on each block that gives you the lower bound of what I assume is the transaction with the lowest sat/vb out of all that were accepted in the block.

I think it'd be nice to be able to paginate that UI and continue loading more and more blocks into the past

![Screenshot 2021-03-13 133232](https://user-images.githubusercontent.com/4914611/111040348-9d5e4700-8400-11eb-9c05-3ead57ff715d.png)

Can anyone provide any feedback or guidance on whether this is a good idea or if it is already in the works?

**Comment by softsimon** [comment]
Yes we should be able to increase the default 8 to 12 or maybe 16 to accommodate for very wide screens like yours.

**Comment by mononaut** [comment]
Resolved by #2884
