### ISSUE TITLE
Address showing negative balance

### ISSUE THREAD

**Issue by yknl** [mempool/mempool#3874]
### Description

Address balance is showing as negative: https://mempool.space/address/38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx

API response also incorrect:
https://mempool.space/api/address/38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx

#### Version

latest

### Steps to reproduce

https://mempool.space/address/38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx

### Expected behaviour

Balance shouldn't be negative

### Actual behaviour

Balance is negative

### Screenshots

![image](https://github.com/mempool/mempool/assets/29081231/58fa6317-2da5-4c63-9669-738d59330802)

#### Device or machine

All

**Comment by softsimon** [comment]
Fixed in https://github.com/mempool/electrs/pull/12 but not yet live
