### ISSUE TITLE
Tx component block arrow does not always update properly when switching between tx

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#3888]
https://github.com/mempool/mempool/assets/9780671/825b482b-d861-4df2-86ef-5d5080566a00

**Comment by softsimon** [comment]
Fixed in https://github.com/mempool/mempool/pull/3863 ?

**Comment by nymkappa** [comment]
> Fixed in #3863 ?

Looks like it yep. I cannot reproduce using that PR.
