### ISSUE TITLE
ETA might go out of sync

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#3899]
I can reproduce this on master, by just jumping between different transactions by using the search bar or browser navigation back and forth. Suddenly the ETA is 1 minute out of sync.

<img width="429" alt="Screenshot 2023-06-26 at 21 08 49" src="https://github.com/mempool/mempool/assets/8561090/a9902cd0-b3c5-4f55-aba0-47003002eddc">

This happens sometimes, I believe it's related but I don't know how to reproduce.

<img width="621" alt="Screenshot 2023-06-26 at 19 43 41" src="https://github.com/mempool/mempool/assets/8561090/15034ad1-8f49-4df9-930f-1a603831482c">

**Comment by nymkappa** [comment]
For the second example it's actually 10 minutes out of sync. 

Definitely a bug as we cannot expect the confirmation ETA to be 1 minute 😂.
