### ISSUE TITLE
Consider adding monospace font for hexidecimal and numeric fields

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#39]
https://fonts.google.com/specimen/Source+Code+Pro

**Comment by softsimon** [comment]
It looks more aligned... But design wise not so good..

![monofont](https://user-images.githubusercontent.com/8561090/78504256-1804f800-7796-11ea-95ff-7aaa711c9626.jpg)

**Comment by softsimon** [comment]
Doesn't look good enough. Closing until future consideration.
