### ISSUE TITLE
SOLVED !!! (rebuild my mariadb mempool database)  mempool.service not enable !! after sudo systemctl enable --now mempool.service

### ISSUE THREAD

**Issue by bitecorner** [mempool/mempool#3904]
Hello everybody,

Describe the bug
journactl -fu mempool result :
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] DEBUG: MIGRATIONS: Running migrations
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] DEBUG: MIGRATIONS: Database engine version '10.6.12-MariaDB-0ubuntu0.22.04.1'
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] DEBUG: MIGRATIONS: Current state.schema_version 47
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] DEBUG: MIGRATIONS: Latest DatabaseMigration.version is 62
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] DEBUG: MIGRATIONS: Execute query:
juin 27 08:01:59 ubuntu node[46586]: ALTER TABLE channels ADD source_checked tinyint(1) DEFAULT 0
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] ERR: MIGRATIONS: Unable to create required tables, aborting in 10 seconds. Error: Duplicate column name 'source_checked'
juin 27 08:02:09 ubuntu systemd[1]: mempool.service: Main process exited, code=exited, status=255/EXCEPTION
juin 27 08:02:09 ubuntu systemd[1]: mempool.service: Failed with result 'exit-code'.
juin 27 08:02:09 ubuntu systemd[1]: mempool.service: Consumed 2.013s CPU time.

Did someone had any idea what i should do to fix this issue ?
Thanks for any help.
Best regards.
Jorge

**Comment by bitecorner** [comment]
yanick@ubuntu:~$ journalctl -fu mempool
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] DEBUG: MIGRATIONS: Running migrations
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] DEBUG: MIGRATIONS: Database engine version '10.6.12-MariaDB-0ubuntu0.22.04.1'
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] DEBUG: MIGRATIONS: Current state.schema_version 47
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] DEBUG: MIGRATIONS: Latest DatabaseMigration.version is 62
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] DEBUG: MIGRATIONS: Execute query:
juin 27 08:01:59 ubuntu node[46586]: ALTER TABLE `channels` ADD source_checked tinyint(1) DEFAULT 0
juin 27 08:01:59 ubuntu node[46586]: Jun 27 08:01:59 [46586] ERR: MIGRATIONS: Unable to create required tables, aborting in 10 seconds. Error: Duplicate column name 'source_checked'
juin 27 08:02:09 ubuntu systemd[1]: mempool.service: Main process exited, code=exited, status=255/EXCEPTION
juin 27 08:02:09 ubuntu systemd[1]: mempool.service: Failed with result 'exit-code'.
juin 27 08:02:09 ubuntu systemd[1]: mempool.service: Consumed 2.013s CPU time.
juin 27 08:12:09 ubuntu systemd[1]: mempool.service: Scheduled restart job, restart counter is at 1.
juin 27 08:12:09 ubuntu systemd[1]: Stopped mempool.
juin 27 08:12:09 ubuntu systemd[1]: mempool.service: Consumed 2.013s CPU time.
juin 27 08:12:09 ubuntu systemd[1]: Started mempool.
juin 27 08:12:10 ubuntu node[46752]: Jun 27 08:12:10 [46752] NOTICE: Starting Mempool Server... (e88cf70)
juin 27 08:12:10 ubuntu node[46752]: Jun 27 08:12:10 [46752] INFO: Connected to Electrum Server at 127.0.0.1:50002 (["electrs/0.9.13","1.4"])
juin 27 08:12:10 ubuntu node[46752]: Jun 27 08:12:10 [46752] INFO: Database connection established.
juin 27 08:12:10 ubuntu node[46752]: Jun 27 08:12:10 [46752] DEBUG: MIGRATIONS: Running migrations
juin 27 08:12:10 ubuntu node[46752]: Jun 27 08:12:10 [46752] DEBUG: MIGRATIONS: Database engine version '10.6.12-MariaDB-0ubuntu0.22.04.1'
juin 27 08:12:10 ubuntu node[46752]: Jun 27 08:12:10 [46752] DEBUG: MIGRATIONS: Current state.schema_version 47
juin 27 08:12:10 ubuntu node[46752]: Jun 27 08:12:10 [46752] DEBUG: MIGRATIONS: Latest DatabaseMigration.version is 62
juin 27 08:12:10 ubuntu node[46752]: Jun 27 08:12:10 [46752] DEBUG: MIGRATIONS: Execute query:
juin 27 08:12:10 ubuntu node[46752]: ALTER TABLE `channels` ADD source_checked tinyint(1) DEFAULT 0
juin 27 08:12:10 ubuntu node[46752]: Jun 27 08:12:10 [46752] ERR: MIGRATIONS: Unable to create required tables, aborting in 10 seconds. Error: Duplicate column name 'source_checked'
juin 27 08:12:20 ubuntu systemd[1]: mempool.service: Main process exited, code=exited, status=255/EXCEPTION
juin 27 08:12:20 ubuntu systemd[1]: mempool.service: Failed with result 'exit-code'.
juin 27 08:12:20 ubuntu systemd[1]: mempool.service: Consumed 1.886s CPU time.
juin 27 08:22:20 ubuntu systemd[1]: mempool.service: Scheduled restart job, restart counter is at 2.
juin 27 08:22:20 ubuntu systemd[1]: Stopped mempool.
juin 27 08:22:20 ubuntu systemd[1]: mempool.service: Consumed 1.886s CPU time.
juin 27 08:22:20 ubuntu systemd[1]: Started mempool.
juin 27 08:22:21 ubuntu node[46891]: Jun 27 08:22:21 [46891] NOTICE: Starting Mempool Server... (e88cf70)
juin 27 08:22:21 ubuntu node[46891]: Jun 27 08:22:21 [46891] INFO: Database connection established.
juin 27 08:22:21 ubuntu node[46891]: Jun 27 08:22:21 [46891] DEBUG: MIGRATIONS: Running migrations
juin 27 08:22:21 ubuntu node[46891]: Jun 27 08:22:21 [46891] DEBUG: MIGRATIONS: Database engine version '10.6.12-MariaDB-0ubuntu0.22.04.1'
juin 27 08:22:21 ubuntu node[46891]: Jun 27 08:22:21 [46891] DEBUG: MIGRATIONS: Current state.schema_version 47
juin 27 08:22:21 ubuntu node[46891]: Jun 27 08:22:21 [46891] DEBUG: MIGRATIONS: Latest DatabaseMigration.version is 62
juin 27 08:22:21 ubuntu node[46891]: Jun 27 08:22:21 [46891] DEBUG: MIGRATIONS: Execute query:
juin 27 08:22:21 ubuntu node[46891]: ALTER TABLE `channels` ADD source_checked tinyint(1) DEFAULT 0
juin 27 08:22:21 ubuntu node[46891]: Jun 27 08:22:21 [46891] ERR: MIGRATIONS: Unable to create required tables, aborting in 10 seconds. Error: Duplicate column name 'source_checked'
juin 27 08:22:22 ubuntu node[46891]: Jun 27 08:22:22 [46891] INFO: Connected to Electrum Server at 127.0.0.1:50002 (["electrs/0.9.13","1.4"])
juin 27 08:22:31 ubuntu systemd[1]: mempool.service: Main process exited, code=exited, status=255/EXCEPTION
juin 27 08:22:31 ubuntu systemd[1]: mempool.service: Failed with result 'exit-code'.
juin 27 08:22:31 ubuntu systemd[1]: mempool.service: Consumed 2.115s CPU time.

**Comment by wiz** [comment]
Is this a custom deployment? Are you running mysql or mariadb?

**Comment by bitecorner** [comment]
Hello
I am running mariadb following 402paymentrequired YouTube channel to implement it under mempool user without sudo privilege belonging to bitcoin group running the Bitcoincore and running the service under an user having sudo privilege where mariadb database mempool is installed.

Envoyé depuis Proton Mail mobile

-------- Message d'origine --------

**Comment by bitecorner** [comment]
I had also an issue concerning the path of my node as it was installed under usr/local/bin/node instead of usr/bin/node as specified in my config file previously.
I also deleted the mempool database in mariadb and did a new one.
Not sure what was the problem but i noticed previously if i run the backend to see if it works, looks like after it creating double columns in mariadb mempool database occurring an error as i was facing. Not have enough skills to investigate this further...
Thanks for your feedback.
