### ISSUE TITLE
The time from last block is losing too much precision when rounded to the next 1h.

### ISSUE THREAD

**Issue by nostitos** [mempool/mempool#3911]
There's been no block for about 1 to 1.49 or 1.99 hours, But I can't tell because the time in rounded to 1h.

I sugest adding minutes to the time using the format,

1h 23min ago.

With the word "Ago" it's clear enough that "min" stands for "minutes"

![image](https://github.com/mempool/mempool/assets/48504624/c3953544-f93e-4568-9466-a965bb249fc3)
1h 23min ago.

There woule be plenty of space.

What I'm often checking mem.space for is to check the time inteterval between blocks, and that's currently only useful between the 2-3 last block as long as they are in minutes and not above 1h.

**Comment by nostitos** [comment]
![image](https://github.com/mempool/mempool/assets/48504624/d11154f0-9da1-4f86-a234-f4fb9b2b59e2)

Not very useful

**Comment by softsimon** [comment]
Closing as fixed.
