### ISSUE TITLE
Mining pool blocks list is broken

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#3977]
The same blocks are repeating

<img width="1128" alt="Screenshot 2023-07-17 at 11 08 05" src="https://github.com/mempool/mempool/assets/8561090/b010de38-7273-4528-a97d-0173f2c3b48d">

**Comment by softsimon** [comment]
Fixed in https://github.com/mempool/mempool/pull/3978

**Comment by Fireskull81** [comment]
Hello

**Comment by BabyLion1** [comment]
Hello
