### ISSUE TITLE
Latest block list is broken

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4012]
When a new block arrives, it doesn't update the latest blocks list.

```
ERROR TypeError: Cannot read properties of undefined (reading 'height')
at blocks-list.component.ts:101:72
```

Row:
`this.blocksCount = Math.max(this.blocksCount, blocks[1][0].height) + 1;`

<img width="570" alt="Screenshot 2023-07-20 at 15 47 49" src="https://github.com/mempool/mempool/assets/8561090/dcfe4e26-35aa-43d5-97e6-7ee71eb550d2">

**Comment by nymkappa** [comment]
Please check if https://github.com/mempool/mempool/pull/3597 does not fix that issue already @softsimon
