### ISSUE TITLE
Blockchain blocks does not auto scroll properly to the requested block

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#4017]
https://github.com/mempool/mempool/assets/9780671/4cd6067b-0bad-48c7-8bf7-dbdf3c5a692d

**Comment by mononaut** [comment]
I can't reproduce. what browser is this? and which mempool version?

**Comment by nymkappa** [comment]
> I can't reproduce. what browser is this? and which mempool version?

Safari. Iphone 13 mini.

v3.0.0-dev @ 4b4173063 (mempool.ninja)

**Comment by nymkappa** [comment]
Cannot repro, probably fixed by https://github.com/mempool/mempool/pull/4268
