### ISSUE TITLE
Support P2PK on the address page

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4019]
Instead of displaying P2PK, actually print out the Pub Key as that was the "address" at that time.

Create a new URL: `/pubkey/<pubkey>` as opposed to the current `/address/<address>` but redirect the URL to the same Address Component.

In the Address Component, detect that we are coming from the '/pubkey/' url and now convert the pubkey to a script hash in order to look the address upp against the esplora `/api/scripthash/:hash` and `/api/scripthash/:hash/txs` 

The conversion algorithm is like the following in NodeJS, but I guess we can do it in the frontend as well(?), but if it requires an extra 3rd party library, it make sense to instead implement it straight into `mempool/electrs` as a new /pubkey/ endpoint.

```
Buffer.from('pubkey, 'hex');
crypto.createHash('sha256').update(str).digest('hex')
```

**Comment by junderw** [comment]
All modern browsers can do this:

```js
// Input: Buffer-like object
// Output: hex string
async function sha256(buf) {
  // Hash. This can be Buffer or Uint8Array or ArrayBuffer etc.
  const hashBuffer = await crypto.subtle.digest('SHA-256', buf);
  // Convert hash to array of numbers 0-255
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  // Convert to hex string
  return hashArray
    .map((bytes) => bytes.toString(16).padStart(2, '0'))
    .join('');
}
```

**Comment by junderw** [comment]
This can also work.

```js
const spk = Buffer.from(vout[0].scriptpubkey, 'hex');
const hashBuffer = await crypto.subtle.digest('SHA-256', spk);
const queryText = Buffer.from(new Uint8Array(hashBuffer)).toString('hex');
```
