### ISSUE TITLE
Missing Menu Items

### ISSUE THREAD

**Issue by Deekee62** [mempool/mempool#4023]
### Description

Menu item for Mainnet, Signet, Testnet and Layer 2 Networks, Bisq, Liquid and Liquid Testnet and Lightning Explorer missing

#### Version

v2.5.0 [[57eddac7](https://github.com/mempool/mempool/commit/57eddac7)]

The installation of mempool was done manually using backend/ and frontend/ instructions

### Steps to reproduce

No steps required

### Expected behaviour

Display of all menu items
<img width="598" alt="image" src="https://github.com/mempool/mempool/assets/33904339/ae270b2b-a0e0-498a-bbe2-1b79451eca26">

### Actual behaviour

Actual display of menu items
<img width="492" alt="image" src="https://github.com/mempool/mempool/assets/33904339/aba51bc5-2ff3-488a-8908-79324e4d32b1">

### Screenshots

<img width="1266" alt="image" src="https://github.com/mempool/mempool/assets/33904339/1bbebb24-4f2e-46b6-aca1-82aa93adff44">

#### Device or machine

Linux MacMini 6.3.0-1-amd64 https://github.com/mempool/mempool/pull/1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1 (2023-06-12) x86_64 GNU/Linux

#### Additional info

Never the lees the Lightning section is accessible, as seen in the screenshot above, when pointing the browser to:

https://192.168.1.48:4081/lightning

**Comment by nymkappa** [comment]
This menu is only for production setup, which is not your case. Closing as it's expected behavior.

**Comment by raelschiffler** [comment]
For the sake of curiosity, will this menu be available in next release? Or is it in the roadmap to be available to manual backend/frontend installation?

**Comment by nymkappa** [comment]
It's already available. You can enable them if you want but you will have to setup all the required backends as well. We only provide support for this kind of full setup to enterprise sponsors. If you want a full setup you need to follow those instructions https://github.com/mempool/mempool/tree/master/production#readme

**Comment by raelschiffler** [comment]
Thanks for answering so quickly. I'll try this by myself, yet sooner than
later may I be an enterprise sponsor and we may do this together.
