### ISSUE TITLE
Expose the current fiat prices using an API

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4052]
1. Expose the current price of Bitcoin in our supported fiat currencies via an api endpoint.

Suggested endpoint and data output, similar to the current https://mempool.space/api/v1/historical-price

`/api/v1/price`.

```
 {
   "USD": 29366,
   "EUR": 26502,
   "GBP": 22683,
   "CAD": 38732,
   "CHF": 25313,
   "AUD": 43447,
   "JPY": 4115960,
   "time": 1690423200, (latest price update)
}
```

2. If it's not done already, use median instead of average for the exchange prices. https://github.com/mempool/mempool/issues/3986
3. Increase the update frequency from current hourly (?)

**Comment by reez** [comment]
Would love this! We are working on an [iOS example wallet](https://github.com/reez/BDKSwiftExampleWallet) for [BDK](https://github.com/bitcoindevkit/bdk-ffi/issues/318) where we were really hoping to use mempool.space as the price API data source.

**Comment by reez** [comment]
Thanks for this!
