### ISSUE TITLE
Incorrect reward representation when using Microsoft EDGE browser

### ISSUE THREAD

**Issue by Goro2030** [mempool/mempool#4097]
When I see this TX using EDGE, it shows like this:

`https://mempool.space/tx/341d1f6a5d0ed9a91ca1fa74faf0f7025d065a6e1d84382d9b85bab8a0a7ce85`

![image](https://github.com/mempool/mempool/assets/10875290/578a0c50-8372-4788-96fd-b3fa7523d819)

It shows properly in Chrome or Firefox.

**Comment by nymkappa** [comment]
Not related to Edge. Fixed in https://github.com/mempool/electrs/pull/32 afaik @mononaut ?

**Comment by mononaut** [comment]
yes
