### ISSUE TITLE
CORS Issues with API

### ISSUE THREAD

**Issue by cryptoquick** [mempool/mempool#4105]
On https://bitmask.app, we're running into CORS issues with Esplora. We're attempting to switch to https://blockstream.info/api to see if this solves the issue on our https://beta.bitmask.app branch, will report back if this helps to narrow down the issue.

We're working on running our own Esplora instance, but we've just been in rushed startup mode for a while. Let us know if that's something you'd prefer us at DIBA to prioritize, but it seems tricky and we might need some advice.

**Comment by cryptoquick** [comment]
Trying the Blockstream API had even worse results and broke all our tests. I'm not sure why.

**Comment by junderw** [comment]
[HTTP Status 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) is "Too Many Requests"

You have hit the rate limit.

mempool also has rate limiting.

**Comment by cryptoquick** [comment]
I see... That's very good to know. I guess I know what I'm doing with my weekend. Do you know if there's an infrastructure as a service provider that we can pay to offer this for us?

**Comment by junderw** [comment]
> I see... That's very good to know. I guess I know what I'm doing with my weekend. Do you know if there's an infrastructure as a service provider that we can pay to offer this for us?

[Mempool offers this](https://mempool.space/enterprise/)

**Comment by cryptoquick** [comment]
NICE! THANK YOU! :pray: 
Will send this to our CEO right away.

**Comment by cryptoquick** [comment]
Upon further reflection, I've filed #4106 so that hopefully this situation might not happen to others. Or maybe I'm just extraordinarily dumb and this has never happened before and never will happen again.

**Comment by cryptoquick** [comment]
Okay, it looks like we're still getting rate limited with even with the new subdomain:
```
Error: Esplora client error: Reqwest(reqwest::Error { kind: Status(429), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("diba.mempool.space")), port: None, path: "/api/scripthash/b07add900ee26b4de6d88be218f57f77e2de61a04cbc13e41cd59de55ff40595/txs", query: None, fragment: None } })
```
I'm not sure what we should do. Will this just resolve over time, or is there a larger issue we're missing?

**Comment by wiz** [comment]
send me a DM on Twitter @wiz
