### ISSUE TITLE
Skip all accelerator related code if not using bitcoin mainnet

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#4118]
```
Aug  9 09:56:53 [49517] WARN: <testnet> Could not connect to http://localhost:9000/api/v1/services/accelerator/accelerations (Attempt 1/1). Reason: connect ECONNREFUSED 127.0.0.1:9000
```

**Comment by mononaut** [comment]
I've disabled all accelerator stuff in the frontend in #4138.

For the backend, we already skip all accelerator related code when `MEMPOOL_SERVICES.ACCELERATIONS = false` in the backend config.

**Comment by nymkappa** [comment]
> I've disabled all accelerator stuff in the frontend in #4138.
> 
> For the backend, we already skip all accelerator related code when `MEMPOOL_SERVICES.ACCELERATIONS = false` in the backend config.

Thanks. I realized that I've created this issue because my config was not set properly, once again. Thanks for fixing the missing frontend mainnet check, I forgot about it.
