### ISSUE TITLE
[transaction flow chart] javascript error when hovering the "fee output"

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#4119]
# How to reproduce

- Open any testnet/signet transaction, eg https://mempool.space/testnet/tx/1744842951116b899ae4b259fa0b9d0149287d2410af02fca473d702bf8e35aa
- Hover the transaction fee line in the transaction flow chart
- A javascript error is printed

<img width="1405" alt="image" src="https://github.com/mempool/mempool/assets/9780671/3a049bb0-25ea-44a4-8a8d-3267db4908ce">

**Comment by softsimon** [comment]
Doesn't reproduce for me locally or on the link provided

**Comment by nymkappa** [comment]
Note: Maybe I broke this in https://github.com/mempool/mempool/pull/3111/commits/f6c7839524c7b19ae7536b649b79441fd4559dd3 ?

**Comment by mononaut** [comment]
I can't reproduce this on current master. I think it was fixed by #4108?

**Comment by nymkappa** [comment]
Cannot reproduce in prod anymore. Closing.
