### ISSUE TITLE
Address balance is not including the block reward

### ISSUE THREAD

**Issue by Ben-in-Chicago** [mempool/mempool#4155]
### Description

The Total Received and Balance for this address is not including the 50 BTC block reward:
https://mempool.space/address/1EMXZbaudKPbQxkj5mH5gmRgkWQSRmsVQb

#### Version

commit/6f11defe

### Steps to reproduce

Enter address of 1EMXZbaudKPbQxkj5mH5gmRgkWQSRmsVQb

### Expected behaviour

Mempool is currently showing two transactions totaling 1,094 sats. There is a block reward transaction dated 2009-04-25 where this address was credited with 50 BTC as the block reward. The expectation is that this transaction and balance (50) is included in the Total Received and Balance totals.

### Actual behaviour

The transaction dated 2009-04-25 and bitcoin from that transaction is not included in the Total Received and Balance totals.

#### Additional info

Here are two other explorers showing the transaction and balance:
https://www.blockchain.com/explorer/addresses/btc/1EMXZbaudKPbQxkj5mH5gmRgkWQSRmsVQb
https://www.okx.com/explorer/btc/address/1EMXZbaudKPbQxkj5mH5gmRgkWQSRmsVQb

Thanks
Ben

**Comment by mononaut** [comment]
The reward from block 12263 wasn't technically paid to address 1EMXZbaudKPbQxkj5mH5gmRgkWQSRmsVQb, but rather to a [P2PK output](https://learnmeabitcoin.com/technical/p2pk) with the same public key.

Some block explorers do index transactions involving raw pubkeys under their corresponding pay-to-pubkey-hash address, however there is [some debate](https://twitter.com/murchandamus/status/1665732910219948037) over whether that's a reasonable thing to do.

mempool.space prefers to index and display P2PK 'addresses' separately, so you'll find the 'missing' block reward listed under https://mempool.space/address/04ff4dfb4a9eedf0224ca58bee7a357d59bef7fdd1994244f6cdefc755633e467898aef837592f3d4e6ca8e7ce0d68a2ce4849258ee5e3e014cfd3385d744c23ee instead.
