### ISSUE TITLE
Add Subresource Integrity

### ISSUE THREAD

**Issue by junderw** [mempool/mempool#416]
Add SRI to the `script` tags generated in the HTML.
I think it's as simple as just:
`ng build --prod --subresourceIntegrity`
But not sure.

**Comment by wiz** [comment]
@junderw did you still want to work on this? if not let's close it

**Comment by junderw** [comment]
https://github.com/angular/angular-cli/issues/19460#issuecomment-1067933411

Looks like Angular is ignoring the issue so let's close it.
