### ISSUE TITLE
Lightning never finishes indexing. 

### ISSUE THREAD

**Issue by niteshbalusu11** [mempool/mempool#4177]
### Description

Self hosted Lightning network explorer never finishes indexing. It's been nearly a week. We even hosted one at foundry probably a month ago and it has the same issue. 

#### Version

0.2.5

### Steps to reproduce

Self host lightning explorer with LND, indexing never finishes completely. 

### Expected behaviour

Indexing finishes and everything populates. 

### Actual behaviour

Incomplete info on pages and shows as indexing. 

### Screenshots

![Screenshot_20230817-133655.png](https://github.com/mempool/mempool/assets/84944042/3dbcc863-5115-4cb6-8835-2b42fe08c8cd)

![Screenshot_20230817-133716.png](https://github.com/mempool/mempool/assets/84944042/611b3215-d89f-4772-8248-d58c3303763e)

![Screenshot_20230817-133724.png](https://github.com/mempool/mempool/assets/84944042/53442397-8f9c-486b-a51d-25c30f797b14)

![Screenshot_20230817-133731.png](https://github.com/mempool/mempool/assets/84944042/af14dff2-7eb0-4ee5-816f-99949112aef2)

#### Device or machine

Ubuntu 22

**Comment by nymkappa** [comment]
Thanks for testing and reporting this. Will try to reproduce on a fresh database. I feel like it could be related to https://github.com/mempool/mempool/issues/4104.

**Comment by niteshbalusu11** [comment]
If you'd like to see my hosted website use mempool.noderunner.wtf

**Comment by nymkappa** [comment]
It's a weird result you get, it feels like the indexing is aborted in the middle, leading to inconsistent data. For example you have proper geoip data for LOOP, but you don't have anything displayed in the top map.

I cannot repro with a clean install on a dev setup. The data seems properly indexed. Tested with `electrs` and `none` in `MEMPOOL.BACKEND`. I've noticed other issues in the mean time that could be related but we need to investigate more.

Do you see any `ERR` or `WARN` being logged in the nodejs backend?
On what device are you running this?

**Comment by niteshbalusu11** [comment]
No error or warning logs at all. Running on Ubuntu 22 but inside docker container.

**Comment by niteshbalusu11** [comment]
Oh and my lightning backend is LND. Idk if that makes a difference.

**Comment by niteshbalusu11** [comment]
> I cannot repro with current master branch, with a clean install on a dev setup. The data seems properly indexed. Tested with electrs and none in MEMPOOL.BACKEND. 

I'm not running master but v2.5.0 which was a release back in March. So idk if things changed since then. Should I be running master? 
Can you try reproducing with v2.5.0? 

Also my personal setup is LND, we had the same issue when we did it at foundry 2 months ago with core lightning.

**Comment by mononaut** [comment]
I couldn't reproduce this on v2.5.0 [[57eddac7](https://github.com/mempool/mempool/commit/57eddac7)] with LND.

Snooping around your instance a bit, it looks like you only have closed channels in your database and zero open channels (which causes the "Indexing in progress" message).

If there are definitely no errors like
```
ERR: <lightning> [Lightning] $runTasks() error: Request failed with status code 500
```
or
```
ERR: <lightning> [Lightning] $runTasks() error: connect ECONNREFUSED 127.0.0.1:8080
```
in your mempool nodejs backend logs, my best guess is that your LND node is missing its network graph. Are you able to run `lncli describegraph` to check if it actually has any data?

**Comment by niteshbalusu11** [comment]
[graph.json.zip](https://github.com/mempool/mempool/files/12381821/graph.json.zip)

Here's my graph file from lncli describegraph

**Comment by mononaut** [comment]
thanks, that's very helpful.

I think the root of the issue is that all of your channels have `"chan_point"` set to `"0000000000000000000000000000000000000000000000000000000000000000:0"`.

obviously `"0000000000000000000000000000000000000000000000000000000000000000"` isn't a real transaction, so the mempool backend isn't able to check whether the channel's utxo is still valid. The default behavior is to treat an unknown utxo as "spent" (or, rather, as unspendable), and therefore to mark the channel as closed.

If there are no known open/active channels, the frontend assumes that we haven't finished syncing lightning data.

I'm not sure why your `chan_point`s are missing, but perhaps it's related to https://github.com/lightningnetwork/lnd/issues/3024, if you have that flag enabled?

**Comment by niteshbalusu11** [comment]
Ahaa. Interesting. Guess if you use neutrino backend it will do that. I have to switch an lnd node backend by Bitcoin core I guess. Thanks, I'll look into it.

**Comment by niteshbalusu11** [comment]
Ok issue fixed, I switched to an lnd with bitcoin-core backend.
Thank you for helping me debug.

**Comment by 21orangehat** [comment]
Hey guys,

I'm having the same issue on my self-hosting at https://mempool.orangehat.wtf

I ran the lncli describegraph command and it shows data
...
{
            "channel_id": "887799564475236355",
            "chan_point": "456c7b527e349aa24b2a26906bfd15f7313635e87b019075a994d1e22e657d63:3",
            "last_update": 1694597516,
            "node1_pub": "031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0",
            "node2_pub": "03c792f6a89fefd3f1b49b3d2ce23143b6f18d36b2ccb039fdb7dbfeb29159bb70",
            "capacity": "12000000",
            "node1_policy": {
                "time_lock_delta": 40,
                "min_htlc": "1000",
                "fee_base_msat": "1000",
                "fee_rate_milli_msat": "1",
                "disabled": false,
                "max_htlc_msat": "11880000000",
                "last_update": 1694595657,
                "custom_records": {}
            },
            "node2_policy": {
                "time_lock_delta": 144,
                "min_htlc": "1000",
                "fee_base_msat": "0",
                "fee_rate_milli_msat": "41",
                "disabled": false,
                "max_htlc_msat": "11880000000",
                "last_update": 1694597516,
                "custom_records": {}
            },
            "custom_records": {}
        }
...

Mempool backend logs looks pretty normal:

...
Sep 13 09:48:00 orangehat npm[110936]: Sep 13 09:48:00 [110936] DEBUG: <lightning> Mempool updated in 0.915 seconds. New size: 121051 (+7)
Sep 13 09:48:01 orangehat npm[110936]: Sep 13 09:48:01 [110936] DEBUG: <lightning> Running statistics
Sep 13 09:48:02 orangehat npm[110936]: Sep 13 09:48:02 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 09:48:03 orangehat npm[110936]: Sep 13 09:48:03 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.099 seconds
Sep 13 09:48:03 orangehat npm[110936]: Sep 13 09:48:03 [110936] DEBUG: <lightning> Mempool updated in 0.795 seconds. New size: 121058 (+7)
Sep 13 09:48:05 orangehat npm[110936]: Sep 13 09:48:05 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 09:48:06 orangehat npm[110936]: Sep 13 09:48:06 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.1 seconds
Sep 13 09:48:06 orangehat npm[110936]: Sep 13 09:48:06 [110936] DEBUG: <lightning> Mempool updated in 0.792 seconds. New size: 121066 (+8)
Sep 13 09:48:08 orangehat npm[110936]: Sep 13 09:48:08 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 09:48:09 orangehat npm[110936]: Sep 13 09:48:09 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.099 seconds
Sep 13 09:48:09 orangehat npm[110936]: Sep 13 09:48:09 [110936] DEBUG: <lightning> Mempool updated in 0.799 seconds. New size: 121069 (+3)
Sep 13 09:48:11 orangehat npm[110936]: Sep 13 09:48:11 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 09:48:12 orangehat npm[110936]: Sep 13 09:48:12 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.31 seconds
Sep 13 09:48:12 orangehat npm[110936]: Sep 13 09:48:12 [110936] DEBUG: <lightning> Mempool updated in 1.289 seconds. New size: 121077 (+8)
Sep 13 09:48:14 orangehat npm[110936]: Sep 13 09:48:14 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 09:48:15 orangehat npm[110936]: Sep 13 09:48:15 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.103 seconds
Sep 13 09:48:15 orangehat npm[110936]: Sep 13 09:48:15 [110936] DEBUG: <lightning> Mempool updated in 0.796 seconds. New size: 121088 (+11)
Sep 13 09:48:17 orangehat npm[110936]: Sep 13 09:48:17 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 09:48:18 orangehat npm[110936]: Sep 13 09:48:18 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.1 seconds
Sep 13 09:48:18 orangehat npm[110936]: Sep 13 09:48:18 [110936] DEBUG: <lightning> Mempool updated in 0.789 seconds. New size: 121093 (+5)
Sep 13 09:48:20 orangehat npm[110936]: Sep 13 09:48:20 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 09:48:21 orangehat npm[110936]: Sep 13 09:48:21 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.148 seconds
Sep 13 09:48:21 orangehat npm[110936]: Sep 13 09:48:21 [110936] DEBUG: <lightning> Mempool updated in 1.071 seconds. New size: 121105 (+12)
Sep 13 09:48:23 orangehat npm[110936]: Sep 13 09:48:23 [110936] DEBUG: <lightning> Updating mempool..
...

I have a bitcoin-core backend and electrs running normally. I'm using Docker just for the MariaDB database.

I cloned and installed the latest version v2.5.0

What else could I check to figure out the problem?

I don't have any channel open on my LND node. It could be the problem? I have an Umbrel node running and there I also don't have channels open but the Mempool is working fine there.

I'm using NGINX Proxy + Cloudflare tunnel to make Mempool public.
 
Thanks!

**Comment by nymkappa** [comment]
> I'm having the same issue on my self-hosting at https://mempool.orangehat.wtf

Most likely not the same problem because you have absolutely no data at all on your instance. Original post shows most of the data is there already.

Looks like your backend is not even running anything lightning related. Can you grep `lightning` in your logs?

**Comment by 21orangehat** [comment]
When I check the logs from my Mempool backend with the command: `sudo journalctl -xeu mempool -f`

I get some with lightning as following:

Sep 13 10:49:20 orangehat npm[110936]: Sep 13 10:49:20 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.1 seconds
Sep 13 10:49:20 orangehat npm[110936]: Sep 13 10:49:20 [110936] DEBUG: <lightning> Mempool updated in 0.798 seconds. New size: 120379 (+14)
Sep 13 10:49:22 orangehat npm[110936]: Sep 13 10:49:22 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 10:49:23 orangehat npm[110936]: Sep 13 10:49:23 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.101 seconds
Sep 13 10:49:23 orangehat npm[110936]: Sep 13 10:49:23 [110936] DEBUG: <lightning> Mempool updated in 0.801 seconds. New size: 120384 (+5)
Sep 13 10:49:23 orangehat npm[110936]: Sep 13 10:49:23 [110936] DEBUG: <lightning> Memory usage: 1.26 GB / 2.05 GB
Sep 13 10:49:25 orangehat npm[110936]: Sep 13 10:49:25 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 10:49:26 orangehat npm[110936]: Sep 13 10:49:26 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.1 seconds
Sep 13 10:49:26 orangehat npm[110936]: Sep 13 10:49:26 [110936] DEBUG: <lightning> Mempool updated in 0.826 seconds. New size: 120404 (+20)
Sep 13 10:49:28 orangehat npm[110936]: Sep 13 10:49:28 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 10:49:29 orangehat npm[110936]: Sep 13 10:49:29 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.1 seconds
Sep 13 10:49:29 orangehat npm[110936]: Sep 13 10:49:29 [110936] DEBUG: <lightning> Mempool updated in 0.798 seconds. New size: 120418 (+14)
Sep 13 10:49:31 orangehat npm[110936]: Sep 13 10:49:31 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 10:49:32 orangehat npm[110936]: Sep 13 10:49:32 [110936] DEBUG: <lightning> Mempool blocks calculated in 0.349 seconds
Sep 13 10:49:32 orangehat npm[110936]: Sep 13 10:49:32 [110936] DEBUG: <lightning> Mempool updated in 1.234 seconds. New size: 120422 (+4)
Sep 13 10:49:34 orangehat npm[110936]: Sep 13 10:49:34 [110936] DEBUG: <lightning> Updating mempool...
Sep 13 10:49:35 orangehat npm[110936]: Sep 13 10:49:35 [110936] DEBUG: <lightning> Mempool blocks calc

I don't know if is that 'lightning' info that you asked for.

**Comment by nymkappa** [comment]
> PS: I don't know why, when I paste the logs here the part is removed. So bellow I have the print of it.

Do you see this the following? Also, do you have any `ERR` ?

```
Sep 13 12:56:53 [54396] INFO: <lightning> [Lightning] Starting lightning network sync service
```

**Comment by 21orangehat** [comment]
Yep, I'm trying to debug the application to see what can cause this problem and I see this info about self-signed certificate:

![err](https://github.com/mempool/mempool/assets/106380435/74cd52c5-8efd-445d-a202-278d72a8ba06)

I don't know if this is the reason. The mempool uses the certificated generated by Cloudflare and the LND use
the certificated auto-generated, but it shouldn't be a problem.
