### ISSUE TITLE
Search align issue x2

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#4182]
Another align issue (maybe I broke it while fixing https://github.com/mempool/mempool/issues/3757)

<img width="583" alt="image" src="https://github.com/mempool/mempool/assets/9780671/55862737-a839-4b31-856a-36d16dbb19f9">

**Comment by pdjsh** [comment]
I was going through the issues a bit, and checked out this one, but it seems to have been fixed in the meantime, even though there's no PR for it. You could check if it's still an issue for you and close it if it's been fixed
