### ISSUE TITLE
Negative balance shown for address

### ISSUE THREAD

**Issue by teebszet** [mempool/mempool#4196]
### Description

mempool.space is showing a negative balance for this address

https://mempool.space/address/38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx

for reference, on other explorers:
blockchair.com: https://blockchair.com/bitcoin/address/38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx
blockchain.com: https://www.blockchain.com/explorer/addresses/btc/38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx

#### Version

see the link

### Steps to reproduce

see the link

### Expected behaviour

no negative balance

### Actual behaviour

has negative balance

#### Device or machine

web

**Comment by nostitos** [comment]
It's not showing negative here, 

On a side note, When an RBF shows up when looking at a specific address, It shows as a 2nd transactions adding up.

Maybe you ended up with two RBF out adding up while they should not.

Refreshing showed the transaction as RBF properly.

**Comment by mononaut** [comment]
Negative address balance is related to https://github.com/mempool/electrs/issues/11.

The RBF issue is unrelated, and will be fixed by #4209

**Comment by softsimon** [comment]
Fixed in https://github.com/mempool/mempool/pull/4209
