### ISSUE TITLE
RBF replacement page is not responsive

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#4201]
<img width="392" alt="Screenshot 2023-08-22 at 14 33 51" src="https://github.com/mempool/mempool/assets/9780671/54dfabfd-1ef0-4cef-9199-b773ca8043ed">

**Comment by mononaut** [comment]
???

https://github.com/mempool/mempool/assets/83316221/8e40807e-1575-42ad-85b1-11ecfcad7f56

**Comment by nymkappa** [comment]
Sorry my fault. Actually I broke it. I assumed it was broken because all pages are working fine with my changes except the `/rbf` one but I should I checked on prod first 😆.
