### ISSUE TITLE
Docker version, Used nearly 100% of heap limit, triggers restart of the docker container

### ISSUE THREAD

**Issue by gorrdy** [mempool/mempool#4227]
### Description

After start of the mempool docker version, it starts to restart after a while probably connected to the problem with the heap limit.

#### Version

9f007d78f8b096365543745e7f19c721913fd62d

### Steps to reproduce

Just run a mempool backend for a while in docker.
### Expected behaviour

Shouldn't restart, bigger limit?

### Actual behaviour

It restarts after several minutes

#### Device or machine

Intel Nuc

#### Additional info

Sep  3 15:18:56 [109] NOTICE: Starting Mempool Server... (57eddac)
Sep  3 15:18:56 [109] INFO: Connected to Electrum Server at 192.168.1.101:50002 (["Fulcrum 1.9.1","1.4"])
Sep  3 15:18:56 [109] INFO: Database connection established.
Sep  3 15:18:56 [109] INFO: Restoring mempool and blocks data from disk cache
Sep  3 15:19:02 [109] INFO: Starting statistics service
Sep  3 15:19:02 [109] NOTICE: Mempool Server is running on port 8999
Sep  3 15:19:02 [109] INFO: 23 blocks since tip. Fast forwarding to the 8 recent blocks
Sep  3 15:19:02 [109] INFO: Re-indexing skipped blocks and corresponding hashrates data
Sep  3 15:19:02 [109] INFO: [Mining] Fetching daily price history from exchanges and saving missing ones into the database
Sep  3 15:19:07 [109] WARN: tx selection worker thread returned 6 stale transactions from makeBlockTemplates
Sep  3 15:19:08 [109] WARN: tx selection worker thread returned 6 stale transactions from updateBlockTemplates
Sep  3 15:19:12 [109] WARN: tx selection worker thread returned 8 stale transactions from updateBlockTemplates
Sep  3 15:19:12 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:12 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:12 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:12 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:12 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:12 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:12 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:12 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:12 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:12 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:13 [109] WARN: Used 0.89% of heap limit (1.82 / 2.05 GB)!
Sep  3 15:19:13 [109] INFO: [Mining] Fetching hourly price history from exchanges and saving missing ones into the database
Sep  3 15:19:18 [109] WARN: tx selection worker thread returned 1 stale transactions from updateBlockTemplates
Sep  3 15:19:24 [109] WARN: tx selection worker thread returned 2 stale transactions from updateBlockTemplates
Sep  3 15:19:35 [109] WARN: tx selection worker thread returned 2 stale transactions from updateBlockTemplates
Sep  3 15:19:41 [109] WARN: tx selection worker thread returned 11 stale transactions from updateBlockTemplates
Sep  3 15:19:41 [109] WARN: projected transaction ancestor missing from mempool cache
Sep  3 15:19:47 [109] WARN: tx selection worker thread returned 3 stale transactions from updateBlockTemplates
Sep  3 15:19:58 [109] WARN: Mempool clear protection triggered because transactions.length: 163414 and currentMempoolSize: 391616.
Sep  3 15:20:07 [109] WARN: Used 0.92% of heap limit (1.89 / 2.05 GB)!

**Comment by nymkappa** [comment]
You're not running a default 300MB bitcoin core mempool, which is why the nodejs backend is going out of memory.

Either use a default 300MB mempool, or increase the memory available in nodejs.

**Comment by nailiujac** [comment]
I have the same problem, and I have 300MB set in the mempool size and default value in `dbcache` param in bitcoin core:

```bash
bitcoin-cli getmempoolinfo
```

```json
{
  "loaded": true,
  "size": 25629,
  "bytes": 38967787,
  "usage": 143242288,
  "total_fee": 3.17306614,
  "maxmempool": 300000000,
  "mempoolminfee": 0.00001000,
  "minrelaytxfee": 0.00001000,
  "incrementalrelayfee": 0.00001000,
  "unbroadcastcount": 0,
  "fullrbf": false
}
```

Shortly after starting, this log appear:s

```bash
WARN: Used 95.54% of heap limit (1.96 / 2.05 GB)!
Feb 19 20:26:04 myhost docker[169209]: Feb 19 19:26:04 [127] WARN: Used 94.96% of heap limit (1.94 / 2.05 GB)!
Feb 19 20:27:06 myhost docker[169209]: Feb 19 19:27:06 [127] WARN: Used 95.03% of heap limit (1.95 / 2.05 GB)!
Feb 19 20:28:10 myhost docker[169209]: Feb 19 19:28:10 [127] WARN: Used 94.97% of heap limit (1.94 / 2.05 GB)!
Feb 19 20:29:12 myhost docker[169209]: Feb 19 19:29:12 [127] WARN: Used 94.29% of heap limit (1.93 / 2.05 GB)!
Feb 19 20:30:14 myhost docker[169209]: Feb 19 19:30:14 [127] WARN: Used 95.08% of heap limit (1.95 / 2.05 GB)!
Feb 19 20:31:18 myhost docker[169209]: Feb 19 19:31:18 [127] WARN: Used 94.84% of heap limit (1.94 / 2.05 GB)!
```

And finally this error occurs:

```bash
Feb 19 20:42:34 myhost docker[169209]: Feb 19 19:42:34 [127] WARN: Mempool clear protection ended, normal operation resumed.
Feb 19 20:42:41 myhost docker[169209]: <--- Last few GCs --->
Feb 19 20:42:41 myhost docker[169209]: [127:0x63a95a0]  1350521 ms: Scavenge 2018.5 (2080.7) -> 2018.2 (2082.2) MB, 22.25 / 0.00 ms  (average mu = 0.617, current mu = 0.587) allocation failure;
Feb 19 20:42:41 myhost docker[169209]: [127:0x63a95a0]  1350547 ms: Scavenge 2019.1 (2082.2) -> 2018.7 (2091.7) MB, 20.64 / 0.00 ms  (average mu = 0.617, current mu = 0.587) allocation failure;
Feb 19 20:42:41 myhost docker[169209]: [127:0x63a95a0]  1351606 ms: Mark-Compact 2025.7 (2091.7) -> 2023.9 (2099.5) MB, 1029.77 / 0.00 ms  (average mu = 0.487, current mu = 0.262) allocation failure; scavenge might not succeed
Feb 19 20:42:41 myhost docker[169209]: <--- JS stacktrace --->
Feb 19 20:42:41 myhost docker[169209]: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
Feb 19 20:42:41 myhost docker[169209]:  1: 0xc99960 node::Abort() [node]
Feb 19 20:42:41 myhost docker[169209]:  2: 0xb6ffcb  [node]
Feb 19 20:42:41 myhost docker[169209]:  3: 0xebe420 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
Feb 19 20:42:41 myhost docker[169209]:  4: 0xebe707 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
Feb 19 20:42:41 myhost docker[169209]:  5: 0x10d01b5  [node]
Feb 19 20:42:41 myhost docker[169209]:  6: 0x10e8038 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
Feb 19 20:42:41 myhost docker[169209]:  7: 0x10be151 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
Feb 19 20:42:41 myhost docker[169209]:  8: 0x10bf2e5 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
Feb 19 20:42:41 myhost docker[169209]:  9: 0x109b926 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
Feb 19 20:42:41 myhost docker[169209]: 10: 0x108cf6c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [node]
Feb 19 20:42:41 myhost docker[169209]: 11: 0x108d0d4 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [node]
Feb 19 20:42:41 myhost docker[169209]: 12: 0x126de8f  [node]
Feb 19 20:42:41 myhost docker[169209]: 13: 0x127aec3  [node]
Feb 19 20:42:41 myhost docker[169209]: 14: 0x129c4bd  [node]
Feb 19 20:42:41 myhost docker[169209]: 15: 0x130fcf6 v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) [node]
Feb 19 20:42:41 myhost docker[169209]: 16: 0x1398263 v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin, v8::internal::EnforceDefineSemantics) [node]
Feb 19 20:42:41 myhost docker[169209]: 17: 0x1501050 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [node]
Feb 19 20:42:41 myhost docker[169209]: 18: 0x150284b v8::internal::Runtime_SetKeyedProperty(int, unsigned long*, v8::internal::Isolate*) [node]
Feb 19 20:42:41 myhost docker[169209]: 19: 0x7f2f43699ef6
Feb 19 20:42:41 myhost docker[169209]: Aborted (core dumped)
```

**Comment by nymkappa** [comment]
Increase available memory for nodejs using `--max-old-space-size=4096` here https://github.com/mempool/mempool/blob/master/docker/backend/start.sh#L300
