### ISSUE TITLE
API returning that tx is not confirmed which is not true

### ISSUE THREAD

**Issue by FlorianHubl** [mempool/mempool#4229]
When I call the mempool API /api/block/:hash/txs method, it returns that the transactions are unconfirmed which is not true.

https://mempool.space/api/block/000000000000000000026aaaf752ba17abe679631f7dd35285ddebfa58de2b55/txs

<img width="1105" alt="F5IwOleXIAA_vcN" src="https://github.com/mempool/mempool/assets/49409175/12a36108-b205-44fc-b5be-ee329d9eb783">

**Comment by junderw** [comment]
Please use the start index.

Originally the /txs endpoint would automatically use a start index of 0, but now it is broken.

We will fix it soon so that `/txs` will also return the same result as start index 0.

```
https://mempool.space/api/block/000000000000000000026aaaf752ba17abe679631f7dd35285ddebfa58de2b55/txs/0
https://mempool.space/api/block/000000000000000000026aaaf752ba17abe679631f7dd35285ddebfa58de2b55/txs/25
https://mempool.space/api/block/000000000000000000026aaaf752ba17abe679631f7dd35285ddebfa58de2b55/txs/50
..... etc.
```
