### ISSUE TITLE
how can i get balance address with my local mempool ?

### ISSUE THREAD

**Issue by VeilleurTrytoFix** [mempool/mempool#423]
hi,

i setup mempool on bitcoin this morning and im trying to get current balance of an address but i got :

Solde | ‎0,00000000 BTC (0,00 $US)

every times, can you say me what im doing wrong ?

everything works fine, but i dont understand why i cant check balance address

thanks

**Comment by softsimon** [comment]
It would be helpful to know what system and version you are running.

Generally a local mempool with fully indexed `romanz/electrs` as a backend for address lookup should work to get the address transactions and balance for addresses.

If I check a random address like `bc1qefcdlevuatwjqqysk4nqx3t5jmxpxscdv77d3n` on my local mempool it correctly displays the balance.

<img width="727" alt="Screen Shot 2021-04-03 at 18 03 27" src="https://user-images.githubusercontent.com/8561090/113480728-e7d65f00-94a6-11eb-91de-a69e688dce33.png">

What result are you getting from this address?

**Comment by VeilleurTrytoFix** [comment]
![mempool-local](https://user-images.githubusercontent.com/11944641/113481962-bc4e7700-949c-11eb-90ab-59425d906d74.png)

**UBUNTU 18.04 (192.168.1.15)**

- mempool 
- mysql-server

mempool/frontend$ nodejs -v
v14.16.0
mempool/frontend$ npm -v
7.8.0
mempool/frontend$ mysql --version
mysql  Ver 14.14 Distrib 5.7.33, for Linux (x86_64) using  EditLine wrapper


**Windows 10 (192.168.1.16)**

- bitcoind
- electrum-personal-server

bitcoin conf
`server=1
txindex=1
whitelist=192.168.1.16
rpcallowip=0.0.0.0/0
rpcconnect=192.168.1.16
rpcbind=192.168.1.16
rpcport =9336
rpcuser=rpcuser    
rpcpassword=rpcpassword`



192.168.1.16:50002
**https://github.com/chris-belcher/electrum-personal-server**

**config.ini**

># Electrum Personal Server configuration file
>
># Lines starting with # are called comments which are ignored.
># For a line to have effect it must not start with #
>
># The most important options are towards the top of the file
>
>[master-public-keys]
># Add electrum wallet master public keys to this section
># In electrum then go Wallet -> Information to get the mpk
>
>#any_name_works = xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF
>
># Multiple master public keys maybe added by simply adding another line
>#my_second_wallet = xpubanotherkey
>
># Multisig wallets use format `required-signatures [list of master pub keys]`
># this example is a 2-of-3 multisig wallet
>#multisig_wallet = 2 xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF xpub661MyMwAqRbcFseXCwRdRVkhVuzEiskg4QUp5XpUdNf2uGXvQmnD4zcofZ1MN6Fo8PjqQ5cemJQ39f7RTwDVVputHMFjPUn8VRp2pJQMgEF
>
>
>[bitcoin-rpc]
>host = 192.168.1.16
>port = 9336
>#add the bitcoin datadir to search for the .cookie file created by the
># node, which avoids the need to configure rpc_user/pass
>#leave this option empty to have it look in the default location
>datadir = J:\bitcoin 
>#if you dont want to use the .cookie method with datadir, uncomment to config u/p here
>rpc_user = rpcuser
>rpc_password = rpcpassword
>
>#to be used with the multi-wallet feature
># see https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.15.0.md#multi-wallet-support
># empty means default file, for when using a single wallet file
>wallet_filename =
>
># how often in seconds to poll for new transactions when electrum not connected
>poll_interval_listening = 30
># how often in seconds to poll for new transactions when electrum is connected
>poll_interval_connected = 5
>
># Parameters for dealing with deterministic wallets
># how many addresses to import first time, should be big because if you import too little you may have to rescan again
>initial_import_count = 1000
># number of unused addresses kept at the head of the wallet
>gap_limit = 25
>
>[electrum-server]
># 0.0.0.0 to accept connections from any IP
>#127.0.0.1 to accept from only localhost
>host = 192.168.1.16
>port = 50002
>
># space-separated whitelist of IP addresses
># accepts CIDR notation eg 192.168.0.0/16 or 2a01:4f8:1f1::/120
># star (*) means all are accepted
># generally requires host binding (above) to be 0.0.0.0
>ip_whitelist = *
>
>#SSL certificate
>#uses the default one, which is fine because by default nobody should be
># allowed to connect to your server or scan your packets
>#to generate another certificate see https://github.com/spesmilo/electrum-server/blob/ce1b11d7f5f7a70a3b6cc7ec1d3e552436e54ffe/HOWTO.md#step-8-create-a-self-signed-ssl-cert
>certfile = certs/cert.crt
>keyfile = certs/cert.key
>
># Option for disabling the fee histogram calculation
># It improves server responsiveness but stops mempool-based Electrum features
># This is useful on low powered devices at times when the node mempool is large
>disable_mempool_fee_histogram = false
>
># Parameter for broadcasting unconfirmed transactions
># Options are:
># * own-node         (broadcast using the connected full node)
># * system <cmd> %s  (save transaction to file, and invoke system command
>#                     with file path as parameter %s)
>broadcast_method = own-node
>
>
>[watch-only-addresses]
>#Add individual addresses to this section, for example paper wallets
>#Dont use this section for adding entire wallets, instead use the
># above section `master-public-keys`
>
>addr = 3KssjQ1BiD4gt5z44i6oJeyS45vPpMCThj
>
># A space separated list is also accepted
>#my_test_addresses = 3Hh7QujVLqz11tiQsnUE5CSL16WEHBmiyR 1PXRLo1FQoZyF1Jhnz4qbG5x8Bo3pFpybz bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq
>
># multiple addresses may also be added in separate lines (like master public keys above)
>#addr2 = 3anotheraddress
>
>
>[logging]
># Section for configuring the logging output
>
># The log level. Logging messages less severe than this will not be displayed
>#options are 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
>#Information printed to the log file is always at level DEBUG
>log_level_stdout = INFO
>
># Location of log file, leave empty to use the default location in temp dir
>log_file_location =
>
># Whether to append to log file or delete and overwrite on startup
>append_log = false
>
># Format to use for logging messages
>#see docs https://docs.python.org/3/library/logging.html#logging.Formatter
>log_format = %(levelname)s:%(asctime)s: %(message)s

![mempool-sync](https://user-images.githubusercontent.com/11944641/113482283-3af7e400-949e-11eb-931f-824f68dd6259.png)

**Comment by softsimon** [comment]
I think the problem is that you are running `electrum-personal-server` which is only made for running with your own wallet, and index your own wallet addresses. 

To look up any address you need the `romanz/electrs` or the `electrumx` python server.

**Comment by VeilleurTrytoFix** [comment]
ok thanks 👍

**Comment by VeilleurTrytoFix** [comment]
hi, i come back im trying to setup mempool with electrumx but mempool cant connect to him, have you an idea of what im doing wrong ?

https://github.com/kyuupichan/electrumx/issues/1047
