### ISSUE TITLE
The transaction submission chart in vB/s should be smoothed to be more readable

### ISSUE THREAD

**Issue by murchandamus** [mempool/mempool#4245]
### Description

The “Transaction vBytes per second (vB/s)” chart on the `…/graphs/mempool` page is very noisy to the point that it is neigh unreadable for most of the time intervals. I’ll refer to this chart as “Submission rate” in the following.

### Problem to be solved

Although the Submission Rate chart is juxtaposed with the mempool composition chart, the Submission Rate chart would be more readable if it had a less detailed resolution than the mempool composition chart. E.g. on the 1M chart, there appear to be datapoints every 30 minutes, but the submission rate can drastically jump between two half hour intervals. E.g. at 4:30PM on Sep. 7th it’s 971 vB/s, then at 5:00PM it’s 8,128 vB/s:

![image](https://github.com/mempool/mempool/assets/4060799/ed4f35e5-3b8f-4e6a-b3af-8ef8dbd4d848)
![image](https://github.com/mempool/mempool/assets/4060799/9d4407ba-f6f8-4678-84ff-e5c7ebb211b3)

### Proposed solution

 Perhaps the Submission Rate chart would be more useful, if it were smoothed to surface trends, e.g. if each 30 minute interval on the 1M chart showed the average of the prior three hours. Alternatively, it would be nice to be able to pick windows over which data is smoothed from a dropdown menu.

#### Additional info

Overview of all time windows:

2h:
![image](https://github.com/mempool/mempool/assets/4060799/1a81e61f-91a5-4c28-b01f-dadd0e6b3851)

24h:
![image](https://github.com/mempool/mempool/assets/4060799/dfb31c8b-fd30-4689-90bf-5f7ba310de83)

1W:
![image](https://github.com/mempool/mempool/assets/4060799/36f6646d-fbdd-437d-9c7f-f7b03f30ce0f)

1M:
![image](https://github.com/mempool/mempool/assets/4060799/0f39332d-d925-4576-8321-383676900464)

3M:
![image](https://github.com/mempool/mempool/assets/4060799/018b6f83-c779-4eeb-86a6-7f5ea8205c30)

6M:
![image](https://github.com/mempool/mempool/assets/4060799/5588b49e-1f18-4b3d-be43-246bba205373)

1Y:
![image](https://github.com/mempool/mempool/assets/4060799/ad2bbeb1-33c9-4be7-928f-9a729854f0ac)

2Y:
![image](https://github.com/mempool/mempool/assets/4060799/ed4d688a-b934-4067-85a7-d30262a0147c)

3Y:
![image](https://github.com/mempool/mempool/assets/4060799/a696ac67-40eb-4079-8691-5f81b2c4b09d)

4Y:
![image](https://github.com/mempool/mempool/assets/4060799/b8bb4b04-ca06-4fad-8694-c2225da486c2)

ALL:
![image](https://github.com/mempool/mempool/assets/4060799/4c3ff7eb-2171-4265-a58c-038d0c4b7c15)

**Comment by mononaut** [comment]
Thanks for the issue!

Yes, it would definitely be good to smooth out some of that noise to reveal the actual trends.

The variance/burstiness of submission traffic is sort of interesting in it's own right though, so I'm reluctant to scrub that off completely.

We do actually have a related issue #2269 and an open PR #3923 to add a smoothed moving average line on top of the existing chart, which might be a good compromise?

<img width="1154" alt="Screenshot 2023-09-11 at 11 27 06 PM" src="https://github.com/mempool/mempool/assets/83316221/c4644f2d-19a4-4625-9220-1b0de1d3b92b">

**Comment by murchandamus** [comment]
Yeah, that would resolve my issue!
