### ISSUE TITLE
Block endpoint return is missing some fields

### ISSUE THREAD

**Issue by PedroW21** [mempool/mempool#4261]
### Description

When I make a request on the endpoint below, the data that I recieved is different from documentaion.

Endpoint: GET BLOCK
Url: https://mempool.space/api/block/000000000000003887df1f29024b06fc2200b55f8af8f35453d7be294df2d214

### Expected behaviour

Expected to receive the fields below:
`
{
  "extras": {
    "reward": 638307429,
    "coinbaseTx": {
      "vin": [
        {
          "scriptsig": "03ad3e0b2cfabe6d6df8fb5429a5de5fc2bd1bafffbc90d33c77eb73307d51931d247f21d7bccde51710000000f09f909f092f4632506f6f6c2f6b0000000000000000000000000000000000000000000000000000000000000000000000050086411100"
        }
      ],
      "vout": [
        {
          "scriptpubkey_address": "1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY",
          "value": 638307429
        }
      ]
    },
    "coinbaseRaw": "03ad3e0b2cfabe6d6df8fb5429a5de5fc2bd1bafffbc90d33c77eb73307d51931d247f21d7bccde51710000000f09f909f092f4632506f6f6c2f6b0000000000000000000000000000000000000000000000000000000000000000000000050086411100",
    "medianFee": 10,
    "feeRange": [
      1,
      8,
      9,
      10,
      15,
      21,
      348
    ],
    "totalFees": 13307429,
    "avgFee": 5591,
    "avgFeeRate": 13,
    "pool": {
      "id": 36,
      "name": "F2Pool",
      "slug": "f2pool"
    },
    "matchRate": 93
  },
  "id": "00000000000000000007566f8f035a1dc38b351e6f54778b311fe6dbabd79b46",
  "height": 736941,
  "version": 536870916,
  "timestamp": 1652891466,
  "bits": 386466234,
  "nonce": 3514220842,
  "difficulty": 31251101365711.12,
  "merkle_root": "4a3072f98f60cbb639bb7f46180b8843d17c7502627ffb633db0ed86610cdd71",
  "tx_count": 2381,
  "size": 1709571,
  "weight": 3997770,
  "previousblockhash": "00000000000000000005ef14db0b4befcbbe1e9b8676eec67fcf810a899c4d5e"
}
`

### Actual behaviour

Received that fields below:
`
{
    "id": "000000000000003887df1f29024b06fc2200b55f8af8f35453d7be294df2d214",
    "height": 250000,
    "version": 2,
    "timestamp": 1375533383,
    "tx_count": 156,
    "size": 95451,
    "weight": 381804,
    "merkle_root": "16ec1eafaca8ca59d182cbf94f29b50b06ac4207b883f380b9bf547fe8fed723",
    "previousblockhash": "0000000000000009c2e82d884ec07b4aafb64ca3ef83baca2b6b0b5eb72c8f02",
    "mediantime": 1375530821,
    "nonce": 9533025,
    "bits": 426957810,
    "difficulty": 37392766.136474565
}
`

**Comment by mononaut** [comment]
Thanks for the issue.

It looks like the documentation needs to be updated - the extended data is available at `/api/v1/block/:hash`

e.g: https://mempool.space/api/v1/block/000000000000003887df1f29024b06fc2200b55f8af8f35453d7be294df2d214

**Comment by PedroW21** [comment]
@mononaut Thank you!
