### ISSUE TITLE
Missing mempool block after reloads

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#4296]
Using regtest, the mempool block often goes missing after reloading. It shows up again after some time:

<img width="1683" alt="Screenshot 2023-09-29 at 11 04 11 PM" src="https://github.com/mempool/mempool/assets/100320/f65b4ed3-cfbf-4afd-b047-aa97d8839a6b">
<img width="1666" alt="Screenshot 2023-09-29 at 11 03 45 PM" src="https://github.com/mempool/mempool/assets/100320/9b7aead7-b5bb-40e5-b321-c00cb1c87b81">

**Comment by softsimon** [comment]
Fixed in https://github.com/mempool/mempool/pull/4745
