### ISSUE TITLE
decimals to 1-2 sats?

### ISSUE THREAD

**Issue by nostitos** [mempool/mempool#4311]
![image](https://github.com/mempool/mempool/assets/48504624/81d9df46-75fc-43b3-8e76-ea9c5ce86115)

There's currently 123mb is transaction between 1 sat and 1.5 sat 

Could we see decimals below 2sat?

**Comment by nymkappa** [comment]
@softsimon @mononaut This seems like a valid improvement request, considering the chart is not linear it means we already have the float values but we round them for display?

**Comment by softsimon** [comment]
On mobile it becomes a bit tight. Any suggestion on solution?

Old vs new

<img width="291" alt="Screenshot 2023-11-11 at 14 46 59" src="https://github.com/mempool/mempool/assets/8561090/d18d038c-3dac-4851-bc47-210a01dbf129">
<img width="291" alt="Screenshot 2023-11-11 at 14 47 02" src="https://github.com/mempool/mempool/assets/8561090/dff3b2f6-3f1c-4aec-a2dc-74b269f39897">
