### ISSUE TITLE
Some differences between the local installation and the mempool.space web.

### ISSUE THREAD

**Issue by nailiujac** [mempool/mempool#4317]
### Description

The fee range for a block displayed in the version I have installed locally and the version on mempool.space is different. What is the reason for the difference?

#### Version

Docker image pulled today

### Steps to reproduce

Viewing the details of a block in the local installation and the mempool.space installation.

### Expected behaviour

The same result in both installations.

### Actual behaviour

Diferent result

### Screenshots

- **mempool.space**

![image](https://github.com/mempool/mempool/assets/83184419/0edaa693-1829-4048-848a-b176f82ee4e5)

![image](https://github.com/mempool/mempool/assets/83184419/1f21e636-3b61-4829-bd66-0057965f3cde)

- **Local mempool with docker**

![image](https://github.com/mempool/mempool/assets/83184419/5c89adc8-a01a-4d62-a20c-5478f4c89043)

![image](https://github.com/mempool/mempool/assets/83184419/161202ef-33a9-460e-9704-15697c578a54)

**Comment by mononaut** [comment]
The difference is whether the fee range is adjusted to consider effective fee rates or not.

The behavior in v2.5.0 (the latest version available on Docker) is to display the range `[10% percentile] - [max]` of the block, sorted by simple fee rate.

But that can be skewed by child-pays-for-parent relationships, so when possible we now calculate a "smarter" fee range that considers the effective fees actually paid to get included in the block.

**Comment by softsimon** [comment]
Basically your local Mempool is running 2.5 and Mempool.Space is running v3.0.0-dev where the algoritms have changed. So not a bug.
