### ISSUE TITLE
BIP69 Transaction Feature Flag

### ISSUE THREAD

**Issue by orangesurf** [mempool/mempool#4335]
### Description

Add BIP69 transaction feature flag

### Problem to be solved

BIP69 (deterministic lexicographical sorting of transaction inputs and outputs) ensures private information (e.g. change address position) is not leaked by the input or output ordering method used by a wallet.

### Proposed solution

Add a feature flag showing whether a transaction complies with BIP69. The tooltip could explain that non-compliance means that the transaction ordering method used by the wallet may be leaking private information. 

#### Additional info

<img width="1434" alt="image" src="https://github.com/mempool/mempool/assets/91332210/9c017394-8c7d-4154-8078-f0ffa190998e">

**Comment by mononaut** [comment]
I don't think we should take an opinionated stance in the tooltip, considering the lack of consensus on BIP69.

But concept ACK for a neutral label with a generic "this transaction conforms to BIP69 lexicographical input/output ordering".

Although I suspect the majority of BIP69-conforming transactions are coincidentally rather than deliberately compliant, so I do wonder how useful this info would be in practice.

**Comment by orangesurf** [comment]
Agreed on the need for a neutral stance (I was trying to get at that with the inclusion of may (rather than is) leaking given the wallet could be randomly shuffling inputs / outputs some other way).

For the latest block (814406) I calculate the following:

47.1 %    Fraction of transactions expected to conform by chance given each tx's input and output number
60.1 %.   Fraction of transactions measured to conform 
(13.0 % Difference)

**Comment by orangesurf** [comment]
Some extra data - Only a small sample of 20 recent blocks but average difference between predicted (based on transaction input and output counts in blocks) and measured is 11.6% (min 7.2 exc 0, max 14.8).


Index | Block Height | Expected | Measured | M-E
-- | -- | -- | -- | --
0 | 814405 | 54.2 | 66.9 | 12.7
1 | 814404 | 49.7 | 64.4 | 14.7
2 | 814403 | 47.0 | 59.5 | 12.5
3 | 814402 | 47.3 | 62.1 | 14.8
4 | 814401 | 47.6 | 61.6 | 14.0
5 | 814400 | 46.1 | 58.6 | 12.5
6 | 814399 | 45.9 | 59.2 | 13.3
7 | 814398 | 45.9 | 59.2 | 13.3
8 | 814397 | 46.3 | 58.1 | 11.8
9 | 814396 | 72.1 | 79.3 | 7.2
10 | 814395 | 61.5 | 70.2 | 8.7
11 | 814394 | 47.4 | 57.1 | 9.7
12 | 814393 | 0.0 | 0.0 | 0.0
13 | 814392 | 37.0 | 44.3 | 7.3
14 | 814391 | 61.7 | 71.8 | 10.1
15 | 814390 | 52.3 | 65.2 | 12.9
16 | 814389 | 49.0 | 60.1 | 11.1
17 | 814388 | 61.6 | 70.4 | 8.8
18 | 814387 | 60.7 | 72.3 | 11.6
19 | 814386 | 48.4 | 61.5 | 13.1





<img width="1167" alt="image" src="https://github.com/mempool/mempool/assets/91332210/065bdd9c-65bc-4703-a1ac-f8a45f177da9">

**Comment by junderw** [comment]
Concept NACK

If anything, this belongs in the block summary. (Expected sorted inputs X%, Actual sorted inputs Y% under a section called BIP69)

The "at a glance" tag is not useful in this position.

**Comment by murchandamus** [comment]
I am not convinced that BIP69 should be encouraged. It would be great if _all_ transactions conformed, but right now it’s only a small subset. And especially with the on-going excitement for ordinals, we cannot expect that all wallets will transition to using it in the long run. This means that the presence or absence of BIP69 will remain a wallet fingerprint in the long run.

It seems more beneficial to encourage wallets to adopt a random ordering which will make the occasional transaction with order requirements stick out less.

If you wanted to help increase awareness for wallet fingerprinting issues, a good one to start with would be to have a “tag of shame” for transactions that order inputs by age.
