### ISSUE TITLE
IP address for Lightning Node in API

### ISSUE THREAD

**Issue by FlorianHubl** [mempool/mempool#4337]
Is there a way to get the IP address or tor address for a Lightning Node via the API?

**Comment by softsimon** [comment]
> Is there a way to get the IP address or tor address for a Lightning Node via the API?

Yes.

https://mempool.space/api/v1/lightning/nodes/02c91d6aa51aa940608b497b6beebcb1aec05be3c47704b682b3889424679ca490

`    "sockets": "213.174.156.82:9735,[2a02:b48:207:2:9735:9735:0:3]:9735,5d2sv46za2hdhhrt5dkhox54gmuysc37kzookf45u7anjxndzf2wcsqd.onion:9735",
`
