### ISSUE TITLE
block status api not working

### ISSUE THREAD

**Issue by philipp1992** [mempool/mempool#4346]
Hi,
im running mempool for bitcoin testnet with bitcoind and without esplora.
While this api endpoint works https://xxxx/api/block/0000000001343c3eec1564c0a664c12a0a931a79a371f844af09609724f9b8af/txids and returns the txids, the block/x/status endpoint returns an error.

![image](https://github.com/mempool/mempool/assets/11994884/c6964631-7185-43ab-a36a-778056aeba2b)

**Comment by nymkappa** [comment]
As mentioned in the support channel this endpoint requires esplora backend
