### ISSUE TITLE
Mempool graph tooltip overflow

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4359]
This overflow may occur when skimming through the mempool graph.

<img width="294" alt="Screenshot 2023-11-11 at 12 04 54" src="https://github.com/mempool/mempool/assets/8561090/36149cda-2f9e-4a93-9389-7b90fea7dc5e">

**Comment by ncois** [comment]
How should this be fixed? Slightly increasing the width of the tooltip is a simple solution but it does not prevent the overflow to happen again

There is another overflow on the incoming tx graph tooltip: 
<img width="314" alt="image" src="https://github.com/mempool/mempool/assets/46578910/f7be7b48-acb2-4484-a801-b0cae582a922">
