### ISSUE TITLE
Outspends API is called twice from the Transaction page

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4360]
Opening any random Transaction and 2 outspends requests are triggered. This should be optimized.

```
INFO - handle GET /tx/198975a89cc20152051a5c9b65f894a6ebf32c217ef5324a9c1ebf4d6798eb12/outspends
INFO - handle GET /tx/198975a89cc20152051a5c9b65f894a6ebf32c217ef5324a9c1ebf4d6798eb12/outspends
```

**Comment by mononaut** [comment]
Yeah, the bowtie diagram and the transaction list both make separate requests.

I suppose we can either fetch outspends further up the component hierarchy, or add some sort of stateService caching layer to reuse the result of the first request.
