### ISSUE TITLE
Hide the white average line on the 2H dashboard

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4362]
* It doesn't add any information here.
* Also the white dashed line representing the throughput limit is gone

<img width="557" alt="Screenshot 2023-11-12 at 15 12 02" src="https://github.com/mempool/mempool/assets/8561090/86088c51-8e5e-4396-a727-ca01696063a5">

**Comment by nymkappa** [comment]
For reference: https://github.com/mempool/mempool/pull/3923
