### ISSUE TITLE
Mempool graph isn't a graph, it's just a rainbow.

### ISSUE THREAD

**Issue by nostitos** [mempool/mempool#4365]
![image](https://github.com/mempool/mempool/assets/48504624/20094c6f-43b8-4c86-a269-77431cddc71a)

What are people supposed to understand from this?

The problem is there isn't enough variation in the top part for us to see it.

Some solution would be to show the Y axis as a log, or show a top range that show a variation over the X period.

Right now the chart shows a span of 2h, only about 12 blocks get mined in that period and the flow of new transaction is somewhat constant.

Given that, the chart should show only the mempool's top 10mb from tip.

**Comment by junderw** [comment]
That's interesting. The height of the sum would be constant (10MvB) but the color composition would change with the flow of transactions.

If tons of transactions flow into a feerate well below the top 10MvB it would essentially be invisible though...

I do agree that during times of congestion that graph is near useless as a quick glance of anything.

**Comment by nostitos** [comment]
It's not so much high congestion, it's that there should always be about 300mb even 1 GB worth of transaction down to as low as 1sat/bytes waiting.  For example; Would 250 mb of transactions waiting at 1 sat/bytes be useful to care about when there's 50mb in a spectrum between 5 and 50 sats?

Assuming most people want their TX to fill in the next day, There's 144 blocks over a day and should be around half that are fresh incoming TX.   So we should now expect much more than 70 1mb blocks to fill in a 24h period.   Looking at 70mb over a 24h period should draw some trends but not 300mb over 2h.

**Comment by junderw** [comment]
You seem to be making a lot of assumptions as to what this graph should be used for...

The full page graph has a bunch of filters to check the various fee levels individually, and can fill most use cases.

If the point of the front page "at a glance" graph is to show a graph that gives you a quick intuition about "the network is congested" or "not" then I think just making it log should be enough.

**Comment by junderw** [comment]
If the point of the graph is "to tell the person who sees "248,000 transactions" (above the graph) a rough idea of which fee brackets a large portion of those transactions are located." then it could be argued that the graph already fills its purpose.

I do think it's a bit hard to intuit anything from the graph as-is, but to take it a step further and say "we must be able to tell how much fee we must pay by looking at the front page graph" I think that's stepping into "wrong tool for the job" territory.

**Comment by nostitos** [comment]
I make the assumption that the frontpage dashboard is a way to get a quick overview that is useful for most who want to do time-cost-benefit of choosing a fee over another. 

I still use another graph daily which shows the same thing but has a selectable X time span and a full screen Y axis. I usually put it at 8h then zoom out to a 2 week to see bigger picture.  https://jochen-hoenicke.de/queue/#BTC,2w,weight

Current chart would be the equivalent of looking at a 1min bitcoin price chart with an y axis that start at 0$ instead of min-max in that range.

I've wrote elsewhere that this chart should be able to be clicked and expanded,  Of just a link to /tv/ that has the full mb range would do.

mempool.space/tv


What I like to see are the notches down when a block is found, to asses how frequent they were.  Would be great to maybe make each block have at least 1 pixel of effect on the chart.   The current chart is about 200 pixel for 300mb
![image](https://github.com/mempool/mempool/assets/48504624/0185e3a0-ce19-4623-828a-7943cbeec732)

**Comment by junderw** [comment]
You're starting to go all over the place with semi-suggestions/ideas that aren't clearly stated.

1. The graph on the front page is not useful to "at a glance" glean any information.

That's the only point that you've made clear, and I agree.

- The next step would be to argue, clearly, what SHOULD a user be able to glean from looking at it.
- Then think of concrete ways the graph could be changed to make that info apparent. Each suggestion should serve the purpose of that goal.

> should be able to be clicked and expanded

Adding functionality to an "at a glance" image is not good UX.

> just a link to /tv/ that has the full mb range would do.

It would be better to link to https://mempool.space/graphs/mempool which actually has functionality (like changing the time span or hiding fee levels). The `/tv` endpoint is also just a larger "at a glance" image.

**Comment by mononaut** [comment]
> What are people supposed to understand from this?

The dashboard chart mainly shows mempool *composition*, i.e. how much of the mempool is occupied by each range of fee rates.

That matches up well with the other metrics shown in that widget (total memory usage, and total number of transactions), but you're right that when the mempool is full, the change over time isn't very visible.

> Some solution would be to show the Y axis as a log, or show a top range that show a variation over the X period.

A log y-axis might be a good solution to show the whole mempool composition while also making recent changes more visible, although lots of people find log charts confusing.

I'm not sold on showing just the top slice of the mempool. As @junderw points out, the height would just be constant, and I think the resulting chart would be unintuitive/hard to read.

Other options might be:
  - increase the default time period (I usually find the 24H or 1W chart more interesting than the 2H anyway).
  - switch the y-axis to count fees instead of vbytes (this has a similar effect to a log axis), although this doesn't match up so well with the Memory Usage and Total Unconfirmed fields.

**Comment by softsimon** [comment]
We solved this by removing the "rainbow" from the dashboard and replaced with the next block visualization. The full mempool graph is on it's own graph page where it makes more sense.
