### ISSUE TITLE
Can't Ctrl+F search for addresses on transaction page - space/line-break in address

### ISSUE THREAD

**Issue by 0xB10C** [mempool/mempool#4367]
When Ctrl+F searching for e.g. `3QYepbTj2Dpi8Ef2usYhHBb3SNju5pdkxJ` (address associated with the first input) on https://mempool.space/tx/c9b5719131bfeac6378749243731c5e70f1ce56deabb7006a2b6539710866420 it does not find it as there's a space or line-break in the address. Removing a few characters at the end of the search helps. However, someone not aware of this might come to the conclusion that a transaction does not spent or pay to an address. This can be fixed by removing or changing the following truncation: 

https://github.com/mempool/mempool/blob/28113d11411efd1a11a324bd94976bb86f877b3c/frontend/src/app/components/transactions-list/transactions-list.component.html#L71C1-L73C29

**Comment by softsimon** [comment]
Yes, after we implemented ellipsis on addresses to handle truncating to all screen sizes, the ability to seach and find was lost. https://github.com/mempool/mempool/pull/2914
