### ISSUE TITLE
Verify my address and fix any issues or errors please 

### ISSUE THREAD

**Issue by Josemoe** [mempool/mempool#4372]
https://github.com/Josemoe/mempool/blob/7b108a6e852c2e24c6784fc4181b2ca58f407ffb/bc1qxhmdufsvnuaaaer4ynz88fspdsxq2h9e9cetdj%20

**Comment by softsimon** [comment]
This is not your address.

**Comment by Josemoe** [comment]
> This is not your address.

Lol it's only been dormant for 13 years

**Comment by softsimon** [comment]
> > This is not your address.
> 
> Lol it's only been dormant for 13 years

It's not dormant. It's active and belongs to a mining pool.

**Comment by Josemoe** [comment]
Well who sees it first and holds the keys is the owner not your key not  your crypto 



No yave no crypto
