### ISSUE TITLE
Basic inscription support

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4376]
This is a rough mockup. A textarea with monospaced text.

<img width="1261" alt="Screenshot 2023-11-14 at 18 38 09" src="https://github.com/mempool/mempool/assets/8561090/57a8c3d0-8285-4b3b-94c0-b057e4570eef">

**Comment by Retropex** [comment]
Bad idea, it's spam why give them legitimacy?

**Comment by junderw** [comment]
What would we do when a MIME type that is not text appears?

**Comment by softsimon** [comment]
> Bad idea, it's spam why give them legitimacy?

Fair complaint. But this would only be displaying raw data just like we display OP_RETURN, and nobody will notice this except those actually looking at their own transactions containing this info.

**Comment by junderw** [comment]
Also, unlike OP_RETURN there's really no limit on the size........ so maybe we could limit it to `text/plain` and `application/json` and truncate anything after 80 characters.

**Comment by eragmus** [comment]
> Bad idea, it's spam why give them legitimacy?

No such thing as spam, in reality. If a transaction pays a fee, then it is valid and 'good for bitcoin' to pay fees to help miners offset the exponentially declining block subsidy. 

The whole point of bitcoin is it is a censorship resistant network, a free market money, where you can't stop people using their bitcoin however they choose.

Before ordinals, fees were very low and security budget was not being addressed by normal transaction demand.

**Comment by eragmus** [comment]
> > Bad idea, it's spam why give them legitimacy?
> 
> Fair complaint. But this would only be displaying raw data just like we display OP_RETURN, and nobody will notice this except those actually looking at their own transactions containing this info.

Please don't give in to censorious bitcoiners who do not understand bitcoin. (see my previous comment)

**Comment by junderw** [comment]
TODO for whoever works on this:
- [ ] Look into the possibility space of inscriptions and decide on what / how much should be shown.

My thoughts:
- Do not display images, videos, sounds, etc. (liability issues)
- Display only a limited amount of text for a small set of MIME types
- Perhaps every inscription should at least show its MIME type
