### ISSUE TITLE
Show mining related data on transaction page

### ISSUE THREAD

**Issue by orangesurf** [mempool/mempool#4422]
### Description

Show information from the block audit view on individual transaction pages.

### Problem to be solved

There are interesting flags in the block audit which are not currently shown on the transaction page. These flags could add useful context, for example whether a pool included a 

### Proposed solution

Add mining related tags to the transaction page.

Example with recent high fee transaction
- Show that transaction was seen in mempool prior to being mined
- Show that transaction was in the expected block

<img width="1216" alt="image" src="https://github.com/mempool/mempool/assets/91332210/78277b40-8f0c-4bc2-bc8e-9b4626cb9f95">

Example with recent censored transaction
- Show that transaction was seen in mempool prior to being mined
- Show that transaction was delayed (not in expected block)
<img width="1216" alt="image" src="https://github.com/mempool/mempool/assets/91332210/c2df55ff-e464-4a70-bc84-c0753c4837a0">

Example of an added transaction (Luxor mined 3.94MWU tx)
- Show that transaction was not seen in the mempool prior to mining
- Show that the transaction was added (not expected in the mempool.space next block template)
- Show the mining pool that mined the transaction (could be added to all transaction pages) 

<img width="1216" alt="image" src="https://github.com/mempool/mempool/assets/91332210/107988ce-cbfb-4804-8120-34f75c00d123">

Example of an accelerated transaction (k3tan 1 sat/vB demo)
- As above but also show that transaction was accelerated

<img width="1185" alt="image" src="https://github.com/mempool/mempool/assets/91332210/f1a36543-1541-4b17-b03a-dff5a8053109">

The tags could link to relevant pages
- "Delayed" tag could link to the block audit for the block in which it was expected (by mempool.space)
- "Added" tag could link to the block audit for the block in which it was included 
- "Accelerated" tag could link to details of the acceleration (inc. amount paid)

**Comment by AjUnstoppable** [comment]
hi, signed up for accelerator long ago but its still showing me as being on the waitlist. how much longer will it take? as one of my transaction is stuck from past 3+ days now due to low gas n i really need to access funds from my wallet. Kindly please help urgently

**Comment by orangesurf** [comment]
builds on  https://github.com/mempool/mempool/issues/513

**Comment by wiz** [comment]
@mononaut this would be cool to have
