### ISSUE TITLE
Collapse/expand toggle for the RBF History view

### ISSUE THREAD

**Issue by mononaut** [mempool/mempool#4423]
When the RBF history for a transaction is very large or complex, it takes up way too much space on the transaction page:

![mega-rbf](https://github.com/mempool/mempool/assets/83316221/c09d750c-8acf-4452-b75f-fd6c843a79b6)

We should cap the maximum height rendered by default, and add a "Show more" or "Show all" toggle to reveal the full diagram.

**Comment by natsee** [comment]
@mononaut I can take this one if you want
