### ISSUE TITLE
Change sponsor twitter images to use 200x200 instead of 400x400

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#443]
We can reduce the About page loading time by around 50% simply by changing changing:

https://pbs.twimg.com/profile_images/1362785873947893763/r_tpTjXl_400x400.jpg -> `18119` bytes

https://pbs.twimg.com/profile_images/1362785873947893763/r_tpTjXl_200x200.jpg -> `8383` bytes

**Comment by softsimon** [comment]
200x200.jpg is already what is being used for all twitter images. Github images are of a different sizes though.

**Comment by wiz** [comment]
so `imageUrl` in the database is not used?

**Comment by wiz** [comment]
hmm, okay must have been my mistake
