### ISSUE TITLE
[[Feature request]] Mark adresses or transactions as favorite on user web browser

### ISSUE THREAD

**Issue by kami104** [mempool/mempool#4434]
### Description

The idea is to have the possibility to save a favorite address or transaction into the user browser so those can be consulted easily. It would be a good idea the user could add a label to that favorite TX or address to identify it in the future.

### Problem to be solved

With a feature like that, the user won't need to search the address or TX on the wallet every time he wants to check it on the mempool.

**Comment by wiz** [comment]
I don't understand, how is this different from using your browser's bookmark feature?

**Comment by kami104** [comment]
You are right. Actually there is not.
