### ISSUE TITLE
Difficulty adjustment chart - Format the hashrate and difficulty

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#4442]
We could use power of ten in this chart https://mempool.space/graphs/mining/hashrate-difficulty#all

<img width="418" alt="Screenshot 2023-11-28 at 2 14 19 PM" src="https://github.com/mempool/mempool/assets/9780671/65a53a04-52d0-48c2-8a76-f407cc53504c">

**Comment by ncois** [comment]
I can take this one. For now it looks like power of ten are already used on mobile, do you want to use them on all devices?

<img width="423" alt="Screenshot 2023-11-29 at 10 21 22" src="https://github.com/mempool/mempool/assets/46578910/cebfba24-7f1d-44e5-87f3-3af3cbac107b">

**Comment by nymkappa** [comment]
> I can take this one. For now it looks like power of ten are already used on mobile, do you want to use them on all devices?

Oh okay I forgot about that. **I think yes it would make sense to use this format on all devices yes.** Being so accurate (display the exact H/s value) is useless, plus it's an estimated value which makes it even more irrelevant.
