### ISSUE TITLE
RTL bug (Sign in popup)

### ISSUE THREAD

**Issue by EZ0010** [mempool/mempool#4456]
### Description

Hi, I reported this on X and thought I should make a github issue.

on RTL languages UI there is a bug that shows a sign in popup and miss the ability to use the website.

#### Version

v3.0.0-dev [[62c4af1a](https://github.com/mempool/mempool/commit/62c4af1a)][4f93e165]

### Screenshots

<img width="1792" alt="Screenshot 2023-11-30 at 11 02 33 AM" src="https://github.com/mempool/mempool/assets/75021359/74bb7354-08d2-4f62-8d13-4c5ec6ac6531">

**Comment by nymkappa** [comment]
We did not work at all on RTL support for the new dashboard. Will create a different issue for checking/fixing all RTL issue on all the new pages instead.
