### ISSUE TITLE
Copy button is not showing on mobile portrait (iPhone 13 mini)

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#4477]
![image](https://github.com/mempool/mempool/assets/9780671/95a79f38-211c-458a-88cd-97bf1630a260)

It does show in landscape

![image](https://github.com/mempool/mempool/assets/9780671/9830ab1c-7713-4ee1-bb3d-d33c6c1f765e)

**Comment by natsee** [comment]
Hiding the copy button on small screen seems to be intentional, in `block.component.html` line 45:
`<app-clipboard class="d-none d-sm-inline-block" [text]="block.id"></app-clipboard>`

But it looks like there is no need to hide it indeed.

**Comment by nymkappa** [comment]
> Hiding the copy button on small screen seems to be intentional, in `block.component.html` line 45: `<app-clipboard class="d-none d-sm-inline-block" [text]="block.id"></app-clipboard>`
> 
> But it looks like there is no need to hide it indeed.

Yeah there is more than enough space to show it, it's a very useful feature that should always be visible.
