### ISSUE TITLE
Mining Pool Overview List

### ISSUE THREAD

**Issue by orangesurf** [mempool/mempool#4492]
### Description

The all time mining pool list doesn't contain all the data

#### Version

[88f61761](https://github.com/mempool/mempool/commit/88f61761)

### Steps to reproduce

Search [the all time list](https://mempool.space/graphs/mining/pools#all) for OCEAN, 0 results.
Search [the 1 month list](https://mempool.space/graphs/mining/pools#1m) for OCEAN, 1 result.

### Expected behaviour

I would expect OCEAN to appear in the all time data.

### Actual behaviour

It is not included, suggesting that the all time data does not include data in the 1 month view.

### Screenshots

1 month
<img width="981" alt="image" src="https://github.com/mempool/mempool/assets/91332210/2847d363-5e98-492a-b13d-392dce66c1ee">

All time
<img width="981" alt="image" src="https://github.com/mempool/mempool/assets/91332210/85c28e2c-2d87-4327-ba01-8746f403a77a">

**Comment by nymkappa** [comment]
It's probably a cache issue. For some reasons some server returns a weird expires time.

<img width="922" alt="image" src="https://github.com/mempool/mempool/assets/9780671/bf206b34-7a87-48a8-aaa8-9f3b7224371c">

**Comment by nymkappa** [comment]
Fixed by @Emzy , this was an ops issue. If you noticed similar discrepancies please dm @Emzy directly.
