### ISSUE TITLE
while exploring local mempool, my electrs server leaks sensitive scripthash values

### ISSUE THREAD

**Issue by 4ezb2** [mempool/mempool#4496]
### Description

electrs leaking privacy sensitive scripthash values into logs, while exploring self-hosted mempool.space in the browser

#### Version

ubuntu server 20.4, mempool 2.5, and electrs server 10.1

### Steps to reproduce

1. Connect to your electrs server in self-hosted mempool.space backend
2. Explore self-hosted mempool.space in browser
3. For example, click on transaction history of an address
4. See error message in electrs logs

### Expected behaviour

no leak of privacy sensitive scripthash values into logs

### Actual behaviour

leak of privacy sensitive scripthash values into logs

#### Additional info, logs:
> ```
> INFO your wallet uses less efficient method of querying electrs, consider contacting the developer of your wallet. Reason: blockchain.scripthash.get_history called for unsubscribed scripthash: 123abc
> ```

The same bug was reported for sparrow wallet [issue724](https://github.com/romanz/electrs/issues/724)

Many thanks for looking into this issue!

**Comment by softsimon** [comment]
When you are running your local Mempool, you are probably running [`romanz/electrs`](https://github.com/romanz/electrs)

Or are you referring to https://github.com/mempool/electrs ?

The bug report has to go to either of those. Our backend requesting script hashes can't be reponsible for the log outputs in the Electrum Server backend.

**Comment by 4ezb2** [comment]
@softsimon thanks for the fast response. Sorry for not being clear enough, yes my electrs server is /romanz/electrs, and I'll report the bu there then.

**Comment by 4ezb2** [comment]
@softsimon thanks for the fast response. Sorry for not being clear enough, yes my electrs server is /romanz/electrs, and I'll report the bug there then.
