### ISSUE TITLE
Add loading animation for table rows when infinite scroll is loading new rows

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#45]
Please add this when infinite scroll is loading more rows

<img width="995" alt="Screen Shot 2020-03-08 at 18 00 10" src="https://user-images.githubusercontent.com/232186/76159736-b9346a80-6166-11ea-8cff-2d9e2249a040.png">

**Comment by softsimon** [comment]
It already exists actually, but starts the loading before scrolling down and loads quite fast so it's never visible when scrolling slowly.
