### ISSUE TITLE
the name of the "US dollar" when mempool in Arabic

### ISSUE THREAD

**Issue by EZ0010** [mempool/mempool#451]
### Description

When you use mempool Arabic version it shows the $ with "US" after it, and this makes some issues with the UI as the text will be bigger and it won't fit in the field in small screen devices. I don't think it is necessary to add US next to $ sign as it is obvious the meaning is the US dollar.
I tried looking up the transifex project but didn't find the string, I didn't find this issue with Persian language.

#### Version

v2.2.0-dev [37409800]

### Screenshots

Here is how it looks like on a phone:
as you can see the "US" is after the $ sign and also the extra space made some of the text out of the UI box.
<img width="250" alt="Screen Shot 2021-04-16 at 2 27 46 PM" src="https://user-images.githubusercontent.com/75021359/115018767-f36f5000-9ec0-11eb-8bc2-c142b1c9c5aa.png">

here is how it looks like after I removed the "US" and the space:
<img width="246" alt="Screen Shot 2021-04-16 at 2 28 04 PM" src="https://user-images.githubusercontent.com/75021359/115019023-46e19e00-9ec1-11eb-9809-5c66e08c9af5.png">

**Comment by softsimon** [comment]
It is using the local language style of foreign currencies automatically so I think that should remain. When we add other currencies like the Australian dollar it might make sense to separate them.

So the bug here is the text overflow on certain screen sizes. Not sure what the best solution is to fix it.

**Comment by softsimon** [comment]
@MiguelMedeiros is now working on solving this overflow issue in #468
