### ISSUE TITLE
Can not search for a block by hash on signet

### ISSUE THREAD

**Issue by natsee** [mempool/mempool#4529]
On signet, using the search bar to search for a block by hash fails. See below with block [175513](https://mempool.space/signet/block/000000fff24a5235cf5fced785f7c208bd4e519b8ef32c5cef8fae18c3e24fd7): 

<img width="501" alt="Screenshot 2023-12-27 at 15 49 44" src="https://github.com/mempool/mempool/assets/46578910/d8f92479-e48c-4a86-85c2-f542fe9fc4e2">

When proceeding to the search:

<img width="1083" alt="Screenshot 2023-12-27 at 15 52 22" src="https://github.com/mempool/mempool/assets/46578910/326ec300-73c2-4b82-aa3d-2f463195199c">

This happens because the block hash regex used in the search form component requires 8 leading zeroes to match, whereas block hashes in signet usually have 5 or 6 (difficulty around 0.003). 

A solution could be to set `regexBlockhash = /^[0]{5}[a-fA-F0-9]{59}$/` on signet.

**Comment by softsimon** [comment]
There's a work in progress to fix this here https://github.com/mempool/mempool/pull/2401
