### ISSUE TITLE
CPFP only showing 1 child instead of all

### ISSUE THREAD

**Issue by Czino** [mempool/mempool#4536]
### Description

I saw a transaction with many outputs, 2 of those have been already used in a child transaction. I saw that the effective fee rate did not update, when the second output got spent. Digging a bit deeper, I found that only one child is considered

#### Version

node205.fra.mempool.space (v3.0.0-dev) [[30da419f](https://github.com/mempool/mempool/commit/30da419f)] - (v1.0.0) [04fe8ca6]

### Steps to reproduce

- Broadcast a transaction with 2 or more outputs
- while parent tx stays unconfirmed:
-- use 1 output for CPFP
-- use a second output for another CPFP

### Expected behaviour

The CPFP info should regard all child transactions

### Actual behaviour

Only one child transaction is shown

### Screenshots

<img width="956" alt="image" src="https://github.com/mempool/mempool/assets/42438775/bc6c96dc-0594-4152-8238-1cf40ca71609">

**Comment by mononaut** [comment]
yes, that's how CPFP works in Bitcoin Core's block construction algorithm, so this is actually correct behavior.

Each "cluster" of related unconfirmed transactions can only be sponsored by a single "root" child transaction.

If you make two separate CPFP children by spending different outputs, only the one with the highest "ancestor feerate" will actually contribute to the effective fee rate of the parent.

**Comment by Czino** [comment]
Ok, that's interesting, I wonder if miners still rely on this algorithm. If I was mining I'd consider all child TX to rake in those fees before somebody else mines it.

Closing issue as this is standard behaviour.
