### ISSUE TITLE
Searching for Liquid assets is broken

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4588]
If you are on liquid.network and searching for an Asset like Tether USDt ( ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2 ) you will only be suggested a TXID.

**Suggested solution:**

When the user is on the Liquid explorer, use the local cache of `assets.minimal.json` that is always loaded to find out if it's an asset or not, and suggest it as first search result under a new category called Liquid Asset.

**Comment by Billym45** [comment]
Just now learning program how to I close out any of my accounts if I lost
all the info.
