### ISSUE TITLE
Feature request: block feerate versus time graph

### ISSUE THREAD

**Issue by starius** [mempool/mempool#4590]
### Description

The main chart https://mempool.space/graphs/mempool shows distribution of feerate in the mempool at a point in time. I'm interested in additional chart, showing feerate in past blocks.

### Problem to be solved

My method of guessing feerate for a non-urgent transaction when sending is to look at feerate during **dips** in the mempool fee chart past week. This is a more complicated way of just checking feerate in blocks. A chart that shows exactly this feerate would be more convenient. 

### Proposed solution

I'm interested in a plain chart y = feerate(time), which depends on data from blocks, not from mempool.
The data as already available, each block has median mempool on its page.

Since it doesn't depend on mempool, it can be shown on this page: https://mempool.space/mining or on its own page. Also on the main page, ideally.

#### Additional info

In addition to the main line, the following areas can be highlighted with a background color:
 - 95% distribution of feerate in a block
 - whole fee span

**Comment by nymkappa** [comment]
You mean this? https://mempool.space/graphs/mining/block-fee-rates

**Comment by starius** [comment]
Yes! I was not aware of this chart. Thank you!

Can it be drawn with lines, not with bars? Like this https://mempool.space/graphs/mining/block-fees

**Comment by nymkappa** [comment]
> Yes! I was not aware of this chart. Thank you!
> 
> Can it be drawn with lines, not with bars? Like this https://mempool.space/graphs/mining/block-fees

No it cannot. But based on your previous description, it looks like to me you can simply pick only one filter and that would do the trick. For example:

<img width="1429" alt="image" src="https://github.com/mempool/mempool/assets/9780671/bafb513d-0962-454a-946e-3faaf9a0467a">
