### ISSUE TITLE
Block ETA is inaccurate in the beginning of each epoch

### ISSUE THREAD

**Issue by starius** [mempool/mempool#4593]
### Description

Block time estimations are ~30 minutes, which is not realistic.

#### Version

node204.fra.mempool.space (v3.0.0-dev) [6553de53] - (v1.0.0) [04fe8ca6]

### Steps to reproduce

Open [mempool.space](https://mempool.space/) in the beginning of an epoch and see that block time estimation is not accurate.

### Expected behaviour

It should look for more blocks in the past to estimate current hashrate and block ETAs.

### Actual behaviour

I think, it estimates hashrate and block ETA by looking only into blocks since current epoch start. If an epoch happens to start with longer that usual block delays (say 30 minutes), it is using this as an estimate until more blocks are mined.

### Screenshots

![Screenshot 2024-01-20 at 12-01-43 mempool - Bitcoin Explorer](https://github.com/mempool/mempool/assets/920155/1dd3076a-6909-4bc2-8c4b-81f8ee73346f)

#### Device or machine

Firefox on Linux.

**Comment by Muniru0** [comment]
@nymkappa please has this issue being resolved.
