### ISSUE TITLE
Implement support to view UTXO details and scripts

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#46]
Example from chainflyer.bitflyer.jp viewing TX scripts

<img width="1160" alt="Screen Shot 2020-03-08 at 20 16 19" src="https://user-images.githubusercontent.com/232186/76161762-bb53f480-6179-11ea-91b0-d04699fc500d.png">

**Comment by bubersson** [comment]
As softsimon asked in #144, I think I'd just add this under Details, something like
<img width="1440" alt="utxo-scripts" src="https://user-images.githubusercontent.com/982922/97098901-8086ca00-163f-11eb-9dea-3bfdf196c8e9.png">

This is for viewing single transaction only so there's a space even if there's a bunch of inputs/outputs.
