### ISSUE TITLE
Mempool.space hidden service isn't reachable

### ISSUE THREAD

**Issue by RequestPrivacy** [mempool/mempool#4600]
### Description

Going to mempool.space the Tor Browser informs about the .onion site of the page. Clicking it just leads to a connection timeout for mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion. This is ongoing and doesn't seem to be a short lived issue. Can you confirm your hidden service is reachable? 

#### Version

-

### Steps to reproduce

-

### Expected behaviour

-

### Actual behaviour

-

### Screenshots
-

#### Device or machine

-

#### Additional info

-

**Comment by orangesurf** [comment]
I can confirm that the tor service is reachable 

<img width="1512" alt="image" src="https://github.com/mempool/mempool/assets/91332210/577cbe3d-3110-41f6-b6ea-52f122000793">
