### ISSUE TITLE
Channel search results showing up during TX search

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4606]
This is due to the channel search regex that clears out characters turning

`a5f4fa1e76c503ee6b07660e530ac24b6e03daae894c5cc8c1e1e3d4d8c2eff6`

.. into a search for `LIKE 5%`

<img width="406" alt="Screenshot 2024-01-23 at 17 37 47" src="https://github.com/mempool/mempool/assets/8561090/f9af9184-9464-4f10-990d-f18db3570836">

**Comment by afahrer** [comment]
Hello, I'd like to work on this issue if possible.

**Comment by afahrer** [comment]
Opened PR #4609

**Comment by softsimon** [comment]
Fixed in https://github.com/mempool/mempool/pull/4609
