### ISSUE TITLE
Add new API documentation.

### ISSUE THREAD

**Issue by MiguelMedeiros** [mempool/mempool#461]
### Description

Add new API documentation page with live `mempool-js` examples.

**Comment by wiz** [comment]
We'd like to include this as part of the upcoming v2.2.0 release - do you have a rough idea when it will be ready? :)

**Comment by MiguelMedeiros** [comment]
I'm finishing the new responsive layout today and I´ll start the API docs tomorrow! 
I´ll give you a better prediction as soon as I start! :)

**Comment by MiguelMedeiros** [comment]
I'll start the API docs today! :)
