### ISSUE TITLE
[bug] CLN Currently Unusable as Backend

### ISSUE THREAD

**Issue by kn0wmad** [mempool/mempool#4634]
### Description

CLN no longer able to display current Lightning data due to Mempool needing a compatibility update

#### Version

2.5

### Steps to reproduce

Use CLN as Lightning backend, visit Lightning tab, witness that data is way out of date

### Expected behaviour

CLN compatibility

### Actual behaviour

Lack thereof

#### Device or machine

StartOS

#### Additional info

Apparently already fixed in `master`, 2.5.1 hotfix supposedly on the way?

**Comment by nymkappa** [comment]
What CLN version are you using?

**Comment by kn0wmad** [comment]
23.11.2 - issue already confirmed by Wiz and Simon - just need the fix released

**Comment by Sjors** [comment]
Same issue here. My CLN data seems to be from around 2023-05-10.

Running CLN v23.11.2 and Mempool v2.5.0 as manual install.

Haven't investigated the issue more, since the above comments suggest it's a known issue and a fix exists. I'll wait.

**Comment by kn0wmad** [comment]
CC @softsimon @wiz

**Comment by wiz** [comment]
does this reproduce with current master?

**Comment by kn0wmad** [comment]
@softsimon said the fix was in master a month ago.  We've been waiting for a hotfix release to update the package for StartOS.

**Comment by softsimon** [comment]
The fixes are in the following commits:

02f361af7334ec8e0df6206c15d328fa7807f5cf
caa8cfbc0e5cf1fba5dc9ca82b0ec3dd3e350fc9

**Comment by kn0wmad** [comment]
> The fixes are in the following commits:
> 
> [02f361a](https://github.com/mempool/mempool/commit/02f361af7334ec8e0df6206c15d328fa7807f5cf) [caa8cfb](https://github.com/mempool/mempool/commit/caa8cfbc0e5cf1fba5dc9ca82b0ec3dd3e350fc9)

Is a release pending?  If not, would a hotfix release be considered?

**Comment by knorrium** [comment]
We'll tag a patch release after these are merged

https://github.com/mempool/mempool/pull/4678

https://github.com/mempool/mempool/pull/4679

**Comment by knorrium** [comment]
@kn0wmad 2.5.1 has been published to dockerhub. Can you try it?

**Comment by Sjors** [comment]
Just updated my manual install on Ubuntu 23.10 to `v2.5.1`.

Looks like it's working again:
```
Mar 01 11:14:50 sjimmie npm[857823]: Mar  1 11:14:50 [857823] INFO: <lightning> [Lightning] Building complete channels from clightning output. Channels processed: 720 of 98090
```

**Comment by kn0wmad** [comment]
Looking good, closing as fixed
