### ISSUE TITLE
UTXO method 404 not found 

### ISSUE THREAD

**Issue by TehnobitSystems** [mempool/mempool#4644]
Hello.
Please tell me what is the reason for the error.
When using the method:
https://site.url/api/address/1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY/utxo
I get a 404 error
However, other methods, for example:
https://site.url/api/address/1wiz18xYmhRX6xStj2b9t1rwWX4GKUgpv/txs
works properly without errors

Ubuntu 22.04
Bitcoin Core 25.0
Mempool v2.5.0
Fulcrum 1.9.8

**Comment by softsimon** [comment]
Because the address/utxo endpoint only exists in `mempool/electrs` and hasn't been ported to the nodejs API when using Electrum Server from romanz or Fulctrum like in your case. Because we don't use the /utxo endpoint on Mempool.

So the API is not 100% matching between the different backends.

**Comment by TehnobitSystems** [comment]
@softsimon Thanks for the details. We deployed mempool/electrs, but the problem persisted. The above method continues with 404 error

**Comment by softsimon** [comment]
> @softsimon Thanks for the details. We deployed mempool/electrs, but the problem persisted. The above method continues with 404 error

Then the deployment or route config can't be correct.

If you go to this URL you can see it works with latest mempool/electrs or blockstream/electrs

https://mempool.space/api/address/3L8Ck6bm3sve1vJGKo6Ht2k167YKSKi8TZ/utxo
https://blockstream.info/api/address/3L8Ck6bm3sve1vJGKo6Ht2k167YKSKi8TZ/utxo

**Comment by TehnobitSystems** [comment]
@softsimon Please tell me how to configure the routes correctly? We use the out-of-the-box configuration as is for mempool/electrs and mempool
