### ISSUE TITLE
Goggles do not catch certain coinjoins

### ISSUE THREAD

**Issue by Kruwed** [mempool/mempool#4645]
### Description

Some coinjoins using the WabiSabi coinjoin protocol are not being noticed by the goggles.

#### Version

Live mempool.space - node205.va1.mempool.space (v3.0.0-dev) [[6553de53](https://github.com/mempool/mempool/commit/6553de53)] - (v1.0.0) [d69e4ecb]

### Steps to reproduce

I'm not sure exactly since some coinjoins are correctly detected, but not others.

In this screenshot, 4 out of the 6 large WabiSabi coinjoin transactions waiting to be included in the block are detected by the goggles -

![firefox_nPJU7JuDNQ](https://github.com/mempool/mempool/assets/118238055/f451eaff-12cb-44a2-b477-b3501b742890)

Noticed by goggles:
a1a5b65047560a07815a34fc7f5b7a547aa056c0b82cfab9bab8201f8f0af1e1
09aac04a5f1e69df7ecb0ebda07f5e5d25015e1d7f1579f031d1568ec3ece534
d331ba87bc952ee8cb92915b5ed49dc7e8cbbda128496518f043b497678716e0
d6f8e08c20e31b1336654860f9ca9eea225d95ff946ae2d43d70f8330defff54

Not noticed by goggles:
302530adbffe6965b54740ff45af2068f443d5e01bfc3529ab4e80c890a5e7bb
5355022d9c520d3f3017b6d28b174b97e986653784366f9c7a16fde69033e397

### Platform

Windows/Firefox

**Comment by mononaut** [comment]
Thanks for the issue!

The filter currently requires that coinjoins involve zero address reuse (as a heuristic to disqualify some other multi-input-multi-output transaction types).

Since wabisabi apparently does permit address reuse on the input side, we should probably relax that rule a little.
