### ISSUE TITLE
Inscription not detected.

### ISSUE THREAD

**Issue by Retropex** [mempool/mempool#4677]
### Description

I run Bitcoin Knots 25.1 with datacarrier=0 which means that the inscriptions are never in my mempool however the goggles do not detect them in the blocks, the OP_RETURN and the stamps (fake pubkey) are correctly detected.
#### Version

[d921c3f](https://github.com/mempool/mempool/commit/d921c3fdc22dd228507797a701b78dd56f52530f)

### Steps to reproduce

use goggle to see inscription on blocks.

### Expected behaviour

See what txs are inscriptions.

### Actual behaviour

Are not detected.

### Screenshots

you can see it in real time [here](https://orangepill.ovh).

#### Device or machine

debian x86.

**Comment by softsimon** [comment]
There is a new mempool-config.json backend config you need to set.

`"GOGGLES_INDEXING": true,`

**Comment by Retropex** [comment]
Is this option already supported with docker?

**Comment by Retropex** [comment]
fixed in https://github.com/mempool/mempool/pull/4889
