### ISSUE TITLE
MariaDB necessary?

### ISSUE THREAD

**Issue by jobeirne-nydig** [mempool/mempool#4691]
Is use of a MariaDB backend necessary, or will any MySQL-compatible backend suffice?

Is there a particular reason that mempool.space uses MariaDB?

**Comment by softsimon** [comment]
It's used for the mempool statistics graphs.
It's used for all historical block data (partially indexed as default).
It's used for all Lightning network data to be swiftly presented and searchable.

It's possible to set the DATABASE -> ENABLED to `false` and run without a database completely. But some features won't work like the historical mempool or the Lightning explorer.
