### ISSUE TITLE
"First seen" keep resetting itself to "Just now"

### ISSUE THREAD

**Issue by Seccour** [mempool/mempool#470]
### Description

When we look at a specific unconfirmed transaction, the "First seen" field always reset to "Just now" every time we open the page or reload it.

#### Version

v2.1.2 (846d7e90)

### Steps to reproduce

Open any unconfirmed transaction, wait a minute or more for the "First seen" field to change from "Just now" to another value then reload the page.

### Expected behaviour

The "First seen" field should display the timing since the transaction was received by the node.

### Actual behaviour

When we look at a specific unconfirmed transaction, the "First seen" field always reset to "Just now" every time we open the page or reload it.

### Screenshots

Step 1:
![image](https://user-images.githubusercontent.com/3265696/115748443-393b8500-a3a7-11eb-89cc-85af25ed8414.png)

Step 2:

![image](https://user-images.githubusercontent.com/3265696/115748755-83246b00-a3a7-11eb-9ac0-024e01588157.png)

Step 3:

![image](https://user-images.githubusercontent.com/3265696/115748810-92a3b400-a3a7-11eb-8089-4dbfb6bcbdb4.png)

#### Device or machine

Raspberry Pi with the latest version of Umbrel on it (0.3.8)

**Comment by softsimon** [comment]
Thanks for reporting this bug so nicely.

It is fixed in master and due for the 2.1 release.

Reated #390
