### ISSUE TITLE
API Docu - Get address tx wrong

### ISSUE THREAD

**Issue by Pl8tinium** [mempool/mempool#4705]
https://github.com/mempool/mempool/blob/ec21b3d06f6c17c60983dffd537a78c400cc6e9c/frontend/src/app/docs/api-docs/api-docs-data.ts#L1020

i think 

https://mempool.space/docs/api/rest#get-address-transactions

is outdated.

Seems to me that 'after_txid' is the correct parameter

**Comment by hunicus** [comment]
@Pl8tinium good catch, thanks! Correction made at #4709.
