### ISSUE TITLE
Incorrect Difficulty Adjustment Percentage

### ISSUE THREAD

**Issue by JhnnWlkr** [mempool/mempool#471]
### Description

The estimated difficulty adjustment percentage is probably calculated by dividing the average time per block of this difficulty epoch by the expected amount of time (600 seconds), instead of the other way around. 
### Expected behaviour

-100*(1-600/720) = -16,7%

### Actual behaviour

-100*(720/600-1) = -20%

**Comment by softsimon** [comment]
This is the current calculation.

The difficultyChange is calculated by dividing progress by the expected progress.

Maybe you could share some suggestions... Because there are different ways of calculating difficulty.
   
       const now = new Date().getTime() / 1000;
       const diff = now - DATime; // DATime is the time of the last difficulty adjustment
       const blocksInEpoch = block.height % 2016;
       const estimatedBlocks = Math.round(diff / 60 / 10);
       const difficultyChange = (blocksInEpoch - (diff / 60 / 10)) / blocksInEpoch * 100;

**Comment by JhnnWlkr** [comment]
Thanks! I was curious to see what the actual calculation was. I noticed it because I'm setting up a py Discord bot with some timechain data, this is what I use to calculate it:

height = int(requests.get('https://mempool.space/api/blocks/tip/height').text)
previous_retarget_timestamp = json.loads(requests.get(f'https://mempool.space/api/blocks/{height-height%2016}').text)[0]['timestamp']
current_block_timestamp = json.loads(requests.get('https://mempool.space/api/blocks/tip').text)[0]['timestamp']
timestamp_difference = current_block_timestamp-previous_retarget_timestamp
blocks_since_retarget = height%2016
average_block_time = timestamp_difference/blocks_since_retarget
deviation = (600/average_block_time)-1
percentage = round(deviation*100, 2)

**Comment by JhnnWlkr** [comment]
Replacing
```
const difficultyChange = (blocksInEpoch - (diff / 60 / 10)) / blocksInEpoch * 100;
```
with
```
const difficultyChange = (600/(diff/blocksInEpoch)-1)*100;
```
should work I guess.

**Comment by AbelLykens** [comment]
So the algos are comparing time passed with blocks found. Let's assume we have seen 1000 blocks in this epoch. 1000 blocks should take 1000 * 10 [min] * 60 [sec] = 600k seconds diff. 
But let's assume it took 660k seconds (10% too slow).

**Original code:**
`(blocksInEpoch - (diff / 60 / 10)) / blocksInEpoch * 100;`
Leads to:
`(1000 - ( 660 000 / 60 / 10 ) / 1000 = -10`
In the example we are 10% slower, and this leads to a -10% difficultyChange in code.

**Proposed code**
`( 600 / ( diff / blocksInEpoch ) -1 ) * 100;`
Leads to:
`( 600 / ( 660 000 / 1000 ) -1 ) * 100 =  -9,09090909090909`

If the difficulty would be 100 000 and goes to 90 000 (10% decrease), then it seems like the original code should do it right?

I might be missing something, have not followed diffchanges for too long, but to me it feels like original calc is OK...

**Comment by AbelLykens** [comment]
Have analyzed era 335 (which starts at block 375360). The real difficulty change was 5.82%.

Mempool's algorithm predicted on average a 6.63% change.
The proposed algo predicted a 7.70% change.

Looking at all blocks in era:
![image](https://user-images.githubusercontent.com/47113175/116063178-3628e900-a674-11eb-8008-b5ef003f8431.png)

Looking at only blocks starting 100 blocks in the era.
![image](https://user-images.githubusercontent.com/47113175/116063219-40e37e00-a674-11eb-9f1b-2f5c317c6ad5.png)

It seems the original/current algo predicts more accurately.

**Comment by JhnnWlkr** [comment]
10% of 660,000 = 66,000.

Let's assume the blocks take 21 minutes, because why not.
Let's assume we have seen 1000 blocks in this epoch, like you said.
That means they took 1,260,000 seconds.

Original code:
`(blocksInEpoch - (diff / 60 / 10)) / blocksInEpoch * 100;`
Leads to:
`(1000 - ( 1 260 000 / 60 / 10 ) / 1000 = -110%`
Yes, -110%.

Proposed code:
`( 600 / ( diff / blocksInEpoch ) -1 ) * 100;`
Leads to:
`( 600 / ( 1 260 000 / 1000 ) -1 ) * 100 = -52.38%`

**Comment by JhnnWlkr** [comment]
You could also take into account the 2015 blocks bug by
1. Calculating an estimated average time for the blocks until the next retarget based on all the blocks in this epoch
2. Multiplying that estimate by the number of blocks until the next retarget
3. Calculating the total time since the *second* block of this epoch
4. Adding those two up and dividing that by 2016 to get the total average block time

**Comment by JhnnWlkr** [comment]
Wait does removing it mean you're not going to change it or you've already changed it?
