### ISSUE TITLE
Improve Inscription Detection

### ISSUE THREAD

**Issue by hans-crypto** [mempool/mempool#4714]
See https://github.com/mempool/mempool/blob/43fde86e9d926e892d1dc9a4709456dba2084b69/backend/src/api/common.ts#L277

If you only search for `OP_FALSE OP_IF` then you will also catch Atomicals, which is confusing.
I suggest to:

* Detect inscriptions with `OP_FALSE OP_IF OP_PUSHBYTES_3 "ord"` and introduce atomicals with `OP_FALSE OP_IF OP_PUSHBYTES_4 "atom"` <br>OR
* Rename the goggle to something like "digital assets", "extra data in witness", or "fake witness data" (since you called data in mutisig keys "fake pubkey").

I can make a PR, if you tell me what option you prefer.

**Comment by mononaut** [comment]
We use "inscription" as a generic term to describe the technique of embedding data in an `OP_FALSE OP_IF ... OP_ENDIF` witness script envelope.

This isn't necessarily a universally accepted usage, but it's well understood, fits in short UI strings, and can be further qualified to specify e.g. "ordinal inscription" or "atomical inscription".

The filter deliberately does not discriminate between different protocols (partly to maintain neutrality, partly as proof against future changes in popular usage, and partly to avoid adjudicating what counts as *valid* under any particular protocol).
