### ISSUE TITLE
Unwanted blockchain scroll on mobile Safari

### ISSUE THREAD

**Issue by natsoni** [mempool/mempool#4742]
### Steps to reproduce

On mobile Safari, go to the blockchain tip:

<img src="https://github.com/mempool/mempool/assets/46578910/9653cc01-c98a-43fc-bf44-8905e68d7a04" width="200">

Vertical scrolling to see the block template does not trigger a scroll on the blockchain above, which is normal. 
Then scroll to older blocks until the white arrow appears on the left: 

<img src="https://github.com/mempool/mempool/assets/46578910/958cd7d5-e8f6-4f17-a435-19d5ca1e6e9f" width="200">

Now, vertical scrolling also makes the blockchain to scroll to the right:

https://github.com/mempool/mempool/assets/46578910/8fdfc30a-ea5e-4920-95b5-53c95771ac1d

**Comment by orangesurf** [comment]
Still present on  [54289368]
