### ISSUE TITLE
Consider patching electrs to modify hard-coded static constants

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#48]
These are some of the hard-coded static constants in electrs we should consider changing
```
const RECENT_TXS_SIZE: usize = 10;
const BACKLOG_STATS_TTL: u64 = 10;
const CHAIN_TXS_PER_PAGE: usize = 25;
const MAX_MEMPOOL_TXS: usize = 50;
const BLOCK_LIMIT: usize = 10;
```

**Comment by Kixunil** [comment]
It should be possible to make them configurable. They currently pretend to optimize things (no allocations) but that's not relevant as it's one-time startup cost that can't be perceived by a human. Unless I'm missing something.

**Comment by wiz** [comment]
Over the past few months I experimented with simple hacks to the blockstream/electrs code like using different compression algorithms, disabling compaction, etc. - you can an example here:

https://github.com/mempool/electrs/commit/98a9a9ad277bafd06bf610d3899c0cab84a1cc28

I think @shesek will probably optimize these on his own anyway, or the romanz/electrs project maintainers over time, and things are okay for the moment so it's not a huge priority for us now

**Comment by Kixunil** [comment]
Do you have any numbers from those experiments? I contribute to the upstream (romanz) version quite a bit so I could use some stats. :)

**Comment by wiz** [comment]
Well since compression and compaction are just tradeoffs between time and space, and lacking any hard numbers, I would suggest simply making everything configurable and letting users decide what they want to optimize for on their own

**Comment by wiz** [comment]
@junderw @softsimon can you guys please prioritize this

**Comment by junderw** [comment]
For these two:

```
const CHAIN_TXS_PER_PAGE: usize = 25;
const MAX_MEMPOOL_TXS: usize = 50;
```

They will change from hard coded limits, to default limits (that you can change per request)

See: https://github.com/mempool/electrs/pull/8/files

For

```
const RECENT_TXS_SIZE: usize = 10;
const BACKLOG_STATS_TTL: u64 = 10;
const BLOCK_LIMIT: usize = 10;
```

We could set them to runtime parameters set on startup.

**Comment by junderw** [comment]
It seems like only `RECENT_TXS_SIZE` needs to be known at compile time (since it uses ArrayDeque)

It could be moved to runtime if we use a VecDeque with fixed length. (Something like https://docs.rs/bounded-vec-deque/latest/bounded_vec_deque/)

**Comment by junderw** [comment]
I made a PR.
