### ISSUE TITLE
ProgressEvent not handled

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#4800]
![Screenshot 2024-03-19 at 18 35 11](https://github.com/mempool/mempool/assets/232186/137ad612-0679-44e4-be7e-cf9979675d77)

**Comment by softsimon** [comment]
Got Console log / HTTP request response?

**Comment by wiz** [comment]
This happens all the time for me when I close and open laptop lid - can't you just handle the event ?

**Comment by nymkappa** [comment]
> This happens all the time for me when I close and open laptop lid - can't you just handle the event ?

We probably make another httpinterceptor to catch those kind of general errors @softsimon ?
