### ISSUE TITLE
Error: Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by Ruxiol** [mempool/mempool#484]
### Description

When starting Backend npm command i get this

Error: Cannot find module 'worker_threads'

#### Version

latest

### Steps to reproduce

  npm run build command on backend folder

**Comment by softsimon** [comment]
I suspect you are running an older version of NodeJS where `worker-threads` is not included as default

So upgrade your NodeJs to a newer version, or if you can't, try installing the worker-threads npm package

**Comment by Ruxiol** [comment]
You were right, sorry my bad!!!

Tell me, can i install this beauty on x11 algo,  DASH fork community project?

We really want to learn basics!

**Comment by softsimon** [comment]
Dash? We support Bitcoin mainnet. You'll have to make adaptations to make it work with something else.

I guess this issue is resolved.
