### ISSUE TITLE
Display additional missing block data

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#487]
The following fields are missing and should be displayed, maybe under a Details button similar to Transaction

`Version, merkle root, bits, difficulty, nonce`

**Comment by MiguelMedeiros** [comment]
I think you can close this issue. 
Already fixed here:  https://github.com/mempool/mempool/commit/d2fe000ad0ce781ba75a84a2b1da22685528759c

**Comment by MiguelMedeiros** [comment]
I think you should close this issue.
Already merged here: https://github.com/mempool/mempool/commit/d2fe000ad0ce781ba75a84a2b1da22685528759c

**Comment by softsimon** [comment]
Fixed in d2fe000
