### ISSUE TITLE
Difficulty adjustment estimate is slightly off

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#488]
AFAIK the difficulty adjustment estimate should match 100% exactly on the last block of an epoch, but it is slightly off

### Expected Result

```
; 1 - (20608845737768.16 / 23581981443663.85)
	~0.12607658576097006297
```

### Actual Result

<img width="534" alt="Screen Shot 2021-05-02 at 5 12 02" src="https://user-images.githubusercontent.com/232186/116794615-48d66e80-ab09-11eb-82cc-1eb700014fc8.png">

### Additional Information

> Due to a longstanding bug in the Bitcoin source code, the time spent mining the first block in each difficulty epoch actually has no effect on the next difficulty calculation. Even if this block somehow took an entire year to mine, it would not cause the next difficulty to drop, believe it or not!

https://github.com/bitcoinbook/bitcoinbook/blob/6486a74a8603eeb9f82f75184a253498a97b8d79/ch10.asciidoc#retargeting-to-adjust-difficulty

**Comment by softsimon** [comment]
Also check https://github.com/mempool/mempool/issues/471#issuecomment-826832010

**Comment by wiz** [comment]
Also there is a cap of -/+ 25%, and during the first few blocks of a new epoch it's wildly off :P

<img width="535" alt="Screen Shot 2021-05-02 at 5 46 54" src="https://user-images.githubusercontent.com/232186/116794684-e0d45800-ab09-11eb-8ce9-2acffd6c44d8.png">

**Comment by darthginger** [comment]
https://github.com/bitcoin/bitcoin/blob/7fcf53f7b4524572d1d0c9a5fdc388e87eb02416/src/pow.cpp#L54
I think it's -75% / +300%
