### ISSUE TITLE
UX: Unify the units

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#490]
The units, including BTC, MB, MWU etc should have the same design language.
Also maybe the (1 min ago) should be in the same style.

<img width="491" alt="Screen Shot 2021-05-03 at 17 17 15" src="https://user-images.githubusercontent.com/8561090/116881676-9c91a680-ac34-11eb-9914-1d0c27a2faff.png">

**Comment by MiguelMedeiros** [comment]
Fix #499 .
