### ISSUE TITLE
Coinbase and OP_RETURN text is truncated on transactions

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#496]
@MiguelMedeiros is this a feature/bug introduced with the recent CSS enhancements?

<img width="271" alt="Screen Shot 2021-05-06 at 18 49 16" src="https://user-images.githubusercontent.com/232186/117278603-ddd7bf80-ae9b-11eb-8ed2-3c0b8c8e3ad1.png">

**Comment by MiguelMedeiros** [comment]
Yes I needed to truncate the text depending on the css media query.
I could make it bigger on desktop view. 

Remeber you can read all the OP_RETURN message if you mouse over the component.

![image](https://user-images.githubusercontent.com/5798170/117286880-1ba6fa80-ae40-11eb-9af5-45b3d33d5aaf.png)

**Comment by lurch** [comment]
Why are there a whole bunch of diamond-characters (and other weird glyphs) displayed in the text? Is it deliberate? :confused:  It looks like some kind of bad-unicode-decoding thing? :man_shrugging:
