### ISSUE TITLE
ETA text justified wrong

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#4999]
This happens on accelerated transactions when the Accelerate button is gone.

<img width="589" alt="Screenshot 2024-04-20 at 15 57 59" src="https://github.com/mempool/mempool/assets/8561090/4675bebf-25a9-4e7b-b2bb-5e9d3f9fb7da">

**Comment by wiz** [comment]
the accelerate button should always appear, this is the actual bug

**Comment by softsimon** [comment]
> the accelerate button should always appear, this is the actual bug

Appear, but being disabled?

Or what is the point of showing it. The ability to accelerate again?

**Comment by nymkappa** [comment]
> > the accelerate button should always appear, this is the actual bug
> 
> 
> 
> Appear, but being disabled?
> 
> 
> 
> Or what is the point of showing it. The ability to accelerate again?

No he got confused with a very similar bug where the accelerate button does not show for txs in the 8th mempool block.

**Comment by softsimon** [comment]
Been fixed
