### ISSUE TITLE
strange graphs data

### ISSUE THREAD

**Issue by svpi11** [mempool/mempool#5043]
Hello,

I am running the self-hosted mempool service behind a tor hiddenservice since a while.
I had little rare moments offline (readjustments, etc), but at the end, my graph is often totally different than the "official grah", and I was wondering if aybody can have an idea, for where does it come from. 

#### Version
Latest 

### Steps to reproduce
Build frontend and backend on a private VPS

### Expected behaviour
same graph as the "official" mempool.space tor website.

### Actual behaviour
different graph: here is an example on 1month

### Screenshots

<img width="1512" alt="Capture d’écran 2024-05-07 à 18 13 05" src="https://github.com/mempool/mempool/assets/69041623/0476126c-72f4-4c36-970d-8191056c73ba">
<img width="1512" alt="Capture d’écran 2024-05-07 à 18 13 15" src="https://github.com/mempool/mempool/assets/69041623/c95319cb-229d-47b9-aded-271ad1d4d7bc">

#### Device or machine
RaspberryPi 4 - Ubuntu Server 22.04LTS

**Comment by natsoni** [comment]
From looking at your mempool graph, it looks like your node is purging transactions to keep its mempool smaller than around 80 MvB ≃  300 MB. Did you set a high enough `maxmempool` in your `bitcoin.conf` to allow your local mempool to be bigger than default 300 MB?

<img width="488" alt="Screenshot 2024-05-07 at 20 52 42" src="https://github.com/mempool/mempool/assets/46578910/b3038642-dcdc-405a-8219-5f21cb451f3e">

You can see that mempool.space's mempool has a size of more than 1 GB, and that nodes that keep their mempool at 300 MB are purging transactions lower than 7 sat/vB.

**Comment by svpi11** [comment]
Thanks a lot for your answer ! 
I just learnt this type of parameters were existing ... 
I didn't configure anything about it, so that was exactly what you said. I Will adapt my bitcoin.conf. then :) 
I can close this, and thanks again ;)
