### ISSUE TITLE
Graphs page loading spinner position

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#5083]
Currently the loading spinner is located where it pushes the UI down.
It previously was located as illustrated below, more close to where the user toggle changes.

![loadingspinnerpos](https://github.com/mempool/mempool/assets/8561090/fe947fca-8f37-4dfa-b497-a5427152f534)

**Comment by nymkappa** [comment]
Why not on the charts like in some other places?

<img width="1447" alt="image" src="https://github.com/mempool/mempool/assets/9780671/4a0d827e-4f09-4ca6-ac96-d11a440b74ee">
