### ISSUE TITLE
Miner loading forever on confirmed transaction

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#5102]
Tracked a accelerated transaction. It got confirmed and the miner is loading like this

<img width="1287" alt="Screenshot 2024-05-25 at 22 17 17" src="https://github.com/mempool/mempool/assets/8561090/65b8aebb-0d44-4c17-aece-d027f415a294">

**Comment by nymkappa** [comment]
That's funny I was about to open the exact same issue

<img width="583" alt="image" src="https://github.com/mempool/mempool/assets/9780671/bc30eff7-34e0-4c4a-b455-aa635eee4ab8">

**Comment by softsimon** [comment]
Still happening

<img width="628" alt="Screenshot 2024-07-18 at 17 00 11" src="https://github.com/user-attachments/assets/d6d1b470-de35-4d56-87dd-99f2efa190b9">
