### ISSUE TITLE
$indexPastAccelerations() fails on non-esplora backends

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#5166]
$indexPastAccelerations() fails due to $getTxsForBlock not being implemented in the bitcoinApi on non-esplora backends.

`Jun 18 15:58:14 [658189] ERR: Failed to process accelerations for block 790245. Reason: Method getTxsForBlock not supported by the Bitcoin RPC API.
`

**Comment by mononaut** [comment]
I've implemented a quick short-term fix in #5169, but I'll see if I can come up with a more efficient solution specifically for acceleration indexing in a later PR.
