### ISSUE TITLE
Unable to get UTXO of an address - /address/:address/utxo 

### ISSUE THREAD

**Issue by nakul91** [mempool/mempool#5191]
<img width="615" alt="Screenshot 2024-06-22 at 2 46 26 PM" src="https://github.com/mempool/mempool/assets/7921710/aed023ed-c7d2-4572-9eab-41f2e87c5881">

  We are running a custom signet and using Electrs we have enabled the Mempool as well but we are facing issue when we try to get the UTXO for an address apart from this all the other API's seems to be working for example transactions api

**Comment by softsimon** [comment]
Electrs don't use the `/v1/` part

**Comment by nakul91** [comment]
Even if I don't add v1 it's somehow redirecting to v1 not sure why

**Comment by softsimon** [comment]
Not reproducible or known bug.
