### ISSUE TITLE
Confirmed after 55 years

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#5196]
Track a transaction, watch it confirm, voila.

Seems to happen a lot.

<img width="437" alt="Screenshot 2024-06-23 at 22 16 06" src="https://github.com/mempool/mempool/assets/8561090/f6e952cb-f68d-4a57-90b5-b6973bf12f07">

**Comment by nymkappa** [comment]
![image](https://github.com/mempool/mempool/assets/9780671/717843c8-abb3-49c7-bba9-70281af1724f)

**Comment by junderw** [comment]
Jan. 1st 1970... I remember that day oh so clearly......... (I wasn't born)
