### ISSUE TITLE
"InternalError: too much recursion" when searching for a future SegWit version address

### ISSUE THREAD

**Issue by vostrnad** [mempool/mempool#5247]
### Description

Searching for a future SegWit version address and clicking it causes this error log in the console:

```
ERROR InternalError: too much recursion
```

#### Version

3dbbc830770231815e804ca147d636d59b77e30c

### Steps to reproduce

1. Start typing "bc1pfeessrawgf" into the search box.
2. Click on the address when it appears as a result.

### Expected behaviour

The address's page should appear.

### Actual behaviour

Nothing happens when the address is clicked.

### Screenshots

![bc1pfees](https://github.com/mempool/mempool/assets/43024885/b9ce6bc0-44db-4e61-be4d-39de4b546dff)

**Comment by mononaut** [comment]
this specific instance is resolved by #5252, but we should probably fix the underlying recursion issue too @natsoni
