### ISSUE TITLE
Tor onion making clearnet calls to services

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#5316]
https://mempool.space/api/v1/services/version

**Comment by wiz** [comment]
ah yeah, in the state service, we should change SERVICES_API to use the mempool onion hostname instead of "mempool.space", this should probably make it into v3.0.0 otherwise accelerating from an umbrel onion might not work due to CORS failing due to origin header being null

**Comment by wiz** [comment]
Fixed by #5431
