### ISSUE TITLE
calculateETA frontend error

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#5318]
I clicked on an accelerated transaction from the dashboard 956bca447fff254e910bb17e8c2201fcc2f321808df8a91f3eea1810d46a13ac

<img width="550" alt="Screenshot 2024-07-12 at 01 11 05" src="https://github.com/mempool/mempool/assets/8561090/f68a85dc-d172-418e-9e9c-3dd11c162822">

<img width="726" alt="Screenshot 2024-07-12 at 01 11 02" src="https://github.com/mempool/mempool/assets/8561090/4782a851-12d2-423e-a919-7f33c3eeb632">

**Comment by wiz** [comment]
please re-open if still reproducing
