### ISSUE TITLE
About page hangs due to too many network requests

### ISSUE THREAD

**Issue by jlopp** [mempool/mempool#5342]
### Description

About page does not fully load.

#### Version

v3.0.0-dev

### Steps to reproduce

Open the about page, watch the network requests in developer tools.

### Expected behaviour

Page should complete loading and rendering in several seconds.

### Actual behaviour

The about page never fully finishes loading because the last dozen or so network requests for resources hangs.

This appears to be exacerbated by the total number of images loaded.

But the real problem is that the stalled image requests end up blocking the loading of critical javascript files.

### Screenshots

![image](https://github.com/user-attachments/assets/6e7897da-1c48-48c5-998e-677e3b2fc161)

#### Device or machine

All.

#### Additional info

I'd suggest a few possible remedies:

Short term, if it's possible to ensure that all javascript files are loaded first before image files, that should ensure that all the major components of the page render even if image requests stall or time out.

Long term, a solution should be found to improve the scalability of loading avatar images of supporters. One option I've seen is to compile all of the images into a single image file on the back end and then use CSS magic to only render small slices of each one on the front end.

**Comment by wiz** [comment]
I tweaked the rate limits for the images shortly before you opened this issue, are you sure this is still reproducing?

As for batching the image loading, sure we've wanted to do this for years but we can't easily change the spec for loading images because they load on the hundreds of thousands of self-hosted mempool instances out there, so we would have to upgrade to use a new spec and wait a few years for everyone to upgrade heh

**Comment by jlopp** [comment]
It's definitely still occurring; you can verify by trying to analyze the page via https://gtmetrix.com/

I think the fundamental problem is the fact that some of the javascript files are failing to load. I'd prioritize ensuring that all javascript gets loaded before trying to load all the avatar images.

**Comment by wiz** [comment]
Fixed
