### ISSUE TITLE
Layout restructuring to merge everything together

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#54]
* Remove links for "blockchain", "graphs", "tv view", "contributors" in top header
* Add toggle switch below mempool logo for graphs: off, time, weight
* Move search box text input field between blocks and table, make larger and style nicely to match site theme
* Move critical statistics data from footer into top header
* Move blockchain blocks to left side and projected mempool blocks to right side, so they match the time scale
* Add a TV button to show the time graph and hide the table (including text field) to replicate current v1 tv view

**Comment by wiz** [comment]
Here is an ugly mockup that doesn't include everything but you get the idea

<img width="1151" alt="Screen Shot 2020-03-13 at 0 50 55" src="https://user-images.githubusercontent.com/232186/76618414-df457a80-656b-11ea-9332-97510e4adcfb.png">

**Comment by softsimon** [comment]
With the new dashboard this task is either semi complete or done.

So closing this for now as it would be better with a new task based on the current design.
