### ISSUE TITLE
Preimage broadcast API

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#543]
- check every OP_RETURN output for 32 byte long sequences (each output may have up to 2 of them due to size limitations)

- hash each found sequence (it is assumed to be a preimage)

- have a key-value db of SHA256_hash(chunk32) -> chunk32

- have an API to return chunk32 by hash(chunk32), if exists

**Comment by btcontract** [comment]
A relevant test which shows the flow: https://github.com/btcontract/plugin-hosted-channels/blob/master/src/test/scala/fr/acinq/hc/app/PreimageBroadcastCatcherSpec.scala#L37-L47.
