### ISSUE TITLE
Testnet shows the same number of Unconfirmed as mainnet

### ISSUE THREAD

**Issue by jsarenik** [mempool/mempool#545]
### Description

Compare the number of *Unconfirmed* transactions when you open both links in tabs of the same browser:

 * https://mempool.space/
 * https://mempool.space/testnet

It happens also in Tor Browser:

  * http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion
  * http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/testnet

#### Version

v2.2.0-dev [edad15da]

### Steps to reproduce

Open the addresses from description.

### Expected behaviour

The testnet Unconfirmed transactions are shown correctly when you open an incognito window and there open _only_ https://mempool.space/testnet

### Actual behaviour

The number of Unconfirmed transactions from mainnet leaks to testnet (maybe also to others like signet, did not try that).

### Screenshots

![mempool-unconfirmed-mainnet](https://user-images.githubusercontent.com/244565/120101312-d7a8cc00-c145-11eb-8a3c-e2da654f7f90.png)

![mempool-unconfirmed-testnet](https://user-images.githubusercontent.com/244565/120101317-de374380-c145-11eb-88ed-4344ca1df022.png)

And just testnet in incognito window:

![mempool-unconfirmed-testnet-only-incognito](https://user-images.githubusercontent.com/244565/120101371-13439600-c146-11eb-995d-405e5606edfd.png)

#### Device or machine

Linux 5.8.0 x86_64 (Ubuntu)

**Comment by softsimon** [comment]
This seems to be a server configuration error on **node201** for testnet.. You can reproduce the error all the time on `https://node201.mempool.space/testnet`. @wiz  will fix it :)

**Comment by wiz** [comment]
hmm ok

**Comment by jsarenik** [comment]
@softsimon Wonderful! Thank you for tracing this issue!

**Comment by wiz** [comment]
Fixed
