### ISSUE TITLE
Y axis of sat/vBytes in graph module

### ISSUE THREAD

**Issue by Genbel** [mempool/mempool#549]
Could you inverse the values of sat/vByte in the graph section like this because the lowest values are on top in the _y axis_ and in the graph are at the bottom

<img width="493" alt="Screenshot 2021-06-04 at 00 00 31" src="https://user-images.githubusercontent.com/10881341/120718472-9dcf2100-c4c9-11eb-9598-d80f4004ed1e.png">

The fix would be easy. In the ul element add

`
display: flex;
flex-direction: column-reverse
`

Thanks for your time

**Comment by MiguelMedeiros** [comment]
Hey @Genbel!
Thanks for the issue, but I've already done it!
Take a look at this pull request https://github.com/mempool/mempool/pull/532

You can see a live preview here:
https://mempool.ninja/graphs

**Comment by Genbel** [comment]
ups sorry! I did not know that this page exists. Is it an staging or testing domain? Thanks for the commit ;)

**Comment by MiguelMedeiros** [comment]
> ups sorry! I did not know that this page exists. Is it an staging or testing domain? Thanks for the commit ;)

Yes, it is our staging domain. :)
