### ISSUE TITLE
[accelerator dashboard] `Recent Accelerations` widget is not updated in real time

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#5490]
When you have txids listed in the `Active Accelerations` that gets mined, those txids should automatically move into the `Recent Accelerations` widget without refreshing the page.

**Comment by natsoni** [comment]
Both widgets `Active Accelerations` and `Recent Accelerations` should already be updated in real time 😬 it's a bug report then?

**Comment by nymkappa** [comment]
Sorry I realized that the issue was coming from the way I was testing 😆
