### ISSUE TITLE
Time Zone Selection

### ISSUE THREAD

**Issue by orangesurf** [mempool/mempool#5628]
### Description

Add time zone selector in footer

### Problem to be solved

Users may not wish to use their local time zone

### Proposed solution

Add drop down selector to footer

![image](https://github.com/user-attachments/assets/aa83f634-2437-4f40-b2fb-dc8a92f357aa)

#### Additional info

Suggestion from Wicked Bitcoin

https://x.com/w_s_bitcoin/status/1855598476068827248

**Comment by nymkappa** [comment]
Related https://github.com/mempool/mempool/issues/179
