### ISSUE TITLE
Make taproot activation block glow

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#573]
On block 709632, taproot will be activated. This will be an event similar to the halving or segwit activation and should be visible on Mempool with a green glowing/blinking mempool block and mined block, and activation should have fireworks spewing for 8 blocks until it's gone out of sight.

We did just like this for this halving so old code should exist for this.

This code should remain so it can be easily configured and adapted for new events. Including all the coming halving events.

**Comment by hsjoberg** [comment]
🟩

**Comment by ziggie1984** [comment]
I was thinking of a temporary feature, besides the fire works and the activation, to only consider the activation smoothly when the first P2TR transaction was mined and no chain split occurred. So my thoughts would be something like highlighting P2TR transactions after the activation and displaying the getchaintips form bitcoin-core, what are your ideas ?
