### ISSUE TITLE
Donations API returns duplicate results

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#583]
https://mempool.space/api/v1/donations should return only unique usernames

**Comment by softsimon** [comment]
The duplicate users are in fact people that sponsored more than once, and we didn't put a unique limit.

**Comment by MiguelMedeiros** [comment]
What do you think about making the image of the sponsor who donated twice or more a little bigger?

**Comment by knorrium** [comment]
What about a small badge, like a notification icon with a number or 2x, 3x, etc?

**Comment by wiz** [comment]
nah

**Comment by MiguelMedeiros** [comment]
> nah

@wiz, don't you think maybe this will help with new donations? :P

> What about a small badge, like a notification icon with a number or 2x, 3x, etc?

@knorrium, I liked this idea. :)

**Comment by softsimon** [comment]
Working as intended
