### ISSUE TITLE
Raw Hex of Objects in Details Tab

### ISSUE THREAD

**Issue by TheBlueMatt** [mempool/mempool#616]
It is often useful to get full hex of a transaction to copy and paste into a wallet or other transaction submission APIs. It would be nice if it were exposed under Details in the transaction view. While you're at it, block header raw hex would be cool too.

**Comment by wiz** [comment]
1) API docs is missing `/header` endpoint
https://mempool.ninja/api/block/0000000000000000000065bda8f8a88f2e1e00d9a6887a43d640e52a4c7660f2/header

2) Add hex transaction link

3) Add hex block header link

**Comment by priyanshiiit** [comment]
@wiz Could you please tell me more details.

**Comment by wiz** [comment]
looks like @softsimon deleted my comment with the details, presumably because he split the tasks into separate issues

**Comment by softsimon** [comment]
> @wiz Could you please tell me more details.

We could add this to the details view for transactions and blocks.

A link to the following api endpoints

`GET /tx/:txid/raw`
`GET /block/:hash/raw`

**Comment by wiz** [comment]
Actually, it should be
`GET /api/block/:hash/header` not `GET /block/:hash/raw`

**Comment by wiz** [comment]
And it should be
`GET /tx/:txid/hex` not `GET /tx/:txid/raw`
