### ISSUE TITLE
No obvious link to previous block

### ISSUE THREAD

**Issue by TheBlueMatt** [mempool/mempool#617]
I don't see a link to the previous block from a block view page, though I may have missed it. In any case, the previous block hex is missing from the Details view of blocks.

**Comment by priyanshiiit** [comment]
Hi @MiguelMedeiros!
Are you working on this issue?

**Comment by MiguelMedeiros** [comment]
> Hi @MiguelMedeiros!
> Are you working on this issue?

Hey @priyanshiiit i'm working on other PR at the moment!
You can take this one for me!

**Comment by softsimon** [comment]
The difficult task is to find where the previous block link should be to not make the block view look ugly.

**Comment by priyanshiiit** [comment]
> The difficult task is to find where the previous block link should be to not make the block view look ugly.

Hi @softsimon. I got your concern, can we have it similar to Block Header Hex?

**Comment by priyanshiiit** [comment]
How about this?
![Screenshot from 2021-08-03 23-40-20](https://user-images.githubusercontent.com/43826321/128065638-911fab93-f1f3-4ac0-9ac5-0fad5c77ce52.png)

**Comment by MiguelMedeiros** [comment]
Hey @priyanshiiit ! 

I think you could use some FontAwesome icons:
 - https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=next&m=free
 - https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=previous&m=free

Ideas for styles:
 - https://dribbble.com/shots/10250629-Button-Next-Previous-Action
 - https://dribbble.com/shots/7311393-Daily-UI-085-Pagination
 - https://dribbble.com/shots/3966679-Let-the-icons-live
 - https://dribbble.com/shots/10056691-Social-media-Share-Pagination-Previous-and-Next-page

I don´t know about the position. But it could be on the top-left and top-right as you showed.

**Comment by softsimon** [comment]
> How about this? At the top-left corner.
> ![Screenshot from 2021-08-03 23-40-20](https://user-images.githubusercontent.com/43826321/128065638-911fab93-f1f3-4ac0-9ac5-0fad5c77ce52.png)

Probably not a good idea since the UI will have to move down compared to other pages to accommodate this.

But I don't have any better idea right now.

**Comment by MiguelMedeiros** [comment]
> > How about this? At the top-left corner.
> > ![Screenshot from 2021-08-03 23-40-20](https://user-images.githubusercontent.com/43826321/128065638-911fab93-f1f3-4ac0-9ac5-0fad5c77ce52.png)
> 
> Probably not a good idea since the UI will have to move down compared to other pages to accommodate this.
> 
> But I don't have any better idea right now.

I'm working on this PR: https://github.com/mempool/mempool/issues/691
And it could be weird add this element on the top of the `block title`.

Maybe you can try something inline instead of on the top, or come with another position for these buttons.
