### ISSUE TITLE
blockchain wrapper div in mempool.space/tv page doesn't show blocks

### ISSUE THREAD

**Issue by aviv57** [mempool/mempool#629]
### Description

On the mempool.space/tv the blocks in the blockchain wrapper div are missing

### Steps to reproduce

Go to the mempool.space/tv page

### Expected behaviour

see the last blocks, and the future blocks

### Actual behaviour

no blocks appear

### Screenshots

![image](https://user-images.githubusercontent.com/2240171/125488988-4d4f84a1-aca5-48b8-ba2c-c9facab2b358.png)

#### Device or machine

Tested it both on Chrome, Firefox (Windows 10)
and on Firefox for Android
and on Firefox for raspberry pi

**Comment by softsimon** [comment]
Thanks for your report.

This bug was fixed yesterday in https://github.com/mempool/mempool/pull/626 and I just upgraded the site so it should be fine now.
