### ISSUE TITLE
Create new block data tables for miner dashboard

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#63]
1. Create a new table for block data in the database with the following fields:
Block height
Block weight
Fee-span (Array)
Median fee
Difficulty
Miner identification (some ID connected to a separate table with miner id+name)

2. Create a new miners table that automatically stores the individual unique mining pools

**Comment by softsimon** [comment]
Replacing with new issue https://github.com/mempool/mempool/issues/1047
