### ISSUE TITLE
Replace static orange color of mempool blocks with dynamic colors from graph legend

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#64]

**Comment by softsimon** [comment]
Although I like the idea it doesn't look good enough in this way at least.. Too colourful.

<img width="941" alt="Skärmavbild 2020-03-28 kl  14 09 17" src="https://user-images.githubusercontent.com/8561090/77888565-ab21c780-7296-11ea-872e-7dd6ffb482d0.png">
<img width="1041" alt="Skärmavbild 2020-03-28 kl  14 02 18" src="https://user-images.githubusercontent.com/8561090/77888572-aceb8b00-7296-11ea-9afa-a5a0828dac1e.png">
