### ISSUE TITLE
Add previous difficulty adjustment visible on dashboard

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#640]
Myself and many people are always interested in the previous adjustment, so it's more important than showing the current block speed (that will be displayed on the mempool blocks).

Something like this:

<img width="557" alt="Screen Shot 2021-07-18 at 12 13 12" src="https://user-images.githubusercontent.com/8561090/126061948-b4261555-1eeb-49d4-bc9b-263ca00d0d30.png">

**Comment by jaonoctus** [comment]
I do like this section. But I think the "block time" avg is also an important thing to be shown

**Comment by softsimon** [comment]
> But I think the "block time" avg is also an important thing to be shown

Block time will be visible on the mempool blocks when #634 is fixed.
