### ISSUE TITLE
TV view does not show the blocks on small screens

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#657]
While the TV view is not intended for mobile, it doesn't hurt to show the block info on smaller screens. Fixing this will also help normalizing the e2e tests to use standard mobile viewports across the test suite.

<img width="503" alt="Screen Shot 2021-07-24 at 11 40 10 PM" src="https://user-images.githubusercontent.com/100320/126890580-3cec17d5-568b-4668-9c4d-4c96771786e3.png">
<img width="542" alt="Screen Shot 2021-07-24 at 11 40 00 PM" src="https://user-images.githubusercontent.com/100320/126890581-c4470e4a-4111-4da8-8b23-fd78a1ee4d83.png">

**Comment by softsimon** [comment]
It's called TV View because it's for TVs. We should not expect this view to work on small screens.

**Comment by knorrium** [comment]
true but we don't have to intentionally break it by hiding the blocks on smaller screens
