### ISSUE TITLE
Status page does not update mempool block information

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#658]
The `mempool-blocks` data is sent only when the `/status` page is first loaded and not on the following websocket updates, causing the block data and status bar to be stale:

<img width="1378" alt="Screen Shot 2021-07-25 at 12 26 28 AM" src="https://user-images.githubusercontent.com/100320/126891398-6150650b-31af-406b-8d19-14a4357d6147.png">

<img width="1706" alt="Screen Shot 2021-07-25 at 12 26 59 AM" src="https://user-images.githubusercontent.com/100320/126891403-4047d422-b6f7-4f10-ae6e-9f8aa2e4312c.png">

**Comment by softsimon** [comment]
> The `mempool-blocks` data is sent only when the `/status` page is first loaded and not on the following websocket updates, causing the block data and status bar to be stale:

It is only required to send once .. but the second update is overriding the first one .. so no mempool-blocks update. :)

<img width="320" alt="Screen Shot 2021-07-25 at 18 42 04" src="https://user-images.githubusercontent.com/8561090/126904962-2b192554-8041-4dc7-a2c4-80d11e7eeeec.png">
