### ISSUE TITLE
Difficulty Adjustment box incorrectly estimates "in ~1 week" 

### ISSUE THREAD

**Issue by tphyahoo** [mempool/mempool#683]
### Description

The difficulty adustment box has

"Remaining
1652 blocks
In ~1 week"

It is August 2 and Clark Moody estimates we reset August 13, which is 11 days from now. 
I don't know how rounding works, but this doesn't feel like a week to me! 

I think it would be better to report  "11.4" days or "1.6 weeks" 

(1652 / 2016) * 2  => 1.63888 (weeks) (which would round to 2 not 1)
(1652 / 2016) * 14 => 11.472222222222221 (days)

**Comment by softsimon** [comment]
This got fixed in #679
