### ISSUE TITLE
Difficulty Adjustment "Current Period" is confusing

### ISSUE THREAD

**Issue by tphyahoo** [mempool/mempool#684]
### Description

The difficulty adjustment box is currently organized into "Remaining... Estimate... Current Period" sections. 

We are currently at "1650 blocks" remaining and 17.61%  for current period.

I get how difficulty adjustment works, but I still had trouble understanding what "Current Period" refers to here. 

The estimated difficulty adjustment in the current difficulty epoch? no, that was already given as "estimate".
The difficulty adjustment in the subsidy epoch? (no)
%remaining days, to go along with the "blocks remaining" in the "remaining" section? no.

Eventually I realized (I think! because numbers still don't quite match) it was % blocks completed, in current difficulty epoch. IE, 

(2016-1649) / 2016 => 0.182

which is close-ish to the reported 17.61%. So I assume this is what the number means.

I think a good way to clarify this number would be to report underneath in a smaller font 

"367 out of 2016 blocks"
or "367 / 2016" if the former is too much space

Display wise, this would be parallel to how the "remaining section" reports "1 week" under "1649 blocks" 
Even if the number doesn't quite match the percent, it's better than what we have now. 

I also think instead of 

"Remaining... Estimate... Current Period"

it would be better to organize this as 

""Remaining... Estimate... Completed"

**Comment by softsimon** [comment]
The rounding was wrong. Floor was used instead of Round. It got fixed in https://github.com/mempool/mempool/pull/679
