### ISSUE TITLE
UX: The header sizes are not consistent across some pages

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#687]
Note the differences in font size.
Same sizing should be used across pages.

<img width="1147" alt="Screen Shot 2021-08-03 at 21 32 00" src="https://user-images.githubusercontent.com/8561090/128067876-f4129f1d-da58-497c-9752-80d8bf4a023e.png">

<img width="1164" alt="Screen Shot 2021-08-03 at 21 32 08" src="https://user-images.githubusercontent.com/8561090/128067883-ac7246e6-f39a-4b1d-9c39-9134fa767959.png">

**Comment by wiz** [comment]
this looks like a job for... CSS Man

**Comment by priyanshiiit** [comment]
Hi @wiz @softsimon 
I can do this by using something like `style="font-size:24px;" ` for each heading and make it consistent across all pages.
