### ISSUE TITLE
Testnet transaction hex links use mainnet URLs

### ISSUE THREAD

**Issue by nothingmuch** [mempool/mempool#699]
### Description

Testnet Transaction Hex link links to mainnet URI for the testnet txid, so it is not found.

#### Version

v2.2.1-dev [99adccf]

### Steps to reproduce

Open a [testnet transaction](https://mempool.space/testnet/tx/0a4ef23d87e2f6c054b21cf345e26fb092d8b7c42729af98a5262f3009c53221)

Click [Transaction Hex](https://mempool.space/api/tx/0a4ef23d87e2f6c054b21cf345e26fb092d8b7c42729af98a5262f3009c53221/hex) and observe that it is a 404.

### Expected behaviour

The API URL should be prefixed the same way, e.g. https://mempool.space/testnet/api/tx/0a4ef23d87e2f6c054b21cf345e26fb092d8b7c42729af98a5262f3009c53221/hex

### Actual behaviour

A link to a non-existent mainnet transaction is generated instead, e.g. https://mempool.space/api/tx/0a4ef23d87e2f6c054b21cf345e26fb092d8b7c42729af98a5262f3009c53221/hex is used instead

**Comment by nothingmuch** [comment]
This prefix appears to be hard coded, whereas everything else uses e.g. `[routerLink]="['/tx/' | relativeUrl, txId]"`:

https://github.com/mempool/mempool/blob/8eb70416da99ef5379370b0684f9f8204e0fcb9a/frontend/src/app/components/transaction/transaction.component.html#L221

**Comment by softsimon** [comment]
Good find!

**Comment by softsimon** [comment]
Closed in 11817c0
