### ISSUE TITLE
Need better Install Guide if possible

### ISSUE THREAD

**Issue by yunier2002** [mempool/mempool#7]
For people that are not as familiar with the command line and dev in general. 

Tried getting it to work on my ubuntu machine but having some issues on the RPC connection to my node. I know RPC is working on my node as it's being used by my Electrum Personal Server.  My bitcoin.conf file has the correct RPC credentials as well as port and I have also whitelisted IPs. mempool-config.json file has the same info

Any help would be appreciated. Here is the error:

Error getBlockCount Error: ETIMEDOUT
      at Timeout._onTimeout (/usr/local/mempool/mempool.space/backend/node_modules/bitcoin/lib/jsonrpc.js:67:15)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7) {
  code: 'ETIMEDOUT'
)

Also, the instructions for nginx.conf are not good enough I'm lost on that part too. Not sure where the "dist" that I need to copy is and also getting the same error reported by another user on the SSL part of the config file.

**Comment by wiz** [comment]
Hey @yunier2002 are you on Keybase? If so send me a DM @wiz and I'd be happy to help you setup the mempool on your local machine. I wrote the setup instructions from my notes after setting it up by myself, so I'm sure they can be improved and I would like to incorporate your feedback and other friction points into improving the README.

**Comment by wiz** [comment]
Oops didn't mean to close this issue, pressed button by accident. As for your actual issue, it sounds like your mempool-space backend is having trouble connecting to your Bitcoin full node. Also note that nginx is completely optional and not required for a personal setup. It's only provided as a reference if you wish to use nginx.

**Comment by wiz** [comment]
As for the nginx issues I've just pushed some updates related to that which should hopefully resolve your issue.

**Comment by softsimon** [comment]
README contains install instructions now.
