### ISSUE TITLE
Transaction fee color bands fail to remain turned off after page auto-refresh

### ISSUE THREAD

**Issue by ericrpatton** [mempool/mempool#70]
I have the transaction fee ranges of 1-2 sats/vbyte turned off on the TV display, and when the page auto-refreshes, they get turned back on. I am only interested in the fee color ranges where my transactions are, and I turn off all lower fee ranges to maximize the vertical real estate on the screen. Every minute when the mempool.space refreshes though, it turns them back on, which is annoying. 

It would great if the page respected the settings after auto-refreshes.

**Comment by dnunes** [comment]
It worth noting that this problem happens on both "TV view" and "graphs" area.

It resets the filters, but the boxes stay the way they were. And when you click any boxes, it reapplies the filter correctly. It looks like a very simple fix.

**Comment by softsimon** [comment]
https://github.com/CodeYellowBV/chartist-plugin-legend/issues/48
