### ISSUE TITLE
UX: Content of network selection dropdown not visible on mobiles

### ISSUE THREAD

**Issue by rene78** [mempool/mempool#700]
### Description

Content of network selection dropdown not visible on mobiles

#### Version

v2.2.1-dev [99adccf]

### Steps to reproduce

Open network selection dropdown on phone

### Expected behaviour

Should be shown

### Actual behaviour

Not visible

### Screenshots

![image](https://user-images.githubusercontent.com/36115705/128597946-bbd977bb-2248-4c2e-801d-7806cdaa559f.png)

#### Device or machine

Mobiles

**Comment by softsimon** [comment]
It works for me so could you specify which phone model that is affected?

![Screenshot_20210807-144753](https://user-images.githubusercontent.com/8561090/128599104-56a5e6bf-3e00-4a32-9ee0-eeb2262c3f98.png)

**Comment by rene78** [comment]
I use a Redmi Note 5 from Xiaomi and checked with Chrome for Android and Brave Browser Android (both the latest versions). Same is true for the Dev Tools of Chrome and Edge when switching to mobile view.  Of course those are all browsers based on V8.
