### ISSUE TITLE
V1: Unable to display past block ~629800 - 629802

### ISSUE THREAD

**Issue by rbrooklyn** [mempool/mempool#71]
Something strange is happening with version 1.0.0

Myself and several others users are struggling to show blocks beyond roughly 629800 - 629802 or so.

Nothing odd in the output from the backend.

Just lines of "Fetching block tx XXX of XXX". However, it's extremely slow to make any progress. Sometimes it can make excellent progress very quickly, then it will "hit a wall" and make barely any progress at all after that point.

I think it's getting stuck on some specific transactions somehow. Difficult to tell.

The graph for the mempool still updates, but the blocks part of the UI is stuck on block 629802 for me, and 629800 for another user.

**Comment by softsimon** [comment]
I can see that block 629800 is filled with transactions having 90 inputs each.

It's a long standing issue sadly. It's due to very heavy transactions that takes a very long time to do recursive fee lookups on. And we only can wait for the fetching to finish which may take several minutes for a single transaction.

It's the reason mempool v2 is relying on electrs which is a real transaction index. But the goal is to give v1 some more love soon and solve this issue somehow. I have been considering lazy loading.

**Comment by wiz** [comment]
@rbrooklyn what hardware are you running your mempool v1 node on? can you let us know what kind of specs you have for CPU, RAM, SSD, etc. ?

**Comment by rbrooklyn** [comment]
> @rbrooklyn what hardware are you running your mempool v1 node on?

Pretty low end. Raspberry pi 4, 4gb, 1tb crucial SATA SSD connected through USB2. Ubuntu 20.04. non docker install.

The other people I am talking to have similar hardware but are using MyNode instead of Ubuntu.

Bitcoin core is able to keep up without issue. However I suspect that actually core might be the bottleneck here? Any configuration tweaks I could try to help it along?

**Comment by softsimon** [comment]
No matter the hardware, it's a bug that needs to be fixed.

**Comment by wiz** [comment]
IIRC there were many TX in those blocks that are computationally expensive to calculate the fees for, and V1 with Bitcoin Core will have difficulty doing it on low-powered hardware. I think the solution is for us to ship V2 with electrs light mode support, which would work on a RPI4 with 1TB SSD, and you would be able to use the full explorer just quite slow performance.

**Comment by rbrooklyn** [comment]
Electrumx yields dramatically improved performance on a Raspberry Pi 4. Without any benchmarks it's night and day when I connect to it. Jameson Lopp recently did some benchmarks I believe so that might be interesting.

The issue with v2 currently is that it requires the blockstream fork of electrs/electrumx/whatever, which is very heavy on modest hardware.

If it could be made to work with "any" electrum server implementation that would be the ideal, but I have no idea how difficult that might be.

**Comment by wiz** [comment]
yes that's what the blockstream/electrs light mode is intended for

**Comment by wiz** [comment]
Closing as WONTFIX - will be fixed in v2.0 release instead
