### ISSUE TITLE
Implement new dashboard widgets for Liquid

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#718]
- [ ] Monitor status of hard fork for dynafed activation

similar to taproot activation lock-in
it happens in 144 block epochs
get version number, look at bit 25(&10000000000000000000000000).
if 75% signal in an epoch
range is from [%144=1 to %144=0]

- [ ] Monitor status of functionaries

identify functionary ID from coinbase transaction bytes
reference implementation is inside `parser.zip`
tag each block by who "mined" it using functionary ID
also on blocks page table indicate which functionary
want to see a "mining dashboard" which shows if functionaries are offline
based on last XXXX blocks mined, need a main dashboard widget to show 15/15 functionaries online

- [x] Monitor status of L-BTC in circulation and BTC pegged-in

use liquid bitcoin asset data to get the two numbers
display on main dashboard as a new widget like 3000 BTC pegged in / 3000 L-BTC in circulation
numbers will be slightly off due to human error where some L-BTC was burned, but >100% reserves

- [ ] Monitor status of UTXOs owned by federation

refer to screenshots sent privately that identify UTXOs in federation 11 of 15 multisig wallet
refer to code in `parser.zip` to idenfiy UTXOs
make a new page with table that lists all Liquid UTXOs and list their locktime expiration

**Comment by wiz** [comment]
The first one might not make sense for mempool, need to consider alternatively forking the taproot.watch website code for the dynafed hard-fork lock-in monitoring

**Comment by softsimon** [comment]
Closing to create new separate issues

https://github.com/mempool/mempool/issues/1025
https://github.com/mempool/mempool/issues/1026
