### ISSUE TITLE
Foundry USA Pool block labelled as "unknown"

### ISSUE THREAD

**Issue by zowki** [mempool/mempool#719]
### Description

Miner for this block is incorrectly labelled as "unknown":
https://mempool.space/block/000000000000000000032ab9c8d3265b35e798e8e5d5134c12f2e1b20ae46f72

It should be "Foundry USA Pool".

Mempool should identify Foundry USA Pool blocks by looking for only the sub-string "Foundry USA Pool".

### Steps to reproduce

View this page:
https://mempool.space/block/000000000000000000032ab9c8d3265b35e798e8e5d5134c12f2e1b20ae46f72

### Expected behaviour

Miner is "Foundry USA Pool"

### Actual behaviour

Miner is "unknown"

### Screenshots

![Capture](https://user-images.githubusercontent.com/8691083/129488053-da78c1db-417f-40fc-8789-ded3c8266f19.PNG)

#### Device or machine

Windows 10, Firefox

**Comment by wiz** [comment]
mempool uses the btccom maintained list of known mining pools, for updates you should make a PR to https://github.com/btccom/Blockchain-Known-Pools

**Comment by zowki** [comment]
Thanks, PR submitted here:
https://github.com/btccom/Blockchain-Known-Pools/pull/89
