### ISSUE TITLE
Poor french translation

### ISSUE THREAD

**Issue by agyx** [mempool/mempool#723]
### Description

The string "2 minutes depuis" is not french 

#### Version

v2.2.2-dev

### Steps to reproduce

Show main page with french localisation

### Expected behaviour

Display "Il y a 2 minutes" instead of "2 minutes depuis" (meaning 2 minutes ago)

### Actual behaviour

It shows string in description

### Screenshots

<img width="168" alt="Capture d’écran 2021-08-17 à 06 28 31" src="https://user-images.githubusercontent.com/40133678/129663779-99ba9473-fa83-4bb8-9742-45af9413fa67.png">

#### Device or machine

macOS Catalina 10.15.7

#### Additional info

n/a

**Comment by wiz** [comment]
If you'd like to help our translations please sign up at https://www.transifex.com/mempool/mempool/

**Comment by agyx** [comment]
I did but I could not join the project as French was not an option

**Comment by agyx** [comment]
I did

**Comment by Bayernatoor** [comment]
I'll approve your application. 

That translation is now fixed. If you'd like to run through the rest and clean them up that would be appreciated. Some were directly translated without much context so there may be a few others that are off.

**Comment by agyx** [comment]
Thanks. Sure I will look into it.
