### ISSUE TITLE
UX: Arrows navigation works for all pages.

### ISSUE THREAD

**Issue by MiguelMedeiros** [mempool/mempool#732]
### Description
Arrows navigation works for all pages.

### Expected behaviour
Arrows navigation should not work on other pages.

### Version
v2.2.2-dev [04f1879]

### Steps to reproduce
1. Click on the about page.
2. Press right arrow key.

### Preview
![bug-arrows-about-page](https://user-images.githubusercontent.com/5798170/129902511-26c7b416-a3c3-4983-9175-22c5bf265248.gif)

**Comment by softsimon** [comment]
Fixed in 58178f4
