### ISSUE TITLE
Wrong number of tx in a block

### ISSUE THREAD

**Issue by gustavonalle** [mempool/mempool#74]
Using version ```v1.0.0``` the blocks always have 1 less transaction:

<img width="518" alt="Screenshot 2020-05-17 at 12 45 47" src="https://user-images.githubusercontent.com/440989/82143545-a2805300-983c-11ea-92fd-180b28c6715e.png">

I checked with my full node and it is returning the correct number.

**Comment by softsimon** [comment]
Duplicate issue #27
