### ISSUE TITLE
Mempool website gets stuck on "Maiting for blocks..." in certain situation

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#77]
### Description

Certain steps cause mempool website to crash and get stuck on "waiting for blocks..."

#### Version

68664968da41f3a80a3e4b0200c5902c4904be29

### Steps to reproduce

1) Open https://mempool.space/ in Chrome
2) Use pull-down to change to Liquid
3) Use pull-down to change to Mainnet
4) Click on Graphs
5) Press back button in web browser

### Expected behaviour

Site should load normally

### Actual behaviour

Site gets stuck on "Waiting for blocks..." for a long time or forever

### Screenshots

<img width="268" alt="Screen Shot 2020-05-27 at 11 12 56" src="https://user-images.githubusercontent.com/232186/82969696-107e0480-a00b-11ea-9751-08a8eff89880.png">

**Comment by softsimon** [comment]
This was fixed in c21dad8 although it introduced a new flickering when switching network -> #95
