### ISSUE TITLE
Addresses hidden after upgrade to bitcoin core v22.0

### ISSUE THREAD

**Issue by darthginger** [mempool/mempool#778]
### Description
After upgrading to bitcoin core v22 i noticed that address fields are either empty or just show the type of address.

#### Version
https://github.com/mempool/mempool/commit/9bdf42530ab1be2f635c853c2e8666cae914fd37

### Expected behaviour
Show addresses as a clickable link.

### Actual behaviour
No address shown, no link to click.

### Screenshots
![image](https://user-images.githubusercontent.com/8257956/133263912-45a0c5ee-68fb-4374-aa53-3e5cd32b06e2.png)

#### Device or machine
Debian GNU/Linux 11 (bullseye)

#### Additional info
https://github.com/romanz/electrs/releases/tag/v0.8.11
node v14.17.6
manual install of mempool
browser console:
![image](https://user-images.githubusercontent.com/8257956/133265211-113f8b8c-6b56-440a-9d1f-535dd76e0b50.png)

**Comment by softsimon** [comment]
Thanks for reporting. I can confirm this issue on my node.

**Comment by softsimon** [comment]
Will make a fix for this soon, but in the meantime you may launch `bitcoind` with `-deprecatedrpc=addresses` and it should fix it.
