### ISSUE TITLE
New chart library sets cookies on page load

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#784]
We should not set any cookies unless the user needs to save a preference or changes locale etc.
<img width="435" alt="Screen Shot 2021-09-16 at 18 51 27" src="https://user-images.githubusercontent.com/232186/133591810-5dcec53a-cd5b-4e76-bb7f-a28c670d0b76.png">

**Comment by MiguelMedeiros** [comment]
These cookies are related to Matomo, not echarts.
Take a look here: https://matomo.org/faq/general/faq_146/
![image](https://user-images.githubusercontent.com/5798170/133622089-ff4432d9-542f-4748-ad45-10e63bde80e1.png)
