### ISSUE TITLE
UI/UX: Confirmations button positioning has changed

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#815]
Before:
<img width="360" alt="Screen Shot 2021-09-25 at 16 34 10" src="https://user-images.githubusercontent.com/8561090/134771823-678f3fa8-1860-4d6e-8feb-fc8fdd10f4e2.png">

Currently:
<img width="358" alt="Screen Shot 2021-09-25 at 16 35 22" src="https://user-images.githubusercontent.com/8561090/134771826-8bb29ea5-89f4-4dc9-9414-d00cd0e5bb90.png">

**Comment by wiz** [comment]
I can't reproduce this bug on production, how do you reproduce it?
