### ISSUE TITLE
utxo goes wrongly from unspent to spent, refreshing page sets it correctly to unspent

### ISSUE THREAD

**Issue by katesalazar** [mempool/mempool#832]
### Description

when spying an invoice address,
in (at least) last transaction,
where last utxo is unspent,
upon receiving new funds,
a sound plays,
old transaction's utxo goes wrongly from unspent to spent,
refreshing page sets it correctly to unspent,
this is mainnet

#### Version

web? mempool.space, today

### Steps to reproduce

if this is unseen, tell me and I'll try my best to make you a video
demonstrating on testnet

### Expected behaviour

do not show weird changes

### Actual behaviour

utxo goes wrongly from unspent to spent, until refreshing the page

### Screenshots

missed them for now...

#### Device or machine

an apple laptop running macOS

#### Additional info

vivaldi 4.2

**Comment by softsimon** [comment]
Thanks for your bug report.

I believe this previous issue could be the same issue https://github.com/mempool/mempool/issues/412

**Comment by katesalazar** [comment]
[duplicate](https://github.com/mempool/mempool/labels/duplicate) #412

**Comment by katesalazar** [comment]
removed browser info and removed past revisions
