### ISSUE TITLE
Toggling fee rate bands shows 2h graph over 24h timeline, switching graphs shows hidden bands

### ISSUE THREAD

**Issue by Xekyo** [mempool/mempool#86]
### Description

When looking at the longer time periods starting with the [24h graph](https://mempool.space/graphs#24h) and toggling one of the fee bands, the graph jumps to show the 2h history instead.

#### Version

Currently live on the website.

### Steps to reproduce

* Go to [graphs](https://mempool.space/graphs)
* Click 24h
* Toggle fee rate band

### Expected behavior

The 24h graph should be shown and the toggled fee rate band should be hidden.

### Actual behavior

Instead of showing the selected time frame with the fee rate band hidden, it jumps to show the 2h graph with the fee rate band hidden. The x-axis still shows the 24h timeline.

Additional observations: afterwards switching to the 2h graph for comparison shows the 2-3 sat/vB band, even though the button is still toggled. Going to 24h graph afterwards exhibits the same behavior: the 2-3 button is still toggled "off", but the band is showing.

### Screenshots
Visit 24h graph:
![image](https://user-images.githubusercontent.com/4060799/84599056-186be000-ae24-11ea-8a52-32a656ff5c47.png)

Click "2 - 3":
![image](https://user-images.githubusercontent.com/4060799/84599070-2883bf80-ae24-11ea-97f6-0f0e68996e5e.png)

Click 2h (Live) fixes time-axis, returns 2-3 fee rate band:
![image](https://user-images.githubusercontent.com/4060799/84599093-6254c600-ae24-11ea-86f5-96fecd4a97b0.png)

Returning to 24h graph (2-3 still toggled to be hidden):
![image](https://user-images.githubusercontent.com/4060799/84599179-ea3ad000-ae24-11ea-82ae-3abe5cb52406.png)

#### Device or machine

Firefox 77.0.1 (64-bit), Linux

**Comment by TechMiX** [comment]
#143 would fix this.

**Comment by softsimon** [comment]
Fixed in 53bc772 by @TechMiX

**Comment by Xekyo** [comment]
@softsimon: Is that patch already deployed? I just tested the behavior I described above and it persists.

**Comment by softsimon** [comment]
It is not deployed on the live environment just yet.

**Comment by Xekyo** [comment]
Can confirm that the issue I was seeing is fixed. :+1:
