### ISSUE TITLE
Unicode Emoji support

### ISSUE THREAD

**Issue by SeverinAlexB** [mempool/mempool#875]
### Description

With the new [Murray Rothbot](https://murrayrothbot.com/opreturn), one is able to write OP_RETURN messages to the blockchain. Unfortunately, Unicode Emojis are displayed as `??`. I would love to the the actual emojis.

See [example](https://mempool.space/tx/cb9004666b28fdd2c54f9f8bbaa81d7fdcf2f99f27d596c4d58092c6cadaeb08).

And if you are already working on it, why not display the whole message? :)

#### Version

Current

### Steps to reproduce

Send a message with the Murray Rothbot including a unicode emoji.

### Expected behaviour

Show unicode emojii properly.

### Actual behaviour

`??`

### Screenshots

<img width="568" alt="CleanShot 2021-10-13 at 09 44 50@2x" src="https://user-images.githubusercontent.com/8782386/137081059-6ae45b90-3efc-4330-9ba4-3a7e9558ffc5.png">

#### Device or machine

-

#### Additional info

-

**Comment by knorrium** [comment]
@SeverinAlexB @wiz this seems to be a problem while encoding the data, not decoding it.

For reference, the Murray Rothbot site is removing those characters and decoding the raw data with other tools like [this](https://www.online-toolz.com/tools/text-hex-convertor.php) also shows `??`.
