### ISSUE TITLE
Liquid asset page incorrectly displays issuance data

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#88]
### Description

Liquid asset page incorrectly displays issuance data

#### Version

c4d4d931f198469201f939c13b2fca41ee0e4c31

### Steps to reproduce

1) https://blockstream.info/liquid/asset/eba8e373cf3e254b245139386debf2441ac43a834156c07c0505b489bd2c83b6
2) https://mempool.space/liquid/asset/eba8e373cf3e254b245139386debf2441ac43a834156c07c0505b489bd2c83b6

### Expected behaviour

Data on 1 and 2 should match

### Actual behaviour

Data on 1 for issued amount is 1000
Data on 2 for issued amount is 0

**Comment by softsimon** [comment]
Fixed in 490223
