### ISSUE TITLE
small RTL issue

### ISSUE THREAD

**Issue by EZ0010** [mempool/mempool#888]
Hi, network selection dropdown is not shown correctly on small devices when website language is RTL.

<img width="273" alt="Screen Shot 2021-10-26 at 7 10 13 PM" src="https://user-images.githubusercontent.com/75021359/138920495-bd87586b-e2c3-4a6b-a2a2-705281706f16.png">

Also please can you give me a reviewer role for Arabic language? there are 10 translators and 0 reviewers, the current translation has a lot of grammar mistakes (and some translations doesn't even make sense, mostly due to using google auto translation) and without a reviewer role no one can fix anything.

here is an example, this "vB/s" was translated to "Visual/textual foundations"
<img width="299" alt="Screen Shot 2021-10-26 at 7 21 21 PM" src="https://user-images.githubusercontent.com/75021359/138920751-416d6c8a-af87-4dc9-ba16-eaec49c561e7.png">
<img width="283" alt="Screen Shot 2021-10-26 at 7 21 28 PM" src="https://user-images.githubusercontent.com/75021359/138920780-6005a1f7-7106-49ba-be69-2c8ada3c8928.png">

**Comment by EZ0010** [comment]
still waiting

**Comment by wiz** [comment]
ok reviewer
