### ISSUE TITLE
Have a way to scroll the blocks chain to the right.

### ISSUE THREAD

**Issue by Transisto** [mempool/mempool#907]
![image](https://user-images.githubusercontent.com/388716/140962642-d28b8823-06ef-470d-a38b-55d8106bd5c2.png)

Currently it's possible by dragging the text select toward the right.

Not optimal, what about a > button on the right side like so.

![image](https://user-images.githubusercontent.com/388716/140963278-256f6e58-10cf-409b-be63-23df6c73280d.png)

**Comment by jorisvial** [comment]
Actually you can already by holding the shift key and scrolling (that's pretty common for horizontal scrolling). Though using mouse drag would obviously be better for UX.

**Comment by Transisto** [comment]
Yeah, mobile and touchscreen have an easier time scrolling horizontally.
