### ISSUE TITLE
Feerate bands in legend mislabeled, band ranges off-by-one?

### ISSUE THREAD

**Issue by Xekyo** [mempool/mempool#908]
### Description

The ranges of the bands in the legend indicate that the lowest tracked band is "0 - 1". However, the data appears to match what other mempool visualizers show for 1–2 sat/vB (1 inclusive, 2 exclusive). I assume that the lowest band is actually showing 1.000–1.999 sat/vB and all bands in the legend are mislabeled.

#### Version

node203.mempool.space (v2.3.0-dev) [af5e0d7c]

### Steps to reproduce

Look at chart, compare with other charts for the same data.

### Expected behaviour

* Unless the mempool data includes transactions below `minRelayTxFeerate`, the lower bound on the lowest band should be 1 sat/vB, not 0 sat/vB.
* Transaction building will often overestimate the transaction size by a few bytes since ECDSA signatures don't have consistent size. To ensure that the targeted feerate is met, the fees are calculated from the expected maximum size. Therefore, transactions created with a target feerate of e.g. X sat/vB will usually land in the range of X.000–X.010 sat/vB. It would be very odd to separate bands between X.000 sat/vB and X.001 sat/vB, so I assume that the intention is for feerate bands to be {1.000–1.999 sat/vB, 2.000–2.999 sat/vB, …, X.000–X.999 sat/vB} as this would group transactions created with the same feerate target.
* [Number ranges should be formatted as "X–Y"](https://www.dailywritingtips.com/use-a-dash-for-number-ranges/) without spaces and an en dash instead of a hyphen. It would be preferable if they were labeled differently altogether, since e.g. in "1–2", "1" should be included and "2" should be excluded. I suggest "1+" instead.

### Actual behaviour

* The label doesn't clearly demarcate whether transactions with exactly 2.000 sat/vB would land in 1–2 or 2–3 (should be 2–3).
* The transactions with feerates 1.000–1.999 sat/vB appear to be labeled as "0 - 1" in the chart's legend.
I assume that the data is actually bucketed as expected (see above), but the labels incorrectly indicate that the lowest band to be between 0 and 1. Very likely that feerate band should be labeled 1+, since that would be consistent with the expectation that most tracked transactions are above or equal to `minRelayTxFeeRate` and would correspond to other mempool visualizers.

### Screenshots

![image](https://user-images.githubusercontent.com/4060799/140972622-e685b52e-8db9-41e4-bf78-0025de64b6e7.png)
![image](https://user-images.githubusercontent.com/4060799/140973054-a09193c2-f291-4354-a8d2-26c467467ee3.png)

**Comment by softsimon** [comment]
Thanks for the extensive report. It may very well be wrong currently. I will investigate and report back to you.
