### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by webdev866** [mempool/mempool#909]
Hi, this project is excellent, I would like to thank all the team involved to bring such a beautiful block explorer, my question is, can I use it for an altcoin? would that work?

**Comment by wiz** [comment]
no

**Comment by webdev866** [comment]
why? can you explain?

**Comment by wiz** [comment]
we only support bitcoin, a bitcoin sidechain called liquid, and a bitcoin p2p exchange called bisq

**Comment by softsimon** [comment]
> why? can you explain?

If the altcoin is a fork of Bitcoin.. it can work with minor modifications, otherwise not.

**Comment by webdev866** [comment]
Actually the fork is based on Litecoin
