### ISSUE TITLE
[Taproot] Backend needs to be reindex for autocomplete to show correct bech32m addresses

### ISSUE THREAD

**Issue by knorrium** [mempool/mempool#911]
Steps to reproduce:

1) Type in `bc1pqy` on the search bar.
2) Select the first result
3) Notice it loads `bc1pqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqs3wf0qm` instead of `bc1pqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqsyjer9e` which is the correct bech32m address

**Comment by wiz** [comment]
done on mempool.space

**Comment by Emzy** [comment]
done on mempool.emzy.de
