### ISSUE TITLE
Outputs not showing

### ISSUE THREAD

**Issue by sjorsvanheuveln** [mempool/mempool#925]
I just installed mempool locally. Everything is working fine, except I don't see input/output data in transactions.

First thought it was txindex in my bitcoin file, but it's set to 1.

What could be causing the issue here?

**Comment by softsimon** [comment]
Which input/output data is missing? Could you share a screen shot?

**Comment by sjorsvanheuveln** [comment]
<img width="1131" alt="Screenshot 2021-11-14 at 12 25 25" src="https://user-images.githubusercontent.com/13645429/141678883-7547a382-f9c9-4e3e-ab0d-c692a58a1090.png">

**Comment by softsimon** [comment]
Ah right. This is related to the Bitcoin Core v22 support which we have fixed but it's not in the current available release https://github.com/mempool/mempool/pull/779

You can fix it instantly by adding
`deprecatedrpc=addresses` to your `bitcoin.conf`

**Comment by sjorsvanheuveln** [comment]
Thanks ser. Fully operational here!
