### ISSUE TITLE
[Solved]Invalid params when starting backend

### ISSUE THREAD

**Issue by nR2Cncdm** [mempool/mempool#972]
### Description

When I follow the instructions to manually install, I am unable to successfully start the backend

#### Version

v2.2.2

### Steps to reproduce

I created a separate user 'mempool' and completed the mariadb steps under an admin account.

### Expected behaviour

  Mempool updated in 0.189 seconds
  Updating mempool
  Mempool updated in 0.096 seconds
  Updating mempool
  Mempool updated in 0.099 seconds
  Updating mempool
  Calculated fee for transaction 1 / 10
  Calculated fee for transaction 2 / 10
  Calculated fee for transaction 3 / 10

### Actual behaviour

Dec  4 17:15:11 [22972] DEBUG: Starting Mempool Server... (1e40ec4)
Dec  4 17:15:11 [22972] INFO: Database connection established.
Dec  4 17:15:11 [22972] INFO: Starting statistics service
Dec  4 17:15:11 [22972] INFO: Starting currency rates service
Dec  4 17:15:11 [22972] NOTICE: Mempool Server is running on port 8999
Dec  4 17:15:11 [22972] INFO: Connected to Electrum Server at 127.0.0.1:50002 (["electrs/0.9.3","1.4"])
Dec  4 17:15:11 [22972] DEBUG: Statistics cache created
Dec  4 17:15:12 [22972] DEBUG: updateMempoolInfo: Invalid params, response status code: 401
Dec  4 17:15:12 [22972] DEBUG: runMainLoop error: Invalid params, response status code: 401. Retrying in 5 sec.
Dec  4 17:15:12 [22972] DEBUG: {"code":-32602}
Dec  4 17:15:17 [22972] DEBUG: updateMempoolInfo: Invalid params, response status code: 401
Dec  4 17:15:17 [22972] WARN: runMainLoop error: Invalid params, response status code: 401. Retrying in 10 sec.
Dec  4 17:15:17 [22972] DEBUG: {"code":-32602}
Dec  4 17:15:28 [22972] DEBUG: updateMempoolInfo: Invalid params, response status code: 401
Dec  4 17:15:28 [22972] WARN: runMainLoop error: Invalid params, response status code: 401. Retrying in 20 sec.
Dec  4 17:15:28 [22972] DEBUG: {"code":-32602}

#### Device or machine

raspberry pi 4g
Linux 5.10.63-v8+ #1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021 aarch64 GNU/Linux

**Comment by softsimon** [comment]
Make sure that you have entered the correct login information to both these blocks in the backend json config
```
"CORE_RPC": {
    "HOST": "127.0.0.1",
    "PORT": 8332,
    "USERNAME": "mempool",
    "PASSWORD": "mempool"
  },
  "SECOND_CORE_RPC": {
    "HOST": "127.0.0.1",
    "PORT": 8332,
    "USERNAME": "mempool",
    "PASSWORD": "mempool"
  },
```

**Comment by nR2Cncdm** [comment]
I don't have a second_core_rpc, here's mine:

{
  "MEMPOOL": {
    "NETWORK": "mainnet",
    "BACKEND": "electrum",
    "HTTP_PORT": 8999,
    "SPAWN_CLUSTER_PROCS": 0,
    "API_URL_PREFIX": "/api/v1/",
    "POLL_RATE_MS": 2000,
    "CACHE_DIR": "./cache",
    "CLEAR_PROTECTION_MINUTES": 20,
    "RECOMMENDED_FEE_PERCENTILE": 50,
    "BLOCK_WEIGHT_UNITS": 4000000,
    "INITIAL_BLOCKS_AMOUNT": 8,
    "MEMPOOL_BLOCKS_AMOUNT": 8,
    "PRICE_FEED_UPDATE_INTERVAL": 3600
  },
  "CORE_RPC": {
    "HOST": "127.0.0.1",
    "PORT": 8332,
    "USERNAME": "mempool",
    "PASSWORD": "<MY UNIQUE PASSWORD>"
  },
  "ELECTRUM": {
    "HOST": "127.0.0.1",
    "PORT": 50002,
    "TLS_ENABLED": true
  },
  "ESPLORA": {
    "REST_API_URL": "http://127.0.0.1:3000"
  },
  "CORE_RPC_MINFEE": {
    "ENABLED": false,
    "HOST": "127.0.0.1",
    "PORT": 8332,
    "USERNAME": "mempool",
    "PASSWORD": "mempool"
  },
  "DATABASE": {
    "ENABLED": true,
    "HOST": "127.0.0.1",
    "PORT": 3306,
    "DATABASE": "mempool",
    "USERNAME": "mempool",
    "PASSWORD": "mempool"
  },
  "SYSLOG": {
    "ENABLED": false,
    "HOST": "127.0.0.1",
    "PORT": 514,
    "MIN_PRIORITY": "info",
    "FACILITY": "local7"
  },
  "STATISTICS": {
    "ENABLED": true,
    "TX_PER_SECOND_SAMPLE_PERIOD": 150
  },
  "BISQ": {
    "ENABLED": false,
    "DATA_PATH": "/bisq/statsnode-data/btc_mainnet/db"
  }
}

**Comment by softsimon** [comment]
Ah yes .. My fault, ecause we changed the config structure 3 month ago that is not in the latest official release yet.

But there is no known bug in the latest v2.2.2 regarding the Bitcoin Core connection. Check so the information is correct and that the Bitcoin config is configured for accepting RPC requests and that the IP is allowed

**Comment by nR2Cncdm** [comment]
Yeah it's setup for rpc requests. I already have electrum and lightning currently working.

**Comment by wiz** [comment]
The 401 error means unauthorized so it's likely related to the core RPC credentials in the backend configuration

**Comment by nR2Cncdm** [comment]
Thanks wiz! I never restarted bitcoind after updating the config file. After restarting bitcoind, everything works!
