### ISSUE TITLE
Missing P2TR witness scripts

### ISSUE THREAD

**Issue by vostrnad** [mempool/mempool#973]
### Description

Unlike P2SH and P2WSH, P2TR spends (specifically script path spends) don't show the spending script.

### Steps to reproduce

Go to transaction 905ecdf95a84804b192f4dc221cfed4d77959b81ed66013a7e41a6e61e7ed530 on mainnet ([link](https://mempool.space/tx/905ecdf95a84804b192f4dc221cfed4d77959b81ed66013a7e41a6e61e7ed530)), expand the details of inputs and outputs and check the one input.

If I read [BIP 341](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#script-validation-rules) correctly this is a Taproot script path spend and the script (second to last witness element) decodes to:
```
febe583fa77e49089f89b78fa8c116710715d6e40cc5f5a075ef1681550dd3c4 OP_CHECKSIGVERIFY
d0fa46cb883e940ac3dc5421f05b03859972639f51ed2eccbf3dc5a62e2e1b15 OP_CHECKSIG
```

As you can see, this script isn't shown anywhere in the details.

### Screenshots

![p2tr](https://user-images.githubusercontent.com/43024885/144732743-31688a7c-8c84-4f7f-b637-70526e151604.png)

**Comment by softsimon** [comment]
Thanks for this report. I checked and it seems you are right. I just created a PR that should fix this. Please check it and see if looks like you expected as I am not super familiar with how the taproot scripting works and what to label it.
