### ISSUE TITLE
npm run start issue

### ISSUE THREAD

**Issue by webdev866** [mempool/mempool#975]
I got this error while running npm run start

`{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":50002}`

Dec  5 20:56:09 [26399] DEBUG: Starting Mempool Server... (1e40ec4)
Dec  5 20:56:09 [26399] ERR: Electrum error: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":50002}
Dec  5 20:56:09 [26399] ERR: Error connecting to Electrum Server at 127.0.0.1:50002
Dec  5 20:56:09 [26399] INFO: Disconnected from Electrum Server at 127.0.0.1:50002
Dec  5 20:56:09 [26399] INFO: Database connection established.
Dec  5 20:56:09 [26399] INFO: Starting statistics service
Dec  5 20:56:09 [26399] INFO: Starting currency rates service
Dec  5 20:56:09 [26399] NOTICE: Mempool Server is running on port 8999
Dec  5 20:56:09 [26399] DEBUG: Statistics cache created
Dec  5 20:56:09 [26399] DEBUG: Initial difficulty adjustment data set.
Dec  5 20:56:09 [26399] DEBUG: New block found (#2401)!
Dec  5 20:56:09 [26399] DEBUG: Fetching block tx 0 of 2
Dec  5 20:56:09 [26399] DEBUG: 0 of 2 found in mempool. 2 not found.
Dec  5 20:56:09 [26399] DEBUG: New block found (#2402)!
Dec  5 20:56:09 [26399] DEBUG: Fetching block tx 0 of 1
Dec  5 20:56:09 [26399] DEBUG: 0 of 1 found in mempool. 1 not found.
Dec  5 20:56:09 [26399] DEBUG: New block found (#2403)!
Dec  5 20:56:09 [26399] DEBUG: Fetching block tx 0 of 2
Dec  5 20:56:09 [26399] DEBUG: 0 of 2 found in mempool. 2 not found.
Dec  5 20:56:09 [26399] DEBUG: New block found (#2404)!
Dec  5 20:56:09 [26399] DEBUG: Fetching block tx 0 of 1
Dec  5 20:56:09 [26399] DEBUG: 0 of 1 found in mempool. 1 not found.
Dec  5 20:56:09 [26399] DEBUG: New block found (#2405)!
Dec  5 20:56:09 [26399] DEBUG: Fetching block tx 0 of 2
Dec  5 20:56:09 [26399] DEBUG: 0 of 2 found in mempool. 2 not found.
Dec  5 20:56:09 [26399] DEBUG: New block found (#2406)!
Dec  5 20:56:09 [26399] DEBUG: Fetching block tx 0 of 1
Dec  5 20:56:09 [26399] DEBUG: 0 of 1 found in mempool. 1 not found.
Dec  5 20:56:09 [26399] DEBUG: New block found (#2407)!
Dec  5 20:56:09 [26399] DEBUG: Fetching block tx 0 of 2
Dec  5 20:56:09 [26399] DEBUG: 0 of 2 found in mempool. 2 not found.
Dec  5 20:56:09 [26399] DEBUG: New block found (#2408)!
Dec  5 20:56:09 [26399] DEBUG: Fetching block tx 0 of 1
Dec  5 20:56:09 [26399] DEBUG: 0 of 1 found in mempool. 1 not found.
Dec  5 20:56:09 [26399] DEBUG: Updating mempool
Dec  5 20:56:09 [26399] DEBUG: Fetched transaction 1 / 2
Dec  5 20:56:09 [26399] DEBUG: Fetched transaction 2 / 2
Dec  5 20:56:09 [26399] NOTICE: The mempool is now in sync!
Dec  5 20:56:09 [26399] DEBUG: Mempool blocks calculated in 0 seconds
Dec  5 20:56:09 [26399] DEBUG: New mempool size: 2 Change: 2
Dec  5 20:56:09 [26399] DEBUG: Mempool updated in 0.016 seconds
Dec  5 20:56:11 [26399] DEBUG: Updating mempool
Dec  5 20:56:11 [26399] DEBUG: New mempool size: 2 Change: 0
Dec  5 20:56:11 [26399] DEBUG: Mempool updated in 0.002 seconds
Dec  5 20:56:13 [26399] DEBUG: Updating mempool
Dec  5 20:56:13 [26399] DEBUG: New mempool size: 2 Change: 0

**Comment by softsimon** [comment]
Your backend is configured to have a electrum server (romanz/electrs) and it is not able to connect to it.. That is your problem.

**Comment by softsimon** [comment]
For support questions like this, join our community channel on Telegram och Keybase.
